### ISSUE TITLE
The Article is shown in the wrong part of the documentation 

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/docs-v7#1014]
An Angular article is shown in the non-Angular part of the docs. - https://docs.nativescript.org/core-concepts/angular-navigation 
![screenshot 44](https://user-images.githubusercontent.com/17448734/34105625-c3dc1bba-e3fd-11e7-97b8-700f19d16a35.png)

**Comment by etabakov** [comment]
Closing as duplicate of https://github.com/NativeScript/docs/issues/1018
