### ISSUE TITLE
API docs utils/ad gives 404

### ISSUE THREAD

**Issue by pentool** [NativeScript/docs-v7#1017]
1. Go to this page: https://docs.nativescript.org/api-reference/modules/_utils_utils_
2. Under "Index", click on the "ad" link in the "Modules" section.
3. 404 Not Found

Well, this is weird. If I click on the URL I pasted above it directly takes me to the 404 page, which should not be the case. If this is what you get, then just

1. Go to the API docs page (https://docs.nativescript.org/api-reference/)
2. Click on the "utils/utils" at the bottom of the left side panel. That will take you to the correct page.
3. Then click the "ad" link under "Modules" which will 404

**Comment by etabakov** [comment]
Seems to be fixed now, so I'm closing the issue. Feel free to reopen if the problem arises again.
