### ISSUE TITLE
Template errors in Angular Groceries Tutorial

### ISSUE THREAD

**Issue by drkhannah** [NativeScript/docs-v7#1027]
I'm following Chapter 2 in the Tutorial and I get Template errors, Says elements are unknown, Why is this?

![screen shot 2017-12-27 at 9 42 52 am](https://user-images.githubusercontent.com/6707443/34384549-d2956d2a-eaea-11e7-8373-f071b0f26fd0.png)

![screen shot 2017-12-27 at 9 42 38 am](https://user-images.githubusercontent.com/6707443/34384555-d89691a4-eaea-11e7-8942-c76996a7ea4c.png)

**Comment by drkhannah** [comment]
I also don't get any intellisense for these elements, or for directives like (tap), only (click)

**Comment by NickIliev** [comment]
@drkhannah as suggested in the error, the project is most likely missing the NO_ERRORS_SCHEMA in the respective NgModule.

app.module.ts (or if using lazy loading the repsctive lazily loaded module)
```
import { NgModule, NO_ERRORS_SCHEMA, NgModuleFactoryLoader } from "@angular/core";

@NgModule({
    // more code here
    schemas: [
        NO_ERRORS_SCHEMA
    ]
})
```

Do let me know if you need further assistance on that matter.
