### ISSUE TITLE
One changelog to rule them all

### ISSUE THREAD

**Issue by tjvantoll** [NativeScript/docs-v7#103]
I'd like to suggest that there be a single changelog file that lives at http://docs.nativescript.org/Changelog, and that links to the more detailed changelogs (CLI, runtimes, and modules).

My reasoning is we really need a single place we can link to in order to show people exactly what changed in a given release. For instance it'd be great if @nativescript could tweet out, “1.1 is out! Here's what changed: http://docs.nativescript.org/changelog.

Ideally this “base” log could also give a three or four bullet summation of the release's major features, and again link to the more detailed changelogs or GitHub issues for more details.

cc @ligaz

**Comment by ErjanGavalji** [comment]
[Done with v1.5.0](https://github.com/NativeScript/NativeScript/releases/tag/v1.5.0).
[Click for the article](http://docs.nativescript.org/releases/changes).
