### ISSUE TITLE
Error 404 on link to Angular docummentation.

### ISSUE THREAD

**Issue by Leoat12** [NativeScript/docs-v7#1040]
Hello,

I realized that chapter 3 of the NativeScript + Angular tutorial gives an error 404 in one of the links to Angular documentation: https://docs.nativescript.org/angular/tutorial/ng-chapter-3. 
The link is the one showed in the image below: 
![capture](https://user-images.githubusercontent.com/5158198/34916688-3e55e454-f923-11e7-83e8-8df0031aa780.PNG)
 
 Thank you for the great job!

**Comment by sis0k0** [comment]
10x for logging that!

**Comment by Leoat12** [comment]
Thank you for the correction! 
I will keep an eye on the documentation while I read. If I find anything else, I will let you know. :)
