### ISSUE TITLE
Burger menu doesn't work on http://docs.telerik.com/devtools/nativescript-ui

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/docs-v7#1043]
_From @bearoutthere on January 16, 2018 10:43_

On my multi-screen setup i keep the documentation site on the side 23" monitors that are in portrait orientation. At that width the left navigation panel collapses into the hamburger menu.  Unfortunately when clicking on that menu nothing happens. I have to keep resizing the browser window in order to navigate. I've tried in Chrome and FF on Ubuntu 17.04.  It's broken in both browsers.  Not a big deal, but it's inconvenient and doesn't look good for the brand.
Just thought you'd want to know.

_Copied from original issue: NativeScript/NativeScript#5275_

**Comment by tsonevn** [comment]
Hi @bearoutthere,
Thank you for your feedback, 

Could you please provide also a screenshot, where the issue could be seen? 
Thank you in advance for your cooperation.

**Comment by BearOutThere** [comment]
Attached are the screenshots of the both states.  Once the left nav bar disappears in a narrower window clicking on the burger menu in the top left does nothing.  Inspecting it in the dev tools shows that the <span class="toggle-nav"><span></span></span> is empty.

![screenshot from 2018-01-17 10-09-33](https://user-images.githubusercontent.com/1024870/35023754-9fac74e6-fb6e-11e7-9e53-c985e15d4d50.png)

![screenshot from 2018-01-17 10-06-57](https://user-images.githubusercontent.com/1024870/35023747-99926480-fb6e-11e7-86e8-09700892e662.png)

![screenshot from 2018-01-17 10-06-38](https://user-images.githubusercontent.com/1024870/35023737-9133e926-fb6e-11e7-9bbe-f3965568e20e.png)

**Comment by tsonevn** [comment]
This issue was moved to telerik/nativescript-ui-feedback#489
