### ISSUE TITLE
Navigation title should be the same as page title

### ISSUE THREAD

**Issue by alvinkonda** [NativeScript/docs-v7#1069]
On the following page, the title on the navigation on the left (desktop view) is "Application Architecture" where the page title is "Application and Navigation". Normally, i think the menu item title should be the same as the page title, which in this case include the info for the navigation.

https://docs.nativescript.org/core-concepts/navigation

**Comment by etabakov** [comment]
Totally agree, a PR is on its way. Thanks for bringing the attention to this.
