### ISSUE TITLE
I think the blue notice should be removed on the end of each page

### ISSUE THREAD

**Issue by alvinkonda** [NativeScript/docs-v7#1074]
As we are developers there is no need to put this "distracting" notice on each page on the docs. If i have something to suggest, there is more than enough the button "improve this article" on the top. 
Also, most important, remember that I have to go to the docs several times each day to get familiar with NS, and probably over and over on each page to get familiar with the features.

However, i'm not sure what other devs thinks. Just my thoughts here...

**Comment by etabakov** [comment]
Hey @alvinkonda! Thanks for sharing your opinion. The feedback functionality is something that we added only recently. For the 2 months it has been in place, we received a lot of useful suggestions and critiques that we were not reported previously as an issue. Having in mind this, it proves valuable for us and we are executing on the feedback received. However, I can understand your point and we will definitely look for a way to make it less distracting.

Thanks once again!

**Comment by pedromorgan** [comment]
Yea sorry am a new kid on the `tns` block, but it don't work, the  was it helpful ?? 
too much brain damage about what "understanding what NS is before I even read.."

It a marketers and everyones dream, and maybe I see where the idea come from

https://www.gov.uk/government/organisations/air-accidents-investigation-branch

Its good to have a section at bottom for feedback.. but yes or no is 2 logical for end users...

eg it its a 
- 'yes' then i will never hit the bottom of page os will never click
- 'no' did not solve my problem, am i missing something ?
- 'was there something wrong'  .. ie 'improve page' ?

I tried "disqus" and alike on the revel.gh project and many other..

And my conclusion is that in my experiences across projects...
 - users will either fix it (ie via improve page)
- or raise an issue
- certainly I think improve page is wrong to be at top..

my 2pence worth, sorry for noise..
https://www.gov.uk/guidance/negligible-value-agreements

**Comment by pedromorgan** [comment]
@AlvinKonda Question.. where does the "feedback" end at ?? is there some mysterious list somewhere ??

**Comment by etabakov** [comment]
The blue notice was redesigned with the latest update to be less obtrusive. Closing the issue for now - feel free to open a new one if this is still an issue.

**Comment by pedromorgan** [comment]
Love new site.. thanks {NS} team ;-)

**Comment by etabakov** [comment]
Thanks @pedromorgan!
