### ISSUE TITLE
Fix z-index issue for search results in api-reference docs

### ISSUE THREAD

**Issue by mudlabs** [NativeScript/docs-v7#1076]
The search field at https://docs.nativescript.org/api-reference/ generates a list of results on input. 

The results are added to an `<ul class="results"></ul>`. But the `<ul>` sits behind the main content of the page.

To fix this the `<ul>` just needs to be given a `z-index` of `+1`.

Tested in;
- Chrome 64
- FireFox 58
- Safari 11
- Opera 49

**Comment by etabakov** [comment]
Sounds good @mudlabs! Thanks for the suggestion - you are most welcome to open a PR with this change.

**Comment by etabakov** [comment]
Deployed on LIVE.
