### ISSUE TITLE
File 'widgets-release' not found

### ISSUE THREAD

**Issue by sarathraj-coder** [NativeScript/docs-v7#1093]
In the doc ``` https://github.com/NativeScript/docs/blob/master/docs//integration-with-existing-ios-and-android-apps/extend-existing-android-app.md ``` mentioned a file named  ``` ns-stock-ticker/platforms/android/src/F0/widgets-release.aar ``` . But cant able to find the file in the F0 folder. i am using native script and vuejs. 

Also in the location(my-app/platforms/android/app/libs/runtime-libs) i can see two files named ``` nativescript-optimized.aar	nativescript-regular.aar ``` . That need to be corrected in the doc

**Comment by pedromorgan** [comment]
Ok so this is a default android app right ?

**Comment by OJ7** [comment]
Saw the same issue following the above tutorial using Nativescript and Angular.

Ended up using the `nativescript-optimized.aar` file and grabbing the `widgets-release.aar` from [here](https://github.com/NativeScript/sample-extend-android-app/blob/master/extended-app/CurrencyConversion/widgets-release/widgets-release.aar). Got it to build and run fine so far.

**Comment by vchimev** [comment]
Hey @sarathraj-coder, @pedromorgan, @OJ7,

Thank you for writing. The article has been updated with NativeScript version 4.0. Feel free to open issues and pull requests if you notice anything else.

References:
- https://docs.nativescript.org/guides/integration-with-existing-ios-and-android-apps/extend-existing-android-app
- https://github.com/NativeScript/docs/blob/master/docs/guides/integration-with-existing-ios-and-android-apps/extend-existing-android-app.md
