### ISSUE TITLE
Suggestion: Add documentation on Page navigation events

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/docs-v7#1099]
_From @bhavincb on March 16, 2018 21:32_

i was getting trouble with navigation data. i had to do some clean up work only when page is navigated using android hardware button or RouterExtentons backToPreviousPage function call.
i didn't find any relevant information regarding on page navigation event on nativescipt-angular documentation.
i had found this useful article on this [https://pointdeveloper.com/nativescript-page-navigation-events/](url).
there should be some official documentation regarding this.

_Copied from original issue: NativeScript/nativescript-angular#1239_

**Comment by pedromorgan** [comment]
Ok so its similar what I want as a newbie.. a list of events tags eg

```xml
<Page loaded="xx" navigatingTo ..etc
```

Can this be tagged as ```Page,Navigation```

**Comment by pedromorgan** [comment]
= https://stackoverflow.com/questions/39378547/understanding-the-page-events

Maybe we can ask this blog.. https://pointdeveloper.com/nativescript-page-navigation-events/

**Comment by tjvantoll** [comment]
We have documentation on this page https://docs.nativescript.org/core-concepts/navigation, but we should review whether this is thorough enough.
