### ISSUE TITLE
readSync with a function argument is confusing

### ISSUE THREAD

**Issue by surdu** [NativeScript/docs-v7#1111]
Having [this sync-named methods in file-system](https://docs.nativescript.org/cookbook/file-system#readingwriting-binary-data-fromto-a-file) that have what appears to be a callback function as the first argument can be really confusion for a JS developer. 

First of all, one would assume that the callback function will be called both in case of success and error, which is not the case.

Second of all, one would assume that callback function will be called asynchronously, which again is not the case.

Only after digging through the source code one would realize that that is actually a function to be called synchronously in case of error, a pattern which, as far as I can remember, I didn't see anywhere else in JS development.

My proposal, at least for the documentation, would be to omit that the sync methods can be passed an error handler function, and instead wrap the calls in a try...catch, which would make the code much easy to understand, and you'll know exactly how to treat errors.

For example, the code sample linked above would read:

```js
var fileName = "logo.png";
var error;

var sourceFile = fs.File.fromPath(__dirname + "/../" + fileName);
var destinationFile = fs.knownFolders.documents().getFile(fileName);

try {
  var source = sourceFile.readSync();
  destinationFile.writeSync();	
} 
catch (e) {
  console.error("Error occurred while copying files");
}
```

**Comment by surdu** [comment]
Giving it a closer look, it seems that the `onError`doesn't default to a function that throws error as I initially miss-read 😕. Maybe this should better be an feature request for NativeScript ?

**Comment by pedromorgan** [comment]
@surdu I bumped into similar problem... Im my case trying to read multiple files..

There needs to be maybe a "sync" and "async" api made clear

**Comment by pedromorgan** [comment]
The page needs an intro with.. 

there are two ways to read, write and scan to the file system.
- async or sync
= blocks code or continues and threads in background


and list 3 or 4 case examples.. eg camera shots, vs a cache file
