### ISSUE TITLE
Don't install Android SDK via brew, and then install Android Studio

### ISSUE THREAD

**Issue by ffxsam** [NativeScript/docs-v7#1117]
The step instructing users to install the Android SDK view brew should be removed. I followed the steps, and Android Studio's emulator failed to run. I did some Googling and found that the two installs don't play nicely together, so I removed the brew version, and set the following variables in my environment after installing Android Studio:

```sh
export ANDROID_HOME=/Users/samh/Library/Android/sdk
export ANDROID_SDK_ROOT=$ANDROID_HOME
```

And now the emulator works fine.

**Comment by pedromorgan** [comment]
Ok So i assume u on Mac right ?? (newbie with no mac)

**Comment by ffxsam** [comment]
Correct

**Comment by srokatonie** [comment]
I went through the procedure of Full setup on my Mac (the ruby command) 4 times recently, and it failed each time. The solution was:
1. Make sure you have Xcode installed
2. Make sure you have Android Studio installed and you run some example project in it (so it downloads SDKs and Build tools)
