### ISSUE TITLE
make it easy to use nativescript by using docker

### ISSUE THREAD

**Issue by oren** [NativeScript/docs-v7#112]
Docker is a great fit for NativeScript. instead of installing all the dependencies on the developer's laptop, everything can be inside a container and the installation can be done via a simple bash script.

It can be similar to this:
https://registry.hub.docker.com/u/kallikrein/android-cordova/

**Comment by enchev** [comment]
Hey @oren,

I'm closing this since you've already created such:
https://github.com/oren/docker-nativescript

Thanks!
