### ISSUE TITLE
cookbook/ doc sources are missing

### ISSUE THREAD

**Issue by pedromorgan** [NativeScript/docs-v7#1129]
I decided to look at #1111 as it confused me and fresh in mind..

However it seems a load of files are missing from the cookbook
- https://github.com/NativeScript/docs/tree/master/docs/cookbook

or am i missing something.

**Comment by etabakov** [comment]
The content of the cookbook is built from the [nativescript-sdk-examples-ng application](https://github.com/NativeScript/nativescript-sdk-examples-ng).
