### ISSUE TITLE
NativeScript identity +  style

### ISSUE THREAD

**Issue by pedromorgan** [NativeScript/docs-v7#1131]
Editors [hat on](https://www.youtube.com/watch?v=pKblP3_EkM0)..

see NativeScript in the docs and NativeScript every  here and everywhere NativeScript where..

I dont know where I seen it but  `{N}` but it is stuck in ones greymatter for this issue, at front not back at this moment in time.

so I like  **{N}** as its shorter than NativeScript, I love **{N}** cos i get home early to work late

eg from manual
Part of the data binding settings is the way data flows. NativeScript data binding supports the following data transmissions.

vs
Part of the data binding settings is the way data flows. **{N}** data binding supports the following data transmissions.

so markup would be
```
its so cool is **{N}**, runs on..
```
creates a
```
<strong>{N}</strong>
```
and in css can make green with purple etc
ie
```
strong[text="{N}"] {
  color: cool;
}

**Comment by etabakov** [comment]
Thanks for the suggestion @pedromorgan! We think that while {N} serves as a great logo, it is cryptic and might be confusing for new users that are not used to it. Also, it doesn't serve for SEO purposes and can be inconvenient when using accessibility features of the browser. 

Furthermore, [reading](https://en.wikipedia.org/wiki/Reading_(process)) is a much more complex process than parsing letters one by one. Words are perceived more like a block of character and with that said I believe that the overhead of the more letters in "NativeScript" worths the clarity that it has in front of "{N}".

Thanks for the feedback!
