### ISSUE TITLE
[Suggestion] forum.nativescript.org

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/docs-v7#1134]
_From @pedromorgan on April 12, 2018 0:31_

So can i propose that is forum is eveything, by name and not by domain..

and make  `forums.nativescript.org` a subdomain, instead of discoSource.nativescript.org (expected abba)

forum. subdomain seems obvious 2 me. and a redirect 304 after a 418

_Copied from original issue: NativeScript/NativeScript#5663_

**Comment by jlooper** [comment]
The forum is a Discourse forum, hosted on their servers, so we redirect to it via forum.nativescript.org.
