### ISSUE TITLE
Broken Link to Metadata Generator Article

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/docs-v7#1135]
The [metadata/generator](https://docs.nativescript.org/runtimes/android/metadata/generator) link returns `404`

**Comment by pedromorgan** [comment]
I'f love to know where that is supposed to link 2

**Comment by radeva** [comment]
This one: https://docs.nativescript.org/core-concepts/android-runtime/metadata/generating-typescript-declarations#android-dts-generator ?
