### ISSUE TITLE
No lists of events exist

### ISSUE THREAD

**Issue by vaindil** [NativeScript/docs-v7#1148]
I'm trying to create a new app and I need to know what events are available for various things, of course. I cannot for the life of me find a list of them anywhere. No page in the API reference has them, nothing in the docs has them (not even the dedicated Events page), they're nowhere to be found.

**Comment by pedromorgan** [comment]
So this is something I want also as a newbie, and apparently its in the api docs..
eg Page is https://docs.nativescript.org/api-reference/classes/_ui_page_.page

See https://github.com/NativeScript/docs/issues/1099
https://github.com/NativeScript/docs/issues/935

Its frustrating me a bit about the api-docs.. https://github.com/NativeScript/docs/issues/1132

Where I want to navigate same as namespace (not {N}).. eg api.nativescript.org/ui/page#Page.events

**Comment by NickIliev** [comment]
@vaindil  [here is the article](https://docs.nativescript.org/core-concepts/application-lifecycle) about the exposed application events and for accessing the native event as well. For the Angular based project, you can use the application events and also [the Angular component's lifecycle hooks](https://angular.io/guide/lifecycle-hooks)
