### ISSUE TITLE
creating-sidedrawer-button section is missing the code example

### ISSUE THREAD

**Issue by sebawita** [NativeScript/docs-v7#1160]
### Please, tell us what's the problem?
[ ] A typo
[ ] Wrong documentation
[ ] Improvement of existing article
[x] Missing documentation
[ ] New article needed

### Please, tell us more details
The code example is missing here:
https://docs.nativescript.org/angular/ui/action-bar#creating-sidedrawer-button

**Comment by etabakov** [comment]
Fixed and will be deployed with the next version on live.
