### ISSUE TITLE
Layout Documentation Not Found

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/docs-v7#1163]
_From @opsional on May 15, 2018 0:8_

Hello, i visit https://docs.nativescript.org/cookbook/ui/layouts/grid-layout and content not found.

_Copied from original issue: NativeScript/NativeScript#5816_

**Comment by tsonevn** [comment]
Hi @opsional
Thank you for letting us know about this broken link. We will check it and will provide the needed fix.
For now, the needed information could be found [here](https://docs.nativescript.org/cookbook/ui/layouts#grid-layout).

**Comment by etabakov** [comment]
Fixed with the latest update of the documentation.
