### ISSUE TITLE
Upgrade instructions do not cover Angular and Webpack upgrade

### ISSUE THREAD

**Issue by etabakov** [NativeScript/docs-v7#1172]
### Please, tell us what's the problem?
[ ] A typo
[ ] Wrong documentation
[X] Improvement of existing article
[ ] Missing documentation
[ ] New article needed

### Please, tell us more details
Currently, we have an article in the documentation that covers the upgrade instructions for the core modules, the runtimes and the CLI.

However, there are important optional packages that are not covered and it's not clear how they should be upgraded, namely:
 - nativescript-angular
 - nativescript-dev-webpack

We should provide instructions for those packages and their dependencies for the latest, next or specific version as this is done for the core framework.

**Comment by vakrilov** [comment]
@NickIliev @tsonevn -> Do you think you can extend this article to cover angular and webpack:
https://docs.nativescript.org/releases/upgrade-instructions

**Comment by NickIliev** [comment]
Resolved via [https://github.com/NativeScript/docs/pull/1242](https://github.com/NativeScript/docs/pull/1242)
