### ISSUE TITLE
Groceries 3.5 Routeing [Exercise: Create the list page]

### ISSUE THREAD

**Issue by laurinfritz** [NativeScript/docs-v7#1180]
### Please, tell us what's the problem?
[ ] A typo
[X] Wrong documentation
[ ] Improvement of existing article
[ ] Missing documentation
[ ] New article needed

### Please, tell us more details

**When I replace the constructor in login.component.ts from:**

constructor(private userService: UserService) {
        this.user = new User();
    }

**to:**

constructor(private router: Router, private userService: UserService) {

**the Template of the App crashes:**

<img width="407" alt="screenshot" src="https://user-images.githubusercontent.com/32292382/40981342-fcb19c78-68da-11e8-8dcf-719744278655.png">

Some ideas how to fix it?

**Comment by NickIliev** [comment]
@laurinfritz it is hard to say what may be causing your issue but check if you have imported the Angular `Router` in your login component. Also, you can use [the `master` branch of the sample-Groceries ](https://github.com/NativeScript/sample-Groceries/blob/master/app/login/login.component.ts)repository as a reference.

Please post the how-to related question in the community slack or other community channels where you would receive faster answers and in the meantime we will keep the repositories strictly for logging issues, features, and bugs.
