### ISSUE TITLE
How to nest elements in dynamically created ScrollView?

### ISSUE THREAD

**Issue by ickata** [NativeScript/docs-v7#1183]
### Please, tell us what's the problem?
[x] Improvement of existing article
[x] Missing documentation

### Please, tell us more details
Hi, I was looking for a way to append a `StackLayout` to dynamically generated `ScrollView`, however  the latter does not provide `addChild` method.

```js
var StackLayout      = require( 'ui/layouts/stack-layout' ).StackLayout;
var ScrollView       = require( 'ui/scroll-view' ).ScrollView;

const scrollview = new ScrollView();
scrollview.orientation = 'horizontal';
const stacklayout = new StackLayout();
stacklayout.orientation = 'horizontal';

console.log( typeof scrollview.addChild );   // undefined
```

**Comment by tjvantoll** [comment]
This one might actually be a core modules issue, as I would think ScrollView should have an `addChild()` method.

**Comment by vakrilov** [comment]
`ScrollView` is actually an implantation of `ContentView` so the right way to set it's content is by doing:
```
scrollview.content = stacklayout
```

Note: Only can only set a single `content` view. That's the reason there is not `addChild` method as it suggests multiple children are supported.
