### ISSUE TITLE
why Placeholder component is not part in the "Nativescript with Angular" tab menu?

### ISSUE THREAD

**Issue by darkyelox** [NativeScript/docs-v7#1186]
### Please, tell us what's the problem?
[ ] A typo
[ ] Wrong documentation
[ ] Improvement of existing article
[ X] Missing documentation
[ ] New article needed

### Please, tell us more details

There is not **Placeholder** entry into the list of the menu **User interface** on tab **Nativescript with Angular**, i don't test it in an Angular app but i think it works and maybe you can expecify that we can use an Angular Component with binding, etc. but internally using Placeholder tag with data binding, or  i'm wrong?

**Comment by NickIliev** [comment]
@darkyelox the `Placeholder` is strictly NativeScript Core concept and **won't work** in Angular.
We thought about adding an explicit note in the Core section but it seems confusing to talk about Angular in NativeScript Core.

In Angular, you could create custom component the Angular way (e.g via selectors you can reuse any Angular component)

**Comment by darkyelox** [comment]
But it works in angular like any nativescript angular component, even it has an event for initialize the native view, I'm using it successfully like this:
```html
<Placeholder (creatingView)="onCreatingView($event)"></Placeholder>
```

**Comment by NickIliev** [comment]
@darkyelox the thing is that although it would work the native elements created ni `creatingView` won't become part of the Angular renderer (they would appear but the layouts might break when assigning dynamic changes for width, height, CSS, etc.). 

The way to go in Angular is with `ViewContainerRef` - there are [some NativeScript's module that are using this technique](https://github.com/NativeScript/nativescript-angular/search?q=ViewContainerRef&unscoped_q=ViewContainerRef) so you can use the code as reference.
