### ISSUE TITLE
Mention creation of Java arrays in 'JavaScript to Java' article

### ISSUE THREAD

**Issue by Tyg-g** [NativeScript/docs-v7#1194]
### Make sure to check the existing issues in this repository 
Yes

### Please, tell us what's the problem?
[ ] A typo
[ ] Wrong documentation
[X] Improvement of existing article
[ ] Missing documentation
[ ] New article needed

### Please, tell us more details

The ['Java to JavaScript: Array'](https://docs.nativescript.org/runtimes/android/marshalling/java-to-js#array) article mentions creating Java arrays in JavaScript. This was useful for me for passing arguments when the conversion is not done automatically, calling a Java function from JavaScript (especially the `Array.create("int", 10)` and `Array.create("[I", 10)` ).

In this context this is more related to the ['JavaScript to Java'](https://docs.nativescript.org/runtimes/android/marshalling/js-to-java) article. For me it was really hard to find it in the current place, took much time. I propose to copy this part to 'JavaScript to Java' or mention this possibility there with a link.

**Comment by NickIliev** [comment]
@Tyg-g there is [an article section](https://docs.nativescript.org/core-concepts/android-runtime/marshalling/js-to-java#array)  in the JavaScript to Java article

**Comment by Tyg-g** [comment]
@NickIliev  yes, ant it _doesn't_ mention the Array.create method! This was misleading me in that I thought that that one was the only way to create/pass arrays.

**Comment by Tyg-g** [comment]
I propose to mention Array.create in the _JavaScript to Java: Array_ section.

**Comment by NickIliev** [comment]
@Tyg-g I've added extended examples for worki9ng with Array of primitive types and two-dimensional arrays and the examples are also demonstrating `Array.create` method [via this PR](https://github.com/NativeScript/docs/pull/1239/files).
