### ISSUE TITLE
Mention about calling variadic functions

### ISSUE THREAD

**Issue by Tyg-g** [NativeScript/docs-v7#1197]
### Make sure to check the existing issues in this repository 
Yes
### Please, tell us what's the problem?
[ ] A typo
[ ] Wrong documentation
[X] Improvement of existing article
[ ] Missing documentation
[ ] New article needed

### Please, tell us more details
Describe how to call different variadic functions in [JavaScript to Java](https://docs.nativescript.org/runtimes/android/marshalling/js-to-java) article for Android, and also for iOS if it is implemented.

**Comment by NickIliev** [comment]
iOS [doesn't support variadic methods](https://docs.nativescript.org/core-concepts/ios-runtime/Limitations)

**Comment by NickIliev** [comment]
Article improved for Android - Resolved via [https://github.com/NativeScript/docs/pull/1239](https://github.com/NativeScript/docs/pull/1239)
