### ISSUE TITLE
PWA AS DOC 

### ISSUE THREAD

**Issue by ghost** [NativeScript/docs-v7#1215]
I think that to get a progressive Web app as doc is gonna be great for us who have Internet occassionnelly

**Comment by etabakov** [comment]
Hey @Fabiyo-90, I'm not sure I understand your request. If you have sporadic access to internet - our advice is to setup the documentation locally as described in the [README](https://github.com/nativescript/docs);. This will allow you to run the whole documentation locally. Is this what you are looking for?

**Comment by ghost** [comment]
I am a frensh man so my english is not good, if the community can explain how install the doc locally via video tutorial on YouTube is gonna be great

**Comment by etabakov** [comment]
You just need to follow these simple steps: https://github.com/NativeScript/docs#local-setup: 
1. Install Docker
1. Clone all required repositories 
1. Run `docker build ...` and `docker run ...` commands as specified in the README.
