### ISSUE TITLE
Documentation: Add an article that lists all officialy supported samples

### ISSUE THREAD

**Issue by enchev** [NativeScript/docs-v7#122]
_From @valentinstoychev on June 24, 2015 5:58_

Link to github repos and provide a summary of the features they are showing inside the code.

Update the getting started article to point to this page with the samples so that this become a natural next step fro everyone learning NativeScript.

_Copied from original issue: NativeScript/NativeScript#354_

**Comment by tjvantoll** [comment]
We have this at http://docs.nativescript.org/start/samples.html, but we recommend pointing people at https://www.nativescript.org/app-samples-with-code.
