### ISSUE TITLE
Documentation: add an article how to run unit tests and how to write a functional test.

### ISSUE THREAD

**Issue by enchev** [NativeScript/docs-v7#123]
_From @valentinstoychev on June 9, 2015 5:55_

Often is the question how to setup testing environment and it will be good if we have articles about this in the docs.

_Copied from original issue: NativeScript/NativeScript#298_

**Comment by enchev** [comment]
_From @emiloberg on June 9, 2015 10:37_

@ligaz [just wrote](https://twitter.com/ligaz/status/607451819359354881):

> We are currently prototyping some ideas for unit testing. We will post a GitHub issue with our findings in the coming weeks.

**Comment by enchev** [comment]
_From @ligaz on June 10, 2015 12:36_

I don't want to spoil the surprise so I will just gave this hint: https://github.com/NativeScript/karma-nativescript-launcher/blob/master/concept.md :smiley_cat:

**Comment by AntonioCuevaUrraco** [comment]
How is the karma integration/article going? I would like to add some tests to our app

**Comment by fritzvd** [comment]
I just wrote this in lieu of something better:
http://blog.technokrat.nl/2015/10/13/writing-tests-for-nativescript-apps/

Should I add a doc article on that?

**Comment by ligaz** [comment]
You can check the unit testing article here #162. If you want to play with the bits before we release them you can checkout the [`sd/karma`](https://github.com/NativeScript/nativescript-cli/tree/sd/karma) branch in NativeScript CLI.

**Comment by alexnewgen** [comment]
I still get the data/observable module not found errors when I try to use proxyquire. Does anyone have a workaround? Thanks in advance.

**Comment by tjvantoll** [comment]
The unit testing article is now live at http://docs.nativescript.org/core-concepts/testing.html. If anyone has any suggestions on how we can improve our unit testing documentation please create a new issue. Thanks!
