### ISSUE TITLE
Spelling on NativeScript landing page. No Code

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/docs-v7#1267]
_From @endepointe on July 19, 2018 17:58_

Used 'V' instead of 'B' in "hybrid WebView-vased) apps"

Snapshot given

![ns](https://user-images.githubusercontent.com/30739491/42961021-67e39198-8b42-11e8-8262-f3ebcd294370.GIF)

Easy fix but it is nice to see correct spelling.

_Copied from original issue: NativeScript/NativeScript#6094_

**Comment by etabakov** [comment]
Fixed. Thanks for letting us know @endepointe.
