### ISSUE TITLE
fetch.fetch http return network request failed. Need more info on error

### ISSUE THREAD

**Issue by atul221282** [NativeScript/docs-v7#127]
This request work fine under ionic mobile app using angular js http but never works in nativescript. 

```
            var url = "http://localhost/MySpecial.Authorisation.API/api/audience/SetClient";
    debugger;
    fetch.fetch(url, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ UserName: "SuperUser", Password: "SuperUser"  })
        }).then(function (r) { 
            return r.json(); 
        })
        .then(function (r) {
            console.log(result);
        }, function (e) {
            console.log("Error occurred " + e);
        });
```

**Comment by ligaz** [comment]
Hey @atul221282,

When accessing `localhost` from your device it actually resolve to the device itself. Can you try changing this to the domain/machine name or IP address of your computer?

**Comment by atul221282** [comment]
I have tried it already These are my latest attempts

fetch.fetch("http://192.168.0.5/MySpecial.Authorisation.API/api/audience/GetClient", {
            method: "GET",
            headers: { 
                "content-type":"application/json"
            },
            }).then(function (r) { 
                alert(r);
                return r.json(); 
            })
            .then(function (r) {
                alert(r);
            }, function (e) {
                alert(e);
            });

```
    http.getString("http://192.168.0.5/MySpecial.Authorisation.API/api/audience/GetClient").then(function (r) {
        alert(r);
    }, function (e) {
        alert(e);
    });
```

in first it just fails and give Network request failed error in second it gives me java.net.ConnectionException Connection timed out error...and it take a lot of time to give that error. But I tried same call in ionic sample it works like bang in milli seconds i get my result and the only reason why I am running in Ionic is because i wan't to make sure that my web api allow all request from all domains.

**Comment by atul221282** [comment]
Another Update - it works in emulator following is my code and I don't know what gets changed between emulator and mobile android HTC.

fetch.fetch("http://192.168.0.5/MySpecial.Authorisation.API/api/audience/GetClient", {
            method: "GET",
            headers: { 
                "content-type":"application/json"
            },
            }).then(function (r) { 
                //alert(r);
                return r.json(); 
            })
            .then(function (r) {
                alert(r);
            }, function (e) {
                alert(e);
            });

**Comment by ligaz** [comment]
It looks like your device is not on the same network as your computer. It works in the emulator because it is run from your machine.

In order to make this work please make sure you can open the specified URL from a web browser on your mobile device.

**Comment by atul221282** [comment]
We can close this issue as it was a problem with my system firewall. 
Thanks once again for ur help and prompt reply.
