### ISSUE TITLE
Documentation Tutorial Update

### ISSUE THREAD

**Issue by SGissubel** [NativeScript/docs-v7#1274]
The documentation & tutorial are amazing... but newer methods for using asynchronous fetches, subscriptions, observables -- with  Angular 6 especially -- has a bunch of updates in certain syntax. 

[ ] A typo
[ ] Wrong documentation
[ x ] Improvement of existing article
[ ] Missing documentation
[ maybe? ] New article needed

For example, the following with no longer work as is (found in documents tutorial): 

```
login(user: User) {
  return this.http.post(
    Config.apiUrl + "user/" + Config.appKey + "/login",
    JSON.stringify({
      username: user.email,
      password: user.password
    }),
    { headers: this.getCommonHeaders() }
  )
  .map(response => response.json())
  .do(data => {
    Config.token = data._kmd.authtoken
  })
  .catch(this.handleErrors);
}
```

The previous will cause errors (ei: 'map does not exist on type...' or '...map is not a function')

The Aync "pipe" is now almost hard not to use and should not fail due to any syntax issues -- (after running through the tutorial -- this DOES work for me - runs in simulators)

Newer methods look more like the following - will not create errors: 

```
  login(user: User) {
	  return this.http.post(
	    Config.apiUrl + "user/" + Config.appKey + "/login",
	    JSON.stringify({
	      username: user.email,
	      password: user.password
	    }),
	    { headers: this.getCommonHeaders() }
	  ).pipe(
	  	map(response => response.json()),
	  	tap(data => {
	    	Config.token = data._kmd.authtoken
		  }),
		  catchError(this.handleErrors)
	  )
	  
	}
```

**Comment by etabakov** [comment]
Thanks for bringing this up @SGissubel! If you have a suggestion on how to improve the tutorial to acknowledge the Angular 6 - you are most welcome to open a PR in this repository.

**Comment by tjvantoll** [comment]
Thanks @SGissubel! I moved this issue over to https://github.com/NativeScript/playground-tutorials/issues/6 as we’re storing our tutorial content there now.

We’ll make sure we get things switched over before Angular removes the old APIs, but as @etabakov said PRs are welcome 🙂
