### ISSUE TITLE
When using the dark color scheme, make sure that you are using dark parent themes on Android

### ISSUE THREAD

**Issue by yavulan** [NativeScript/docs-v7#1281]
### Please, tell us what's the problem?
[ ] A typo
[ ] Wrong documentation
[x] Improvement of existing article
[ ] Missing documentation
[ ] New article needed

### Please, tell us more details

https://docs.nativescript.org/angular/ui/theme#color-schemes should clarify something like this:

“When using the dark color scheme, make sure that you are using dark parent themes on Android:

In `app/App_Resources/Android/src/main/res/values/styles.xml` and in `app/App_Resources/Android/src/main/res/values-v21/styles.xml` remove `“Light.”` from parent namespaces, e.g. `Theme.AppCompat.Light.NoActionBar` becomes `Theme.AppCompat.NoActionBar`  etc.”

**Comment by etabakov** [comment]
Thanks for the suggestion @yavulan! Feel free to open a PR that addresses this tip.
