### ISSUE TITLE
Nativescript Sidekick cloud build error Android

### ISSUE THREAD

**Issue by dpdragnev** [NativeScript/docs-v7#1289]
Please see https://stackoverflow.com/questions/51618664/nativescript-sidekick-cloud-build-error-android for more details.

In a nutshell, today my app started behaving very strange.  When I try to add a platform I get the **Unhandled rejection Error: Integrity check failed:** error.
If I try to build using Sidekick I get the same error.

Also, if I try to build for iOS on Windows using Sidekick, I get stuck on **Installing tns-ios**.  I tried that on 2 different machines.

Thank you.

**Comment by ggarabedian** [comment]
Hello @dpdragnev, 

can you please tell me what versions of **NodeJS** and **NPM** you have installed on your machine? We cannot reproduce this issue when testing locally with a sample app and we hope the requested information can help us to investigate this further.

**Comment by dpdragnev** [comment]
Hello @ggarabedian 

Node: 8.11.1
NPM: 5.6.0

As I mentioned, I can build locally through the tns build android command, so I don't think it is the tooling.  I only get the error if I try to do a cloud build via the Sidekick

Thanks.

**Comment by dpdragnev** [comment]
I could not figure out the reason for this, but after removing the node_modules, hooks, removing all platforms and adding them back on, suddenly everything works again.
