### ISSUE TITLE
JDK installation instructions on NativeScript Getting Started Guide. 

### ISSUE THREAD

**Issue by mbcrump** [NativeScript/docs-v7#129]
http://docs.nativescript.org/setup/ab-setup/ab-vse-setup.html

Instruction 5.2 should let the user know they can use PATH to see if it added the JDK successfully.

In the instructions, it just says "If not present.."

Also, the path to JDK will not appear in the same command prompt where they installed it. They will have to close the prompt and open it back up to check if the path was added successfully.

**Comment by tjvantoll** [comment]
This has since been addressed. Oh, and hi @mbcrump 👋 😄
