### ISSUE TITLE
Expand docs for custom fonts

### ISSUE THREAD

**Issue by lscown** [NativeScript/docs-v7#132]
i.e. https://docs.nativescript.org/styling#custom-fonts

The docs are very vague on how you include custom fonts and apply them.

**Comment by tjvantoll** [comment]
Wow, it’s been awhile. I completely agree here. Adding the up-for-grabs label.

**Comment by NickIliev** [comment]
I have updated the section - let me know if you have any comments on this PR 
https://github.com/NativeScript/docs/pull/456
