### ISSUE TITLE
Possible regression: broken link to Layouts pages

### ISSUE THREAD

**Issue by BrendanBerkley** [NativeScript/docs-v7#1328]
### Please, tell us what's the problem?
[ ] A typo
[ ] Wrong documentation
[ ] Improvement of existing article
[x] Missing documentation
[ ] New article needed

### Please, tell us more details
This might overlap with #1325.

Did #1314 cause a regression? If I go to https://docs.nativescript.org/ then try to click either "Layouts" link, they don't work. Same with Google/Bing search results.

Someone on Slack [pointed out](https://nativescriptcommunity.slack.com/archives/C0L9EEURY/p1535011670000100?thread_ts=1534963113.000100&cid=C0L9EEURY) that the link is supposed to go to [here](https://docs.nativescript.org/angular/ui/ng-ui-widgets/layouts), which worked.

**Comment by etabakov** [comment]
Thanks for letting us know! It should be fixed now.

**Comment by BrendanBerkley** [comment]
Thank you for your work!
