### ISSUE TITLE
Broken link in CORE CONCEPTS/Android Runtime/Metadata/Accessing APIs

### ISSUE THREAD

**Issue by shiv19** [NativeScript/docs-v7#1332]
In the following link, the link that says "the dedicated article" is broken.
https://docs.nativescript.org/core-concepts/android-runtime/metadata/accessing-packages#extend-classes-and-interfaces

**Comment by etabakov** [comment]
Thanks @shiv19! The link is fixed and will be deployed with the next update of the documentation.
