### ISSUE TITLE
Add article that explains how to most effectively report a problem in the framework

### ISSUE THREAD

**Issue by etabakov** [NativeScript/docs-v7#1339]
### Please, tell us what's the problem?
[ ] A typo
[ ] Wrong documentation
[ ] Improvement of existing article
[ ] Missing documentation
[X] New article needed

### Please, tell us more details
A new article that explain what steps a user can take in order to provide most information when reporting a bug is needed. It will be referred in all our issue templates, so that we don't have to duplicate this knowledge. The [Get Support](https://docs.nativescript.org/get-support) section can be an appropriate place for this information. 

The article should explain all tip&tricks about enabling and retrieving logs for the different components of the framework, like __enableVerboseLogging() in Android, `adb logcat`, etc.

**Comment by mbektchiev** [comment]
A new section in the `Get Support` page has been added.
