### ISSUE TITLE
Document XAML-like sizing system

### ISSUE THREAD

**Issue by emiloberg** [NativeScript/docs-v7#137]
As described [in this issue](https://github.com/NativeScript/NativeScript/issues/412#issuecomment-138682119), the sizing of e.g. a a GridLayout's cols/rows can be set by a XAML-like sizing system, like `"*, 3*, *"`. I haven't found this documented anyway and it's really a hidden gem as we quite often want to have non-pixel-sizing.

**Comment by hshristov** [comment]
Hi @emiloberg,

Is this good enough?
https://docs.nativescript.org/ApiReference/ui/layouts/grid-layout/HOW-TO.html

**Comment by emiloberg** [comment]
I'd like to see an XML-example of how to use eg `*, 3*, *`.

Do I understand correctly if I say:
A value which is just a number, e.g. `80` is a fixed pixel value, whereas a value with a star, e.g. `2*` or just `*` is treated as a fraction (which can be translated to a percentage), e.g.

```
<GridLayout columns="*, 3*, 2*" >
```

means: Make 3 columns, width of first should be 1 unit, the second should be 3 units and the last 2 units. If I were to have a 1200 pixel wide screen that would translate to column 1 being 200 pixels, column 2 being 600 pixels and column 3 being 400 pixels. 

And that `*` and `1*` is the same thing in this case?

Also some clarification on things like this:

```
<GridLayout columns="80, *, auto">
```

This means, if I understand correctly: Make 3 columns, first one is 80 pixels, star means fill left and auto means take rest of the space. But I can't really visualize the end result of this. If I have a screen, with the width 1000 pixels, what would the 3 column widths be? 80, 460 and 460?

Overall, some more examples would help.

**Comment by tjvantoll** [comment]
> I'd like to see an XML-example of how to use eg _, 3_, *.

:+1: I didn't even realize this syntax existed until recently.

**Comment by jlooper** [comment]
@tjvantoll I learned it from you... Srsly we need to get this documented...

@emiloberg an example is in the Groceries app:

https://github.com/NativeScript/sample-Groceries/blob/master/app/views/list/list.xml

``` xml
<GridLayout rows="auto, *" columns="2*, *">
        <TextField id="grocery" text="{{ grocery }}" hint="Enter a grocery item"
            row="0" col="0" />
        <Button text="Add" tap="add"
            row="0" col="1" />

        <ListView items="{{ groceryList }}" id="groceryList"
            row="1" colSpan="2">
            <ListView.itemTemplate>
                <GridLayout columns="*, auto">
                    <Label text="{{ name }}" />
                    <Image src="res://ic_menu_delete" ios:visibility="collapsed" tap="delete"
                        col="1" />
                </GridLayout>
            </ListView.itemTemplate>
        </ListView>

        <ActivityIndicator busy="{{ isLoading }}"
            rowSpan="2" colSpan="2" />
    </GridLayout>
```

**Comment by hshristov** [comment]
I guess it is not clear enough :)

``` code
columns="*, 3*, 2*"
```

this means there will be 3 columns. columns a separated by comma (we will allow separation with space soon). Star without a number is equal to 1 star. In CSS Grid Specification our stars are named 'fr' - fraction of the free space.

If you have 1200px width the grid will count the total star columns count which is 6 in this case. So 1 star is 1200/6 = 200px. Then we multiply star count by 200 for every column which results to - 200, 600, 400.

```
<GridLayout columns="80, *, auto">
```

means 3 columns: 80 pixels, star column and auto column.
Auto columns are auto sized - the column width will be the width of the widest element in this column.
After fixed and auto columns are calculated the remaining width is given to the star columns (if any).

So in the above example it is not clear what will be the width of 2nd and 3rd column.
Same rules applies for rows.

Does this clarifies how GridLayout works?
If so we can put it in the docs.

**Comment by emiloberg** [comment]
Thanks! I'm quite happy with this explanation. 

—

**Comment by tjvantoll** [comment]
This should be covered in http://docs.nativescript.org/ui/layout-containers now. If anyone stumbles upon this and finds the explanations in the docs unclear please open a new issue. Thanks!
