### ISSUE TITLE
Background Execution - Long-Running Tasks

### ISSUE THREAD

**Issue by nikym23** [NativeScript/docs-v7#1371]
### Please, tell us what's the problem?
[ ] A typo
[ ] Wrong documentation
[x] Improvement of existing article
[x] Missing documentation
[ ] New article needed

### Please, tell us more details
I have tried to implement the 'Background Execution - Long-Running Tasks' example available at https://docs.nativescript.org/core-concepts/ios-runtime/how-to/BackgroundExecution.

I implemented the applicationPerformFetchWithCompletionHandler method in CustomAppDelegate and added fetch to
Info.plist.

The problem is that the method is never trigger on the device. When I use 'Simulate Background Fetch' in Xcode, it works fine.

Am I missing something? The application was turned off, the screen locked about 15 hours.

**Comment by NickIliev** [comment]
@nikym23 have you followed all the steps including overwriting the iOS delegate in `main.ts`

```TS
import { CustomAppDelegate } from "./custom-app-delegate";

application.ios.delegate = CustomAppDelegate;
```

**Comment by nikym23** [comment]
yes, I followed all the steps. Maybe something's missing when I publish app to the app store, because it works when I simulate fetch?
