### ISSUE TITLE
Update extending activity docs

### ISSUE THREAD

**Issue by manojdcoder** [NativeScript/docs-v7#1417]
### Please, tell us what's the problem?
Improvement of existing article

### Please, tell us more details
1. Since we have replaced `android.app.Activity` with `android.support.v7.app.AppCompatActivity`, [docs](https://docs.nativescript.org/core-concepts/android-runtime/advanced-topics/extend-application-activity) should reflect the same.
2. [isNativeScriptActivity](https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/ui/frame/activity.android.ts#L13) flag is used to identify whether or not to trigger application level resume event, since it's not documented we loose `resumeEvent` when extending own activity.

**Comment by NickIliev** [comment]
@manojdcoder thank you for reporting this one! The `android.support.v7.app.AppCompatActivity` was already added  but we've missed the new boolean flag in the examples. Added via the PRs described below.

Resolved via [https://github.com/NativeScript/docs/pull/1420](https://github.com/NativeScript/docs/pull/1420) and via [https://github.com/NativeScript/nativescript-dev-webpack/pull/705](https://github.com/NativeScript/nativescript-dev-webpack/pull/705)
