### ISSUE TITLE
Missing explanation

### ISSUE THREAD

**Issue by muuvmuuv** [NativeScript/docs-v7#1435]
### Please, tell us what's the problem?
[ ] A typo
[ ] Wrong documentation
[x] Improvement of existing article
[x] Missing documentation
[ ] New article needed

### Please, tell us more details

Related: https://github.com/NativeScript/docs/blob/master/docs//ui/animation.md

I don't really know how to get `view` to animate elements. This is not clear enough, IMHO. 
What I have tried in Angular was `this.page.getViewById` to get the view of an element, but I get this error from TS: `[ts] Property 'animate' does not exist on type 'ViewBase'. [2339]`

**Comment by ibnYusrat** [comment]
Any luck with this? I am also getting the same problem.

**Comment by ibnYusrat** [comment]
> I don't really know how to get `view` to animate elements. This is not clear enough, IMHO.
> What I have tried in Angular was `this.page.getViewById` to get the view of an element, but I get this error from TS: `[ts] Property 'animate' does not exist on type 'ViewBase'. [2339]`

Alright. So you basically have to specify type to be 'View' for the variable or constant that gets the value of getViewById() and then everything works as expected. 

so something like
```
let myInputField = this.page.getViewById('some-view-id');
myInputField.animate({
...
});

```

could produce an error saying animate does not exist on ViewBase but if you do

`let myInputField: View = this.page.getViewById('some-view-id');`

then this error is gone.
