### ISSUE TITLE
Local notification code example not working

### ISSUE THREAD

**Issue by RaisinBread42** [NativeScript/docs-v7#1449]
### Please, tell us what's the problem?
[ ] A typo
[ ] Wrong documentation
[x] Improvement of existing article
[ ] Missing documentation
[ ] New article needed

### Please, tell us more details

Following the documentation here: https://docs.nativescript.org/core-concepts/ios-runtime/how-to/BackgroundExecution#long-running-tasks 

I get an error on re undefined variable on the line with:
```
          LocalNotification.schedule([{
            title: 'Title of the notification'
          }]).then( ...
```
changed `LocalNotification` to match the import (`LocalNotifications`), then received the error 
`    TS2339: Property 'schedule' does not exist on type 'typeof import("/path-to-projects/project-root/node_modules/nativescript-local-notifications...'.`

Still quite new to nativescript so don't know the possible mistake I am making or the fix that is needed?

**Comment by jeremie1112** [comment]
> ### Please, tell us what's the problem?
> [ ] A typo
> [ ] Wrong documentation
> [x] Improvement of existing article
> [ ] Missing documentation
> [ ] New article needed
> 
> ### Please, tell us more details
> Following the documentation here: https://docs.nativescript.org/core-concepts/ios-runtime/how-to/BackgroundExecution#long-running-tasks
> 
> I get an error on re undefined variable on the line with:
> 
> ```
>           LocalNotification.schedule([{
>             title: 'Title of the notification'
>           }]).then( ...
> ```
> changed `LocalNotification` to match the import (`LocalNotifications`), then received the error
> ` TS2339: Property 'schedule' does not exist on type 'typeof import("/path-to-projects/project-root/node_modules/nativescript-local-notifications...'.`
> 
> Still quite new to nativescript so don't know the possible mistake I am making or the fix that is needed?

Why do you want to change `LocalNotification` to match the import (`LocalNotifications`) ? This "LocalNotification.schedule" is one term so (LocalNotifications).schedule wont work.

**Comment by NickIliev** [comment]
@RaisinBread42 check [the documentation of nativescript-local-notification.](https://github.com/EddyVerbruggen/nativescript-local-notifications#setup-since-plugin-version-300) The import variable used should be the one imported

e.g. 
```TypeScript
import * as LocalNotifications from "nativescript-local-notifications";

// then
 
LocalNotifications.schedule({
})
```

Or in TypeScript
```TypeScript
import { schedule } from "nativescript-local-notifications";

// then

schedule({
})
```

BUt in order, for all that to work you should have the plugin ([nativescript-local-notifications](https://github.com/EddyVerbruggen/nativescript-local-notifications#setup-since-plugin-version-300)) installed and set as described in the documentation
