### ISSUE TITLE
Can't scroll "In this Article" column

### ISSUE THREAD

**Issue by mrmowji** [NativeScript/docs-v7#1455]
### Please, tell us what's the problem?
[ ] A typo
[ ] Wrong documentation
[x] Improvement of existing article
[ ] Missing documentation
[ ] New article needed

### Please, tell us more details
I can't scroll the right column ("In This Article") separately. I have to scroll the whole page to the end to see if there is more links (headings), which doesn't benefit me at that point. Same is true for the left column (Topics). For example, open [The Basics page](https://docs.nativescript.org/ui/basics).

**Comment by bdlb77** [comment]
I think the issue is that the onscroll is added the middle column.. which is actually the parent div to the right and left columns. I'll open a PR to see if I can fix it if that's okay... (I'm new to Open source soo if I'm doing anything wrong just let me know :)  )

**Comment by etabakov** [comment]
@bdlb77 we are here to help you :) go ahead!
