### ISSUE TITLE
Animation page is messed up because of a typo

### ISSUE THREAD

**Issue by EddyVerbruggen** [NativeScript/docs-v7#1466]
### Please, tell us what's the problem?
[x] A typo
[ ] Wrong documentation
[ ] Improvement of existing article
[ ] Missing documentation
[ ] New article needed

### Please, tell us more details
See https://github.com/NativeScript/docs/blob/b6dd7610096d2401652fbe05ba4cf4a1835fab2a/docs/ui/animation-examples.md#rotation-using-originx-and-originy

- The image is missing
- There's "git bran"
- And a typo: "viww"

I would have sent a PR but I'm not sure which image should be linked, and what the original author intended to do with "git bran".

**Comment by etabakov** [comment]
The typo and the "git bran" should be fixed in [this PR](https://github.com/NativeScript/docs/pull/1478). Unfortunately, I don't have an idea what image should be used either. @NickIliev @tsonevn, any thoughts?

**Comment by tsonevn** [comment]
@etabakov We do not have GIF for this animation. I will make one and will add it in the article.

**Comment by etabakov** [comment]
Awesome, thanks @tsonevn!
