### ISSUE TITLE
Not sure how to offer an edit for code snippets

### ISSUE THREAD

**Issue by x-yggdrasil-x** [NativeScript/docs-v7#1490]
### Please, tell us what's the problem?
[ ] A typo
[ ] Wrong documentation
[x] Improvement of existing article
[ ] Missing documentation
[ ] New article needed

### Please, tell us more details
I'd like to help contribute or offer suggested edits to the wiki, specifically code snippets that look like:
```
{%snippet xxx-yyy-zzz%}
```

But I do not know where these code snippets are stored. Can someone point me in the direction of where to edit these snippets?

Thanks!

**Comment by etabakov** [comment]
Snippets are extracted from real NativeScript applications that reside on several places: [NativeScript/NativeScript](https://github.com/nativescript/nativescript), [NativeScript/nativescript-sdk-examples-ng](https://github.com/NativeScript/nativescript-sdk-examples-ng) or [NativeScript/nativescript-sdk-examples-js](https://github.com/NativeScript/nativescript-sdk-examples-js). Probably, the fastest way to find where exactly the snippet is to search in whole [NativeScript](https://github.com/nativescript) organisation. Usually, the IDs of the snippets unique enough to give you the location right away.
