### ISSUE TITLE
Document creating release builds and/or submitting to app stores

### ISSUE THREAD

**Issue by tjvantoll** [NativeScript/docs-v7#150]
Currently there is no documentation on how to create a release build, or how to submit an app to the app stores. IMO we should have a page that shows the basic process, starting with using the `--release` flag. For things out of our control (Application Loader, iTunes Connect, Google Play Developer Console, etc), we could at least give people links to point them in the right direction.

**Comment by tjvantoll** [comment]
It would also be good to have documentation on the various `--key-store-*` options here. I had no idea how to use them.

**Comment by emiloberg** [comment]
Documenting how to deal with all the images (Icons/Splash screen/Start screens/etc) should be a part of this. Also see this issue https://github.com/NativeScript/nativescript-cli/issues/888

**Comment by emiloberg** [comment]
More ideas:

Should describe
- describe both ways of uploading an app to iTunes Connect; Application Loader and with Xcode (does Application Loader do the same package verification as XCode does?)
- describe how to create JKS files for signing the Android app
- describe (or at least link to a _really good_ resource) how to set up iOS Certificate and Provisioning Profiles (most probably easiest by creating the certs on Apple's site and then importing them from within Xcode (Preferences > Accounts))

Not doc, but release related:
- As the Android version needs a new versionCode for every new build; When adding the `--release` flag, it'd be nice if the CLI tool prompted an input to change `versionCode` and `versionName`. Added a separate issue: https://github.com/NativeScript/nativescript-cli/issues/1118

**Comment by PanayotCankov** [comment]
Hi,

[I have been working on article for iOS submission. You can review it while it is in development, feedback about the content will be appreciated, while typos and style will go through internal review.](https://github.com/NativeScript/docs/pull/242/files).

The CLI now produces IPAs signed with development certificates and provisioning profiles so the _Application Loader_ fails to submit them.

**Comment by tjvantoll** [comment]
These articles now exist 🎉
