### ISSUE TITLE
Broken Link on Angular Full Setup tutorial.

### ISSUE THREAD

**Issue by cowboyd** [NativeScript/docs-v7#1528]
### Please, tell us what's the problem?
[ ] A typo
[x] Wrong documentation
[x] Improvement of existing article
[ ] Missing documentation
[ ] New article needed

### Please, tell us more details
Looks like the link to the next steps of CLI basics is broken. It's got two `/angular` elements in the path, when there ought to be one. https://docs.nativescript.org/angular/angular/start/cli-basics
Describe in more details

**Comment by etabakov** [comment]
Hey, thanks for reaching out. Can you give us the URL of the page, where the broken link can be found? Also, at the right sidebar that is an "Improve this article" link, which can help you to directly edit the page and open PR fixing the problem that you are experiencing.

**Comment by cowboyd** [comment]
It appears at the bottom of this page https://docs.nativescript.org/angular/start/ns-setup-os-x

I'm not sure what the right fix is. Because it being a link, I'd be unsure how to test if I was getting it right.

**Comment by etabakov** [comment]
Fixed
