### ISSUE TITLE
about hub.docker.com

### ISSUE THREAD

**Issue by ghost** [NativeScript/docs-v7#1533]
Then I suggest you publish a docker image in www.hub.docker.com which would greatly facilitate us who wish to have the documentation permanently without being connected to the internet

**Comment by etabakov** [comment]
The image used in the current setup is also public. Can you elaborate on what is preventing you to use the documentation offline?

**Comment by ghost** [comment]
I do not master well docker, it would have been better if the image was on hub.docker.com and make it easier for us to install it, the easier it is to install more people will tend to use it.
I am in Africa, DR Congo, and the speed of the internet connection is really poor hence the preference to install it and use it in localhost.
Or just a hmtl documentation much like the fuelphp framework

**Comment by etabakov** [comment]
I understand the need to have the documentation locally and work with it locally. We are currently using public docker image from hub.docker.com that should be available for everyone to download. 

What I do not understand is - are you having any problem to use it currently. Did you tried to run it locally on your machine and are there any issues? If yes - what are they?

**Comment by ghost** [comment]
I misunderstood, I just ask that the team that designs the documentation can have an official image on www.hub.docker.com as is the case with ubuntu, mysql, postgresql and other product that I have could see but no official image on nativescript documentation. And most of all I have seen none is up to date. They are almost all dating back at least a year.
An official image will be welcome !

I use google translate because I am a french man

**Comment by etabakov** [comment]
There is no official "NativeScript image" because such is not needed. We use an official ruby image from hub.docker.com. Please, test the current setup and let us know if any issues occur.

**Comment by etabakov** [comment]
Closing this issue, due to lack of activity.
