### ISSUE TITLE
 RadListView Item Selection: Missing line of code of the example to update the class of the deselected item.

### ISSUE THREAD

**Issue by gitllermopalafox** [NativeScript/docs-v7#1547]
### Please, tell us what's the problem?
[ ] A typo
[ ] Wrong documentation
[*] Improvement of existing article
[ ] Missing documentation
[ ] New article needed

### Please, tell us more details

Hi, I noticed is missing a line of code of the example to update the class of the deselected item:

https://docs.nativescript.org/vuejs/ns-ui/ListView/selection#example

More details in this example:

https://play.nativescript.org/?template=play-vue&id=CfODKO&v=2

**Comment by etabakov** [comment]
@gitllermopalafox - thanks for spending the time to open this issue and create a Playground with the addressed problem. Feel free to directly open a pull request with the suggested change in the code snippet.
