### ISSUE TITLE
Getting Started Guide - Rob's edits

### ISSUE THREAD

**Issue by jlooper** [NativeScript/docs-v7#156]
1.       Android Setup:
   a.       As a not-so-regular Mac user I was confused by having to alter my PATH all the time (in fact, one time I altered my PATH variable and screwed up what had been done by Gradle for me, odd). Ideally you would put literal commands in there based on the latest versions of all the tools (difficult to keep up to date, but for idiots like me it can be critical!).
   b.      “Android Support Repository” package didn’t exist in my ADK tool list, FYI.
2.       {N} CLI:
   a.       Prior to installing the NS CLI, I had to uninstall node, delete the node_modules directory, and reinstall it. Probably not related to anything prior, but it happened to me.
3.       Detour: How do I know which {N} modules I need in my code? This always has irritated me. I’d love some guidance on when I need to require which modules in KB doc.
4.       [3.2] For me, anything output in console.log doesn’t show up in the terminal, but rather in the system.log in the simulator.
5.       [4.3] “load function empties the list” à should be “empty function” I think
6.       [4.5] Instructions there to “open list.js” and add some xml à should be list.xml
7.       [5] minor spelling issue on “install and use and external…”

**Comment by stephlm2dev** [comment]
In [this page](https://github.com/NativeScript/docs/blob/production/tutorial/chapter-4.md#----exercise-populate-a-list-view-from-a-backend), 

> In this code, groceryList is referencing the grocery list model, and the load() function empties the list, and then calls the view model's load() function to reload the data from the backend.

`load() function empties the list` should be replace by `empty() function empties the list`

**Comment by tjvantoll** [comment]
Thanks @stephlm2dev! Fixed in 72216e77ad50dd4b3ec080f1e3b3e1fd9e46dbe0.

**Comment by tjvantoll** [comment]
I believe all of these things have either been addressed or are no longer relevant now. If these crop up we can open new issues to address them.
