### ISSUE TITLE
Broken link on "RadListView for Angular - Getting started RadListView"

### ISSUE THREAD

**Issue by gbrunow** [NativeScript/docs-v7#1585]
### Please, tell us what's the problem?
[ ] A typo
[ ] Wrong documentation
[x] Improvement of existing article
[ ] Missing documentation
[ ] New article needed

### Please, tell us more details

The article [RadListView for Angular - Getting started RadListView](https://github.com/NativeScript/docs/blob/master/docs//ui/professional-ui-components/ng-ListView/getting-started.md) has a broken link in the section [Adding a RadListView to your template](https://docs.nativescript.org/angular/ui/professional-ui-components/ng-ListView/getting-started#adding-a-radlistview-to-your-template) where it says *"[...] in your app as explained **here**"*.

**Comment by tsonevn** [comment]
fixed with PR https://github.com/NativeScript/docs/pull/1594
