### ISSUE TITLE
Create Development Provisioning profile Read-Me document seems to be outdated.

### ISSUE THREAD

**Issue by ibnYusrat** [NativeScript/docs-v7#1588]
### Make sure to check the existing issues in this repository 
Checked
### Please, tell us what's the problem?
[* ] Wrong documentation

### Please, tell us more details
The document at 
https://docs.nativescript.org/sidekick/user-guide/code-signing/code-signing-for-ios/create-development-provisioning advises us to login to Apple's website and follow certain steps, however those steps aren't visible any more. 

Can someone please check it?

**Comment by theNaut1lus** [comment]
Would love to work on this @etabakov @NickIliev

**Comment by NickIliev** [comment]
@co16353sidak we are welcoming all contributions to NativeScript documentation and framework. [Here are the instructions](https://github.com/NativeScript/docs#contributing) for contributing and for local setup of the documentation through Docker. Please do let me know if you need any assistance

**Comment by NickIliev** [comment]
Closing as the issue seems no to be present anymore (the links are opening the Apple Developer Center as expected)
