### ISSUE TITLE
Add information about naming convention for plugins

### ISSUE THREAD

**Issue by lambourn** [NativeScript/docs-v7#1596]
### Please, tell us what's the problem?
[ ] A typo
[ ] Wrong documentation
[x] Improvement of existing article
[ ] Missing documentation
[ ] New article needed

### Please, tell us more details
I found that {N} plugins that do not follow the "nativescript-..." naming pattern can cause problems. This surfaced after migration to {N} 5.x when our Webpack build stopped working.

Seems as if the code/module resolution of nativescript-dev-webpack assumes that plugin code always lives in `node_modules/nativescript-...` folders. In {N} 4.x that was not required.

When using the Plugin-Seed this issue does not occur as it automcatically prefixes the generated code, meta data and folder structure with "nativescript-" but if someone wants to build a plugin from scratch (as we did) then this will cause issues.

This should be added to the "Create a plugin" section
https://docs.nativescript.org/plugins/plugin-reference#create-a-plugin

**Comment by lambourn** [comment]
fyi - this breaking change is due to this commit in nativescript-dev-webpack (0.19.x version)

https://github.com/NativeScript/nativescript-dev-webpack/commit/0d9ecec3442842434c4b8cd36f628c555fc01488#diff-ca6614fb68d993fc7af1f1d3b9e1722b

Since then, only npm modules under node_modules with "tns", "ns" or "nativescript" in their name will get picked up. This applies to custom plugins as well of course. 

This should be reflected in the docs.

**Comment by NickIliev** [comment]
Resolved via https://github.com/NativeScript/docs/pull/1857
