### ISSUE TITLE
give example for splitting ui libaries

### ISSUE THREAD

**Issue by westlakem** [NativeScript/docs-v7#1603]
### Please, tell us what's the problem?
[ ] A typo
[ ] Wrong documentation
[ ] Improvement of existing article
[X] Missing documentation
[ ] New article needed

### Please, tell us more details
In your Angular code splitting document, you show how you can split HTTP clients using different modules.  You also state that you can split UI components in the same way, but I don't understand how.

Take `nativescript-cardview` and `material card` for example.  They don't use the same selectors, and the cardview requires you to add
```
import { registerElement } from 'nativescript-angular/element-registry';
import { CardView } from 'nativescript-cardview';
registerElement('CardView', () => CardView);
```
to your component in order to use it

**Comment by NickIliev** [comment]
@westlakem I am not sure that I understand your question - can you clarify what do you mean by "splitting UI libraries" and by "material card" (is that a plugin)?

**Comment by westlakem** [comment]
@NickIliev Yes, "material card" is a plugin.

What I want to do, is create 2 different modules (one that includes materialCard plugin for TNS, and one that includes AngularMaterial for web), and have them both be called `Card` so I can re-use the component.ts file in my app.

**Comment by NickIliev** [comment]
https://docs.nativescript.org/plugins/angular-plugin
