### ISSUE TITLE
Bug: Feedback Bar at the end has no margins

### ISSUE THREAD

**Issue by theNaut1lus** [NativeScript/docs-v7#1622]
### Make sure to check the existing issues in this repository 
Checked.

### Please, tell us what's the problem?
[ ] A typo
[ ] Wrong documentation
[ ] Improvement of existing article
[ ] Missing documentation
[ ] New article needed
None of the above, more of an error in the UI of the particular section of the docs on the website.

### Please, tell us more details
The feedback bar at the end of every article seems to have some design faults, the two content elements seem to have been aligned to the corners leaving vast open spaces in between and also at the edges the content seems to miss a lot of margin space and hence the text seems to crash into the borders.
I have enclosed a screenshot of the same.
<img width="1270" alt="Screenshot 2019-04-09 at 4 44 19 PM" src="https://user-images.githubusercontent.com/35738138/55821473-3b617c80-5b1b-11e9-8eb9-e3beafef24c4.png">

P.S: I tried a lot to find the most suitable place to report this issue, I felt that the main repo was not suitable with this report as this issue seems to be with the website and not with the framework itself.
I would also love to work on this issue, and wold love to send a PR as my first contribution to NativeScript. 🥇

**Comment by etabakov** [comment]
Hey co16353sidak! Thanks for reporting this issue. We will be happy to consider your Pull Request - let me know if we can help you with something along the way.

**Comment by theNaut1lus** [comment]
@etabakov Will implement a change and send up a PR

**Comment by theNaut1lus** [comment]
@etabakov 

On further in-depth inspection I find that while the feedback banner does show the above fault in safari it seems to be alright in Firefox.
checking the below screenshots you will be able to understand the same.

**Firefox**
<img width="1392" alt="Screenshot 2019-05-06 at 11 50 31 PM" src="https://user-images.githubusercontent.com/35738138/57245979-c02bb180-7059-11e9-86e8-6114cd52e6c2.png">


**Safari**
<img width="1392" alt="Screenshot 2019-05-06 at 11 47 34 PM" src="https://user-images.githubusercontent.com/35738138/57245795-5a3f2a00-7059-11e9-8f70-0efc6a35e169.png">

also for some reason this error only comes in safari at 100% zoom and above, while the issue persists on further zoom, but unzooming the page and the issue seems to disappear.

**unzoomed**
<img width="1392" alt="Screenshot 2019-05-06 at 11 48 40 PM" src="https://user-images.githubusercontent.com/35738138/57245870-7e027000-7059-11e9-8c3d-6d801db4c175.png">

I am a little perplexed as to why this issue is occurring, would love some help from your end in order that I can understand this and possibly make a fix.
Thanks in advance. 😄

**Comment by Zxela** [comment]
Issue appears to be related to the z-index on ns-footer. I've made a PR to address this.
