### ISSUE TITLE
new page wrong path

### ISSUE THREAD

**Issue by blondie63** [NativeScript/docs-v7#1640]
### Please, tell us what's the problem?
[ ] A typo
[x] Wrong documentation
[ ] Improvement of existing article
[ ] Missing documentation
[ ] New article needed

Here: https://docs.nativescript.org/sidekick/user-guide/add-page/add-page
i read: and place them in a newly created folder, which is located in the app folder of your project.

but it's not true, new pages are create on project root ! (Sidekick v 1.16.2-v.2019.3.13.12)

**Comment by NickIliev** [comment]
@blondie63 just tried the described steps and the new page is created as expected - in a folder located at the root level (the folder is named as the page)
