### ISSUE TITLE
Angular RadListView documentation is almost non-existent  

### ISSUE THREAD

**Issue by brandon-sigao** [NativeScript/docs-v7#1661]
### Please, tell us what's the problem?
[ ] A typo
[ ] Wrong documentation
[x ] Improvement of existing article
[ x] Missing documentation
[ ] New article needed

### Please, tell us more details
I'm trying to diagnose massive failures in the rendering of items inside a RadListView and the documentation is unusable.  I have no idea if our implementation is correct.   There are no code snippets showing the proper usage with Angular.  Most of the demo links return 404.  MULTIPLE pages have some sort of statement like "The following snippets demonstrate how _____ is used." followed by a 100% blank area.  Just...nothing.  Its like someone came in and removed examples that used to be there.  

Please give us code examples starting at <RadListView>  and ending at </RadListView>. That's all I want.  Long explanations of every directive and method doesn't help me if I can't see the recommended way to implement them.

**Comment by brandon-sigao** [comment]
To anyone reading this later, all those broken links in the Nativescript documentation are supposed to lead here: https://github.com/telerik/nativescript-ui-samples-angular/tree/master/listview/src/app/examples

Unfortunately the Nativescript documentation does not seem match the examples, so I still don't know the "correct" way to do anything, but at least I have actual code to work with now.

**Comment by NickIliev** [comment]
Resolved via [https://github.com/NativeScript/docs](https://github.com/NativeScript/docs)

The actual example app is located here: https://github.com/NativeScript/nativescript-ui-samples-angular
