### ISSUE TITLE
RadListView "Getting Started" page broken example reference link

### ISSUE THREAD

**Issue by lonerzzz** [NativeScript/docs-v7#1662]
### Please, tell us what's the problem?
[X] A typo
A link to reference code is missing
[ ] Wrong documentation
[ ] Improvement of existing article
[ ] Missing documentation
[ ] New article needed

### Please, tell us more details
The link to the Getting Started Example on this page https://docs.nativescript.org/angular/ui/professional-ui-components/ng-ListView/getting-started is broken so there is no code to reference. I believe the link should be to here:

https://github.com/telerik/nativescript-ui-samples-angular/tree/master/listview/src/app/examples/getting-started

**Comment by NickIliev** [comment]
Thanks for reporting this issue - link fixed via [https://github.com/NativeScript/docs/pull/1697](https://github.com/NativeScript/docs/pull/1697)

The migrated app is located here: https://github.com/NativeScript/nativescript-ui-samples-angular/tree/master/listview/src/app/examples/getting-started
