### ISSUE TITLE
nativescript-dev-sass is not required anymore

### ISSUE THREAD

**Issue by Izrab** [NativeScript/docs-v7#1715]
### Please, tell us what's the problem?
[ ] Improvement of existing article

### Please, tell us more details
In this [article](https://docs.nativescript.org/ui/styling) and this [article](https://docs.nativescript.org/ui/theme) at the bottom, or when it talks about using SASS with NativeScript, it indicates that `nativescript-dev-sass` is needed for writing `scss` or `sass` code with NS apps, but that package is deprecated and no longer required, especially in NS 6.

**Comment by NickIliev** [comment]
Resolved via [https://github.com/NativeScript/docs/pull/1717](https://github.com/NativeScript/docs/pull/1717)
