### ISSUE TITLE
Typo Navigaiton should be Navigation

### ISSUE THREAD

**Issue by kokizzu** [NativeScript/docs-v7#1728]
### Please, tell us what's the problem?
[X] A typo

### Please, tell us more details
lots of typo related for word "Navigaiton", it should be "Navigation"

**Comment by NickIliev** [comment]
@kokizzu where is the typo appearing?

**Comment by kokizzu** [comment]
ui/basics.md
91:In cases where we want to pass a specific context and need more control than the automated `bindingContext`, you could use the `context` property in the `navigatedEntry` object. The navigated page can obtain the passed context via the `navigatedTo` event and the [`navigaitonContext`](/api-reference/classes/_ui_page_.page#navigationcontext) property.

I think there's one more but I can't find it anymore.

**Comment by etabakov** [comment]
Thanks for reporting that @kokizzu. I fixed this specific typo. Since you mentioned that there are "lots of" them and I couldn't find more - you can always suggest a change by opening a PR. Just use the "Improve this Article" button in the right side navigation.
