### ISSUE TITLE
HTTP vs. HTTPS in API URL for backend grocery service

### ISSUE THREAD

**Issue by kvnphllps** [NativeScript/docs-v7#174]
Section 4.0 of the docs refers to the hard-coded API URL that utilizes HTTP:

```
module.exports = {
    apiUrl: "http://api.everlive.com/v1/GWfRtXi1Lwt4jcqK/"
};
```

But the app employs HTTPS in the `config.js` file for both the start and end branches.

If a user thought to change HTTPS of the repo to HTTP - to follow the docs - then you obtain the "Unfortunately we could not find your account" dialog and the following log:

```
2015-11-03 09:35:08.155 sampleGroceries[5287:133749] App Transport Security has blocked a cleartext HTTP (http://) resource load since it is insecure. Temporary exceptions can be configured via your app's Info.plist file.
file:///app/views/login/login.js:26:24: CONSOLE LOG TypeError: Network request failed
```

Perhaps the docs should be updated to reflect HTTPS?

**Comment by tjvantoll** [comment]
Good catch. Thanks!
