### ISSUE TITLE
Unable to proceeed on angular docs

### ISSUE THREAD

**Issue by jcfrane** [NativeScript/docs-v7#1742]
### Make sure to check the existing issues in this repository 
Yes.

### Please, tell us what's the problem?
[ ] A typo
[ ] Wrong documentation
[ ] Improvement of existing article
[*] Missing documentation
[ ] New article needed

### Please, tell us more details
When I navigate to angular documentation then choose a topic in the sidebar it redirects me to pure JS documentation not the one with /angular in the url.

Thanks!

**Comment by etabakov** [comment]
That's addressed in https://github.com/NativeScript/docs/pull/1741
