### ISSUE TITLE
add css-calc and css-variable to styling

### ISSUE THREAD

**Issue by m-abs** [NativeScript/docs-v7#1744]
### Please, tell us what's the problem?
[ ] A typo
[ ] Wrong documentation
[ ] Improvement of existing article
[x] Missing documentation
[ ] New article needed

### Please, tell us more details
Support for css-variables and css-calc expressions were just merged to `NativeScript` and will be available from `6.1.0+`.

Creating this issue to be able to submit a PR

**Comment by NickIliev** [comment]
Resolved via https://github.com/NativeScript/docs/pull/1745
