### ISSUE TITLE
A little typo

### ISSUE THREAD

**Issue by Izrab** [NativeScript/docs-v7#1753]
I think the following should be `node-sass` instead of `node-sas`, right?

![image](https://user-images.githubusercontent.com/22328131/63763683-0d869580-c87a-11e9-8fa2-262cc0c177a8.png)

**Comment by etabakov** [comment]
Hey @Izrab! You can easily open a PR using the "Improve this Article" button with the suggested change. Thanks!

**Comment by Izrab** [comment]
@etabakov , where is `Improve this article `button? I cannot find it, I have very little knowledge in git, pr, and contribution...

**Comment by etabakov** [comment]
![Screenshot 2019-08-29 at 13 35 39](https://user-images.githubusercontent.com/2611328/63933536-1df96480-ca62-11e9-9f13-fce754662c86.png)

**Comment by Izrab** [comment]
OK now i found it, but I don't know how to PR...
