### ISSUE TITLE
Remove the `Lazy Loading` article

### ISSUE THREAD

**Issue by sis0k0** [NativeScript/docs-v7#1765]
The Lazy Loading article in the docs - https://docs.nativescript.org/angular/performance-optimizations/lazy-loading is outdated. It suggests configuring lazily loaded modules by aliasing `~` and providing the path to the module file:
```javascript
{ path: "feature", loadChildren: "~/feature/feature.module#FeatureModule" }
```

This used to be the recommended approach because it was compatible both with the webpack workflow and the legacy workflow. However, NativeScript 6.0 supports only the webpack workflow. Therefore, we don't need to alias `~` anymore.

Also, the Angular docs recommend using dynamic import when configuring lazy 
 loaded modules:
```javascript
{ path: "feature", loadChildren: () => import("./feature/feature.module").then(m => m.FeatureModule)
```

The above configuration works in NativeScript Angular. I suggest we remove the 'Lazy loading' article from the NativeScript docs and redirect the URL to the [Angular docs](https://angular.io/guide/lazy-loading-ngmodules).

**Comment by vakrilov** [comment]
I think most of the content is still relevant. 
IMO it will be better to just rewrite the example with dynamic imports, remove the whole part about `~` and add the link to the angular docs.

**Comment by NickIliev** [comment]
Resolved via https://github.com/NativeScript/docs/pull/1802
