### ISSUE TITLE
TypeError: applicationModule.start is not a function, with --template nativescript-template-tutorial

### ISSUE THREAD

**Issue by mmyself** [NativeScript/docs-v7#1788]
i got this error, while starting the tutorial with "tns create HelloWorld --template nativescript-template-tutorial".
got it with any device. everything is new installed and uptodate.

if i create a HelloWorld without the template, by choosing the HelloWorld option everything works fine.

the require in app.js looks not the same

Maybe you have to update the tutorial or the template.

thx for your wonderful work.

**Comment by manoldonev** [comment]
@mmyself how did you come across the `nativescript-template-tutorial` package? This is the first time I see it and it seems to be targeting a pretty old version of NativeScript.
Generally you can create an up-to-date version of the JavaScript "HelloWorld" template with the following command:
```
tns create HelloWorld --js
```
Also, you can find the rest of the supported NativeScript templates [here](https://market.nativescript.org/?tab=templates&category=all_templates) and [here](https://docs.nativescript.org/app-templates/app-templates)

@tjvantoll Do you remember what was the idea behind https://www.npmjs.com/package/nativescript-template-tutorial -- seems obsolete and I think we should unpublish it?
