### ISSUE TITLE
The "Improve this article" link in the "UI/Components/*" articles is broken

### ISSUE THREAD

**Issue by sis0k0** [NativeScript/docs-v7#1790]
## To reproduce
1. Go to any article in the `UI/Components` section, eg. https://docs.nativescript.org/ui/components/button.
2. Click on the `Improve this article` link in the right navigation bar.
3. The opened page doesn't exist - https://github.com/NativeScript/docs/blob/master/docs//ui/components/button.md.

![Peek 2019-09-27 15-01](https://user-images.githubusercontent.com/7893485/65767961-324f8080-e138-11e9-8639-8a4a18d63451.gif)

**Comment by oorjitchowdhary** [comment]
hi, can i take this up?

**Comment by etabakov** [comment]
Of course, let us know if you need guidance!

**Comment by oorjitchowdhary** [comment]
i believe this uses the following code

https://github.com/NativeScript/docs/blob/88be3f15bd216dfd441be94805693ec2c3712760/build/_includes/improvethis.html#L3

however, i'm unable to find the place where `{{ page.improvethisurl }}` is stored. i'm a newcomer to this repo 😅
