### ISSUE TITLE
Broken links to Professional UI components

### ISSUE THREAD

**Issue by sis0k0** [NativeScript/docs-v7#1792]
Several links with the `slug ns-ui-overview` are leading to 404 pages:
- Professional UI components: https://docs.nativescript.org/core-concepts/navigation#sidedrawer-navigation
- Professional UI components: https://docs.nativescript.org/angular/core-concepts/angular-navigation#sidedrawer-navigation
- Progress UI components: https://docs.nativescript.org/app-templates/app-templates#navigation-drawer

**Comment by wuworkshop** [comment]
Submitted a PR for this one - #1834.
