### ISSUE TITLE
Update the VSCode extension article to {N} 6.0

### ISSUE THREAD

**Issue by sis0k0** [NativeScript/docs-v7#1795]
The VScode extension article still recommends using the `nativescript-dev-typescript` plugin - https://docs.nativescript.org/tooling/visual-studio-code-extension#debug-typescript.
This plugin is not required when building with webpack, which is the only option with {N} 6.0+. Maybe, we should stop recommending the `nativescript-dev-typescript` plugin?

The article also mentions additional steps when configuring the extension to work with webpack - https://docs.nativescript.org/tooling/visual-studio-code-extension#debug-webpack. These steps are no longer required with {N} 6.0. Maybe they should be removed from the article?

@rosen-vladimirov @DimitarTachev @Fatme, what do you think?

**Comment by NickIliev** [comment]
Closing as already resolved
