### ISSUE TITLE
Update the `Transpilers` article to {N} 6.0 and the bundle workflow

### ISSUE THREAD

**Issue by sis0k0** [NativeScript/docs-v7#1796]
The Transpiler article - https://docs.nativescript.org/tooling/transpilers, recommends using the `nativescript-dev-typescript` and `nativescript-dev-babel` plugins. However, {N} 6.0 builds with webpack by default and we should recommend using webpack plugins/loaders instead of the above plugins.

@rosen-vladimirov, @DimitarTachev, @Fatme, what do you think?

**Comment by NickIliev** [comment]
Resolved via https://github.com/NativeScript/docs/pull/1856
