### ISSUE TITLE
The link to the external "How NativeScript works" article is broken

### ISSUE THREAD

**Issue by sis0k0** [NativeScript/docs-v7#1807]
The link `How NativeScript Works article on developer.telerik.com` in the [Technical Overview](https://docs.nativescript.org/core-concepts/technical-overview) article leads to [nativescript.org/blog](nativescript.org/blog).
![Screenshot from 2019-10-03 16-11-13](https://user-images.githubusercontent.com/7893485/66129747-30366780-e5f9-11e9-9912-280d34f1764d.png)

**Comment by wuworkshop** [comment]
Submitted a PR for this one - #1833.
