### ISSUE TITLE
Nativescript-ui API Reference leads to 404

### ISSUE THREAD

**Issue by Eonfuzz** [NativeScript/docs-v7#1808]
The API Reference on [Nativescript-ui-bar documentation](https://docs.nativescript.org/angular/ui/ng-components/ng-Chart/Series/bar) leads to several pages that 404. 

I have not confirmed that this is happening to other API references, ie:
https://docs.nativescript.org/angular/ns-ui-api-reference/classes/radcartesianchart

**Comment by NickIliev** [comment]
Resolved via [https://github.com/NativeScript/docs/pull/1849](https://github.com/NativeScript/docs/pull/1849) - the updated documentation is now live.
