### ISSUE TITLE
Application lifecycle events and zones

### ISSUE THREAD

**Issue by dmytro-gokun** [NativeScript/docs-v7#1845]
### Make sure to check the existing issues in this repository 
Check

### Please, tell us what's the problem?
[ ] A typo
[ ] Wrong documentation
[ ] Improvement of existing article
[x ] Missing documentation
[ ] New article needed

### Please, tell us more details
https://docs.nativescript.org/core-concepts/application-lifecycle

I think it's worth mentioning in this article (and may be emphasize it somehow) the fact that application lifecycle hooks are run outside of any Angular zone. Thus, if any changes are made to the app state which may affect the UI, they will not be reflect in the UI until next change detection happens. This is a real pitfall, i've run into and spend quite a lot of time figuring out the reason.

**Comment by NickIliev** [comment]
Resolved via https://github.com/NativeScript/docs/pull/1854
