### ISSUE TITLE
image dokcer ?

### ISSUE THREAD

**Issue by ghost** [NativeScript/docs-v7#1860]
Why not simply have a docker image to download via the repository ?

**Comment by NickIliev** [comment]
@Fabiyo-90 the documentation is relying on multiple repositories and (in the common case)  those repos have to be updated (so you could build the latest documentation). I am not familiar with the options that a Docker image provide but if it is possible to create an image that will pul the latest repos that are needed then you could create one an post a PR.

**Comment by NickIliev** [comment]
@Fabiyo-90 a docker image containing the whole documentation would be around 500MB .. quite too large for a GitHub repo.
