### ISSUE TITLE
Broken API Reference Links within Vuejs Nativescript UI Document Pages

### ISSUE THREAD

**Issue by chriskeehealth** [NativeScript/docs-v7#1891]
### Please, tell us what's the problem?
[X] A typo
[ ] Wrong documentation
[ ] Improvement of existing article
[ ] Missing documentation
[ ] New article needed

### Please, tell us more details
You can repro by clicking API reference links on [RadSlideDrawer - Overview](https://docs.nativescript.org/vuejs/ns-ui/sidedrawer/overview)

This issue with the urls is that they have `/vuejs` as the first route parameter.  I’ve noticed that if you remove the `/vuejs` from the url, it resolves to the appropriate API reference page

**Comment by avats-dev** [comment]
@chriskeehealth the links seem to be working , can you check this again and update. They are working for me so there might be some platform dependent issue in case which I can't say for sure.

**Comment by chriskeehealth** [comment]
@avats-dev The links are now working.  Thanks
