### ISSUE TITLE
NativeScript image builder disapear.

### ISSUE THREAD

**Issue by dimitri-bret** [NativeScript/docs-v7#1902]
### Please, tell us what's the problem?
[ ] A typo
[ ] Wrong documentation
[ ] Improvement of existing article
[x] Missing documentation
[ ] New article needed

### Please, tell us more details

this documentation page: https://docs.nativescript.org/ui/image-resources#adding-android-resources explains how the ressource system works in Android and IOS, it also gives a link to generate ressources folder, this tool was very useful!
The tools was here: http://nsimage.brosteins.com/

Unfortunately this tool is no longer available... I used it a week ago.
I did not find the repository, is there any way to get this tool back? or any alternative, i could not find the repo of this tool, I think it should be back under an official Nativescript adress, if it is possible.

Anyways, if this tool is not available and can't be restored, (which is a shame), you should remove the broken link, (I can do a PR for that if you want). 

Thank you.

**Comment by dimitri-bret** [comment]
Just found this assets generator, http://mobileassetgenerator.pythonanywhere.com/, it is a good replacement candidate

**Comment by NathanaelA** [comment]
No, unfortunately, we have no control over that site, so we will get the docs updated.  However, two other asset generators exist:   https::/images.nativescript.rocks and the TNS CLI has some built in.
