### ISSUE TITLE
"Requesting permission to use location service" javascript snippet is not valid, page unclear.

### ISSUE THREAD

**Issue by danielrob** [NativeScript/docs-v7#197]
[The location documentation](https://github.com/NativeScript/docs/blob/production/location.md#request-a-permission-to-use-location-service) has a javascript snippet which is mostly typescript - it crashes the ios emulator: 

```
var buttonModule = require("ui/button");
var appModule = require("application");
var platformModule = require("platform");

var onRequestButtonTap = function(args: observable.EventData) {
    var button = <buttonModule.Button>(args.object);
    if (button.android) {
        console.log("Application run on Android");
        (<android.app.Activity>appModule.android.currentContext).startActivityForResult(new android.content.Intent(android.provider.Settings.ACTION_LOCATION_SOURCE_SETTINGS), 0);
    }
    else if (button.ios) {
        console.log("Application run on iOS");
        if (platformModule.device.osVersion.indexOf("8") === 0) {
            console.log("iOS version is greater or equal to 8.0");
            var iosLocationManager = CLLocationManager.alloc().init();
            iosLocationManager.requestWhenInUseAuthorization();
        }
    }
```

---

Further to this, this whole section is not as clear as it might be - it took me some time to decipher. I think it could be more obvious with an end-to-end example. The following is a suggested structure for the page:

---
## Configure a location service for the application

To enable location services it is first required to configure a location service in the respective application bundles: 

For an IOS 8.0+ project:  
Add one of the two following snippets to `<applicationName>-Info.plist` depending on your business needs: 

```
<key>NSLocationAlwaysUsageDescription</key>
<string>Your message goes here</string>

<key>NSLocationWhenInUseUsageDescription</key>
<string>Your message goes here</string>
```

In an Android project:   

```
<android example/instructions>
```
## Request permission to use the location service

Next, a request to use the location service is required. Unfortunately... `(section as it stands with corrected javascript snippet above)...`
## Getting a location

`
Either point to, or move the` [HOW-TO](https://github.com/NativeScript/docs/blob/production/ApiReference/location/HOW-TO.md) `page to this location in the interests of DRY. The HOW-TO page seems clearer, and contains more information (with less words).`

**Comment by danielrob** [comment]
If someone would provide me with the javascript snippets, and android instructions, I'd be happy to draft up a pull request along the lines of the suggestion above. [It seems I'm not the only one](http://www.telerik.com/forums/nativescript-app-location-not-available#PogImgAAyEeU8CmlHnnR1g) who found this a tad difficult to decipher.

**Comment by jlooper** [comment]
hi, @danielrob, I have location working in my School Bell Weather app. What a nightmare it was to configure it, and I had help from a lot of people. You can use the code here: https://github.com/jlooper/SBW-NativeScript/tree/master/app - and you need to change your Info.plist and Manifest.xml files to handle the particular platform issues you'll encounter. The one good thing about this mess is that you can test location changes in the iOS emulator.

**Comment by danielrob** [comment]
@jlooper that apps awesome! See more below:). First regarding this issue I did figure out the location services in the end which is why I was suggesting the requirement you mentioned - updating the Info.plist and Manifest.xml be fed back into the documentation in a clearer manner. Could you comment on what documentation might have made your issue easier?

Your app is brilliant! If I am reading it correctly, you hook up a callback on the `locationManagerDidChangeAuthorizationStatus` to re-request the location after an authorization status change (which you expect to get after calling requestWhenInUseAuthorization). This solves the asynchronous nature of that problem (I was looking into nastier options like setInterval checking inside a promise). 

Related, I had an issue with the "Allow "" to access your location"  dialogue disappearing if the user didn't respond after a few seconds. Your use of `dialogs.alert().then()` seems to improve this problem - the timeout is much longer after an alert. However I can't see how or determine if your app handles the case where the user doesn't respond (the dialogue does eventually timeout with your code). Do you have any comments on this?

**Comment by jlooper** [comment]
@danielrob thanks! As you noticed, I have this check for the app's status for iOS: https://github.com/jlooper/SBW-NativeScript/blob/51675be1d9b8a2be3a06048397496c6f25170cbf/app/main-view-model.js#L26-L32
These lines check to see what status has been handed back to the app. I probably should beef it up to pop an alert if the status is 'not authorized' and restart the loop to try to get permission to use location.

I am sure that more could be done on the Android front as well, to handle situations where the user refuses permission to access location. I always find Android a bit more obtuse.

If you want to fork my code and improve it, I'll be really happy!

**Comment by N3ll** [comment]
@danielrob - thank you very much for the support! We are working on improving this article because the code which you referring to is deprecated. There is a new [plugin](https://www.npmjs.com/package/nativescript-geolocation) for working with the location. There you can also find a link to an example of how to use it.

**Comment by jlooper** [comment]
@N3ll @danielrob wow, I didn't know about this plugin. I'm not sure, however that it covers the same use case. The code I'm referencing above is managing the native popup that appears when you enable location via the Info.plist in iOS, which is more complicated than in Android. In the geolocation plugin, I don't see instructions on how to do that. Is that use case covered? cc @nsndeck

**Comment by danielrob** [comment]
@N3ll @jlooper Yes, this plugin appears to add some simplification to managing locations once access is granted. I'm unable to determine (couldn't find source code?) whether it changes the prelude for ensuring location services authorisation?

**Comment by nsndeck** [comment]
@danielrob @jlooper The plugin provides API for granting access to location services (both for Android and iOS). Indeed for iOS granted access is only when in use. I've just updated plugin to 0.0.6 version and now there is also an info message for `Always in use`. API for granting access to location service is just a single method `enableLocationRequest` which takes an optional single boolean parameter (this parameter makes sence only for iOS and indicates `Always` and `When in Use` request). I've just updated [example](https://github.com/nsndeck/locationtest) with a button that demonstrates this functionality.

**Comment by d4mn** [comment]
@nsndeck did you removed nativescript-geolocation? Because I can't get it installed there is no files or folders created

**Comment by tjvantoll** [comment]
I’m going to go ahead and close this because this page has [drastically changed](https://docs.nativescript.org/releases/changes), and the code samples at the beginning of this issue is no longer used. If anyone still is having issues with this page please open a new issue. And thanks!
