### ISSUE TITLE
image-source class docs outdated

### ISSUE THREAD

**Issue by afortaleza** [NativeScript/docs-v7#198]
This is outdated, for example, the function loadFromBase64 should be fromBase64

https://docs.nativescript.org/ApiReference/image-source/ImageSource.html

**Comment by N3ll** [comment]
@afortaleza  - those are two different methods. 

 **loadFromBase64(source: string): boolean;** - Loads this instance from the specified native image data.
**fromBase64(source: string): ImageSource;** - Creates a new ImageSource instance and loads it from the specified resource name.

You can check all of the method in the [image-source.d.ts](https://github.com/NativeScript/NativeScript/blob/e56d90b06025c1979e98e0da0d835aecd404a32e/image-source/image-source.d.ts#L52).
