### ISSUE TITLE
Document icon fonts and binding

### ISSUE THREAD

**Issue by tjvantoll** [NativeScript/docs-v7#200]
See https://github.com/NativeScript/NativeScript/issues/1197, as this has come up a lot.

A lot of people are using icon fonts in {N} apps, so I feel like we should add a quick note on our existing fonts documentation about using them—specifically this caveat about how to use them with data binding.

cc @jlooper @sitefinitysteve

**Comment by sitefinitysteve** [comment]
100% I think it needs an entire detailed section, not just a blog post (although a link to that wouldn't hurt).

Support has gotten a ton better, but if it saves someone 2 hours of headaches, then great

**Comment by tiagordc** [comment]
+1

**Comment by hamorphis** [comment]
Working on it...
