### ISSUE TITLE
GridView and its HOW-TO doc example uses ".setColumn" which doesn't exist anymore. Please provide a real example!

### ISSUE THREAD

**Issue by mike-ense** [NativeScript/docs-v7#219]
Hi,

https://docs.nativescript.org/ApiReference/ui/layouts/grid-layout/HOW-TO.html is completely confusing as discussed in https://groups.google.com/forum/#!topic/nativescript/O-uimQ4GDDE .

Also it uses .setColumn which doesn't exist anymore, so the actual example in there is broken ("gridLayout.setColumn(button1, 0);" etc.).

An example that actually shows how it works would be greatly appreciated. Please make it for mor than one row, so that one of the most unclear points, which is how to feed the GridView with cells across rows, is done.

Also http://docs.nativescript.org/ApiReference/ui/layouts/grid-layout/GridLayout.html claims that .setColumn exists which it does not, so it should be removed!

And perhaps the same document should mention something so the reader can understand how data is fed to it.

(Trying to run .setColum gives the error "gridLayout.setColumn is not a function".)

Thanks!
Mike

**Comment by mike-ense** [comment]
Ah also for that example to be meaningful, there needs to be actual content e.g.: button1.text = "Button 1"; label1.text = "Label 1";

**Comment by mike-ense** [comment]
Sorry - the broken example is the one at https://www.nativescript.org/blog/details/demystifying-nativescript-layouts . The HOW-TO example is fine.

Its mistake is to say "gridLayout.setColumn" where it should be "layout.GridLayout.setColumn".

With this fix, got it working!

If anything is not working perfectly I'd post it separately here, otherwise can be closed in 7 days.

A final question here is, why do you use static classes for assignment like this - I mean, why not just do it within the instance?

Thanks :)

**Comment by jlooper** [comment]
@mike-ense, thank you for noting the broken example. I need to update that post. I think what I state about 'Border' is out of date as well.

**Comment by jlooper** [comment]
I have updated the article on layouts. Thanks for letting me know about it
