### ISSUE TITLE
Borked Markdown on Data Binding

### ISSUE THREAD

**Issue by sitefinitysteve** [NativeScript/docs-v7#227]
http://docs.nativescript.org/core-concepts/bindings#binding-to-a-plain-object

![docs](https://cloud.githubusercontent.com/assets/1542376/12494272/3c3aeb08-c057-11e5-9ee4-6ec801001587.PNG)

**Comment by sitefinitysteve** [comment]
More 
http://docs.nativescript.org/core-concepts/properties

**Comment by ErjanGavalji** [comment]
@sitefinitysteve, thanks for the report!

Fixed in commit [3e0b28](https://github.com/NativeScript/docs/commit/3e0b28097e6124a54a4959f36d23a69be0b55b56)
