### ISSUE TITLE
Move the API reference to typedoc

### ISSUE THREAD

**Issue by enchev** [NativeScript/docs-v7#239]
_From @PanayotCankov on September 18, 2015 12:21_

Currently we have an in-house tool that generates an [API reference page](https://docs.nativescript.org/ApiReference/data/observable/Observable) for us. There is a public open-source state-of-the-art tool [typedoc](http://typedoc.io/) that generates much more extensive and feature rich API reference we can adopt.

_Copied from original issue: NativeScript/NativeScript#773_

**Comment by enchev** [comment]
_From @PanayotCankov on November 10, 2015 9:50_

[The grunt has been updated to generate api reference for the NativeScript modules](https://github.com/NativeScript/NativeScript/pull/1070).

We will have to find a proper place on [docs.nativescript.org](docs.nativescript.org) for the API reference, and integrate the site specific elements such as headers and footers in the typedoc.
According to the [typedoc documentation about theming](http://typedoc.io/guides/themes.html) we can override small parts of the default theme ([e.g. header](https://github.com/sebastian-lenz/typedoc-default-themes/blob/master/src/default/partials/header.hbs)) and inject our CSS-es.

**Comment by ErjanGavalji** [comment]
API-Ref gets generated via typedoc as of 2.0.0
