### ISSUE TITLE
Update help article http://docs.nativescript.org/ui/action-bar#styling

### ISSUE THREAD

**Issue by enchev** [NativeScript/docs-v7#243]
_From @myninka on February 18, 2016 9:11_

Update help article http://docs.nativescript.org/ui/action-bar#styling to use the back icon from here: https://design.google.com/icons/#ic_arrow_back

We can replace all the icons used in the help for Android with the material icons here: https://design.google.com/icons/

_Copied from original issue: NativeScript/NativeScript#1574_

**Comment by tjvantoll** [comment]
It looks like this has since happened: http://docs.nativescript.org/ui/action-bar#styling. Closing this.
