### ISSUE TITLE
Update Plugins Doc: Needs info on InternalProperty override

### ISSUE THREAD

**Issue by sitefinitysteve** [NativeScript/docs-v7#246]
Summary: InternalProperty ignore syntax for iOS need to be documented

Killed myself for the last hour on this, it doesn't appear to be documented.

So I have a cocoapod and was trying to impliment background-color.  I wired up all the handler stuff, and implimented the documented methods (see below)

``` js
var FloatingActionButtonStyler = (function () {
    function FloatingActionButtonStyler() {
    }

    // BACKGROUND COLOR
    FloatingActionButtonStyler.setBackgroundColorProperty = function (view, newValue) {
        var fab = view.ios;
        fab.buttonColor = newValue;
    };
    FloatingActionButtonStyler.resetBackgroundColorProperty = function (view, nativeValue) {
        var fab = view.ios;
        fab.buttonColor = nativeValue;
    };
    FloatingActionButtonStyler.getNativeBackgroundColorValue = function (view) {
        var fab = view.ios;
        return fab.buttonColor;
    };

    FloatingActionButtonStyler.registerHandlers = function () {
        style.registerHandler(style.backgroundColorProperty, new style.StylePropertyChangedHandler(FloatingActionButtonStyler.setBackgroundColorProperty, FloatingActionButtonStyler.resetBackgroundColorProperty, FloatingActionButtonStyler.getNativeBackgroundColorValue), "FloatingActionButton");
    };
    return FloatingActionButtonStyler;
})();
exports.FloatingActionButtonStyler = FloatingActionButtonStyler;
FloatingActionButtonStyler.registerHandlers();
```

So regardless of me telling {N} which property of the UI widget to set the color on, it kept setting the background color of the OUTER UIView, not the specific UI element I wanted.

@NathanaelA was able to dig in and find this gem

``` js
style.registerHandler(style.backgroundInternalProperty, style.ignorePropertyHandler, "FloatingActionButton");
```

Which I guess tells {N} to ignore it or something?

I feel like this should be documented somewhere, and IMO the iOS plugin docs would be more readable with the Styler\registerHandler syntax that you guys use internally.

**Comment by vakrilov** [comment]
This issue no longer relevant as most of the property-system code is different. There is a new [properties article](https://docs.nativescript.org/core-concepts/properties) you can check.
