### ISSUE TITLE
ui/editable-text-base options need available type values present in the docs

### ISSUE THREAD

**Issue by nraboy** [NativeScript/docs-v7#250]
I am looking here:

https://docs.nativescript.org/ApiReference/ui/editable-text-base/Options.html

I don't know what the "string" values can be for each of the properties.  Would be nice to know the available options for each string property on this page.

Best,

**Comment by tjvantoll** [comment]
Link is now https://docs.nativescript.org/api-reference/classes/_ui_editable_text_base_.editabletextbase.html. @nraboy does the updated site and structure help at all?

**Comment by nraboy** [comment]
It is certainly more descriptive, but now I think it is more confusing.  I also ran into dead links:

https://docs.nativescript.org/api-reference/enums/AutocapitalizationType/README.md

Best,

**Comment by tjvantoll** [comment]
@nraboy: Ok I’ll follow up on the descriptions then. Did you find that URL on our docs or is that just something you had saved from before?

**Comment by nraboy** [comment]
I found it from clicking around in your documentation.

**Comment by etabakov** [comment]
Guys, these articles don't exist anymore. Let's open a new issue if there is still work left to be done. Also, I think the broken links have been fixed.
