### ISSUE TITLE
Node Version unclear

### ISSUE THREAD

**Issue by sipacate** [NativeScript/docs-v7#253]
In the System Requirements section, node.js 5.1.x is offered as a possibility.
The latest Node.js 0.10.x, 0.12.x, 4.2.x, or ​_5.1.x_​ stable official release

In the Setup section, 5.1.x is not mentioned.
Install the latest Node.js 0.10.x, 0.12.x, or 4.2.x stable official release.

Note, 5.1.x not in the setup

https://github.com/NativeScript/docs/blob/production/start/ns-setup-win.md

**Comment by tjvantoll** [comment]
We now support 6.x and the docs don’t mention that (yet) either.
