### ISSUE TITLE
Genymotion Step Unclear (Workflow changed on Genymotion side?)

### ISSUE THREAD

**Issue by sipacate** [NativeScript/docs-v7#254]
These instructions make it seem like you can download the Genymotion bits from the redirected page. What actually happens is you are prompted to make an account. Please adjust to account for the _new_ workflow.

http://docs.nativescript.org/start/ns-setup-win 
Step 6

(Optional) Install Genymotion.
Genymotion is a third-party native emulator.
Go to Get Genymotion, select Windows and click Get Genymotion.
You might want to download the larger archive which contains VirtualBox.
If prompted, confirm the download.
After the download completes, run the installer and complete the installation.

**Comment by tjvantoll** [comment]
Adding up-for-grabs. If anyone stumbles upon this and is interested in contributing feel free to send a pull request. If you need help getting started you can ping me in the [community Slack channel](http://developer.telerik.com/wp-login.php?action=slack-invitation) (I’m tjvantoll).
