### ISSUE TITLE
Problem with Gestures docs

### ISSUE THREAD

**Issue by sitefinitysteve** [NativeScript/docs-v7#265]
You cant just paste in the gesture code, "gestures is not defined" is the error that gets thrown.

https://docs.nativescript.org/ui/gestures#subscribing-to-multiple-gestures-and-events

Perhaps this is is TS code in the JS section? (I realize gestures.GestureTypes.swipe is just "swipe" but in js it should be the string)

**Comment by tjvantoll** [comment]
Hey @sitefinitysteve. 

Sorry for the late reply here. It looks like the snippet in question has been fixed now.
