### ISSUE TITLE
Troubleshooting article with list of known problems

### ISSUE THREAD

**Issue by enchev** [NativeScript/docs-v7#269]
We can list various known problems like this one:
https://github.com/NativeScript/NativeScript/issues/1722

**Comment by tjvantoll** [comment]
We already have a troubleshooting article at http://docs.nativescript.org/start/troubleshooting. I’ll add up-for-grabs in case anyone from the community wants to add the Android button issue. If anyone stumbles upon this and is interested in contributing feel free to send a pull request. If you need help getting started you can ping me in the [community Slack channel](http://developer.telerik.com/wp-login.php?action=slack-invitation) (I’m tjvantoll).
