### ISSUE TITLE
Review the articles within the Start section

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/docs-v7#275]
These are:
- https://github.com/NativeScript/docs/blob/production/start/faq.md
- https://github.com/NativeScript/docs/blob/production/start/getting-started.md
- https://github.com/NativeScript/docs/blob/production/start/introduction.md
- https://github.com/NativeScript/docs/blob/production/start/ns-setup-linux.md
- https://github.com/NativeScript/docs/blob/production/start/ns-setup-os-x.md
- https://github.com/NativeScript/docs/blob/production/start/ns-setup-win.md
- https://github.com/NativeScript/docs/blob/production/start/samples.md
- https://github.com/NativeScript/docs/blob/production/start/troubleshooting.md

**Comment by erikruth** [comment]
I have edited all of these. General editing question about capitalization of your headings: Is it your style that heading 2s are Title case and heading 3s are Sentence case? I figured that out about 1/2-way through but wanted to confirm before I made changes everywhere.

In the getting started article (https://github.com/NativeScript/docs/blob/production/start/getting-started.md), I just see your list of include files with the markdown files. I expected to see a page running with links to files to edit but that didn't work.

In the introduction article (https://github.com/NativeScript/docs/blob/production/start/introduction.md) the architecture diagram didn't work. Perhaps the link is bad?

I reviewed but had no changes to the troubleshooting article (https://github.com/NativeScript/docs/blob/production/start/troubleshooting.md) so you won't see any pull requests from me.
