### ISSUE TITLE
Add ActionBar platform specific styling instructions

### ISSUE THREAD

**Issue by sitefinitysteve** [NativeScript/docs-v7#278]
This is a common question, styling the Actionbar\statusbar on iOS... I think it should be in the ActionBar How-To docs

``` js
    if (app.ios) {
        var navigationBar = frame.topmost().ios.controller.navigationBar;;
        navigationBar.barStyle = 1;        //Style the top status bar
        navigationBar.tintColor = UIColor.whiteColor();        //Style the top status bar
        navigationBar.translucent = false; //Stop the actionbar from being seethrough, and thus not the hex code you set
    }
```

**Comment by tjvantoll** [comment]
We have a [well documented page for the ActionBar](https://docs.nativescript.org/ui/action-bar) now, but still nothing on the status bar. I think the status bar is a common enough thing to want to alter that it deserves its own page on the docs.

**Comment by tjvantoll** [comment]
ACTUALLY this totally exists now at http://docs.nativescript.org/angular/ui/change-status-bar-style-ios.html. Who knew?

@sitefinitysteve if you have any other problems with this let me know, but I’m closing this for now.
