### ISSUE TITLE
Review the articles within the core-concepts

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/docs-v7#284]
These are:
- https://github.com/NativeScript/docs/blob/production/core-concepts/accessing-native-apis-with-javascript.md
- https://github.com/NativeScript/docs/blob/production/core-concepts/application-management.md
- https://github.com/NativeScript/docs/blob/production/core-concepts/bindings.md
- https://github.com/NativeScript/docs/blob/production/core-concepts/debugging.md
- https://github.com/NativeScript/docs/blob/production/core-concepts/events.md
- https://github.com/NativeScript/docs/blob/production/core-concepts/modules.md
- https://github.com/NativeScript/docs/blob/production/core-concepts/navigation.md
- https://github.com/NativeScript/docs/blob/production/core-concepts/properties.md
- https://github.com/NativeScript/docs/blob/production/core-concepts/publishing-android-apps.md
- https://github.com/NativeScript/docs/blob/production/core-concepts/publishing-ios-apps.md
- https://github.com/NativeScript/docs/blob/production/core-concepts/testing.md
- https://github.com/NativeScript/docs/blob/production/core-concepts/transpilers.md
- https://github.com/NativeScript/docs/blob/production/core-concepts/visual-studio-code-extension.md

I have verified the problem with architecture diagram. You can review the article with correct image src path here: https://github.com/NativeScript/docs/blob/master/start/introduction.md

**Comment by erikruth** [comment]
All of these were individually edited. I think you can remove this task.
