### ISSUE TITLE
Menu Bar Closes On Child Selection

### ISSUE THREAD

**Issue by burkeholland** [NativeScript/docs-v7#307]
Every time you select an option in the menu it closes regardless option has child options. so you basically have to open the menu > scroll to the parent of the Item you want > select said item then repeat until you get to the info you want. On top of that the menu options aren't very finger friendly.

**Comment by tjvantoll** [comment]
Ping @ErjanGavalji. This would be a good thing to add to our list of things to fix when we apply the styling updates.

**Comment by ErjanGavalji** [comment]
A good catch! Seems we lost the treeview expanded state persistence for some reason (http://docs.telerik.com/kendo-ui/controls/navigation/treeview/how-to/persist-expanded-state)
