### ISSUE TITLE
ui/ui-images Documentation Needs Correcting

### ISSUE THREAD

**Issue by ikoevska** [NativeScript/docs-v7#310]
Hey guys,

I was using your sample syntax from http://docs.nativescript.org/ui/ui-images to add an image to my iOS app. Using your syntax, my view which contained the image kept crashing. The reason was an erroneous space for all XML syntax which was causing an error during the building of the UI.

This kept causing my app to crash:

```
<Image src="~/logo.png" / >
```

This made my app work as expected:

```
<Image src="~/logo.png" />
```

Please, remove the erroneous space from all examples.

**Comment by tjvantoll** [comment]
Thanks @ikoevska 😄
