### ISSUE TITLE
Add an article about launch screens and icon

### ISSUE THREAD

**Issue by enchev** [NativeScript/docs-v7#311]
_From @PanayotCankov on April 5, 2016 12:43_

_Copied from original issue: NativeScript/NativeScript#1886_

**Comment by enchev** [comment]
_From @jjTudu on April 5, 2016 13:53_

@PanayotCankov for icon you may go through https://www.youtube.com/watch?v=sKjJwsmng88, but in last just copy all the font file present in the font folder and Me too looking for splash Screen article

**Comment by tjvantoll** [comment]
Closing this as we have this article now for iOS, and the Android one is coming with https://github.com/NativeScript/docs/pull/445.
