### ISSUE TITLE
OS-X getting started guide missing information

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/docs-v7#331]
The getting started guide for OSX on the main docs site is missing critical information for new users getting things installed.

The docs do NOT list how to install (or that you even need) the:
 xcodeproj, or cocoapods , and xcproj.    

These have been required for a while now, and really need to be listed as prereqs and how to install them...  The good new is TNS doctor will complain about these missing, but it leaves the user scratching his head on how to fix the issue...

**Comment by dtopuzov** [comment]
Hope this help:
https://github.com/NativeScript/nativescript-cli#manual-setup-1
We will add this in official docs.

**Comment by NathanaelA** [comment]
Thanks, I'll forward any new people who ask about it to those docs.   But since we are expecting a lot of new people in the next couple days; any chance we can get those added to the main docs asap. 

  And CocoaPod is not really an optional item anymore; if you install the majority of the plugins on iOS it will require it...

**Comment by tjvantoll** [comment]
Hey @NathanaelA,

I just removed the optional label from CocoaPods, so I think your points have (hopefully) been addressed. Could you confirm? http://docs.nativescript.org/start/ns-setup-os-x

**Comment by NathanaelA** [comment]
Almost have it; at the top of the list it still doesn't list CocoaPod at all.   ;-)
I think I would personally remove the (optional) tag on xcproj; many people probably won't know which version of cocoapod they have installed.    It probably would be just safer to waste the tiny amount of disk space for xcproj...  :grinning:

**Comment by tjvantoll** [comment]
@NathanaelA: Good catch on CocoaPods not being listed on the top. I just pushed a commit to add that.

As for `xcproj`, I’m sort of torn. If people are following the guide and run `gem install cocoapods`, then they’ll get version 1.x.y now, so for the vast majority of people that step is unnecessary. My gut says I should just add a quick note to the step that tells people about `pod --version` so they’ll instantly know to skip that install. Thoughts?

**Comment by tjvantoll** [comment]
Current:

> (Optional) If you are using Xcode 7.3 and CocoaPods 0.39.0 or earlier you must install xcproj command-line tool either by running brew install xcproj in the terminal, or building the xcproj tool manually with xcodebuild.

My thought:

> (Optional) If you are using Xcode 7.3 as well as an older version of CocoaPods (0.39.0 or earlier), you must install the `xcproj` command-line tool by running `brew install xcproj` in your terminal. You can check your CocoaPods version with `pod --version`.

**Comment by NathanaelA** [comment]
I think that would work!   Thanks @tjvantoll

**Comment by NathanaelA** [comment]
Hmm, one update; in the slack today we had to downgrade someone from cocoapods 1.01 to 0.39 to get his system to work.    Several of us are still using 0.39 (I am also) -- so you might need to update the docs and just show how to install 0.39 so that others don't run into the 1.01 issue...

**Comment by tjvantoll** [comment]
@NathanaelA It seems like we lose no matter which way we go 😄 . Is that 1.0.1 issue documented somewhere?

I’m sort of learning towards your suggestion of just having people `brew install xcproj` to simplify the instructions considerably. @dtopuzov > any thoughts on that?

**Comment by NathanaelA** [comment]
To be honest, it is only documented on slack at this point.   I don't even know if it is just his machine, or if there is a general issue with v1.01 of cocoapods and NS.    All I know is he couldn't build any pods but no errors; just wouldn't build them and acted like they weren't installed.   Downgrading to v0.39 and resetting the platform folder again fixed it.

I do know that everyone that was helping on that channel was still running 0.39 of cocoapods.    Maybe we need to run a poll on the experts channel and see if anyone is running 1.01 successfully or if everyone stayed at 0.39.   :grinning:

**Comment by tjvantoll** [comment]
Bumping this as it’s been awhile. @dtopuzov > any concerns with just having people blindly run `brew install xcproj`? There doesn’t seem to be much harm, and it’ll simplify things considerably.

**Comment by tsonevn** [comment]
This issue has been already resolved and the needed information is included in the docs. http://docs.nativescript.org/start/ns-setup-os-x
