### ISSUE TITLE
TypeScript example tab in the documentation incorrect.

### ISSUE THREAD

**Issue by JoshDSommer** [NativeScript/docs-v7#336]
There are two Typescript Tabs on the below pages instead of JavaScript and TypeScript. 
The first tab is a JavaScript Example and appears to be correct while the second is listing `import observable = require("data/observable");` as the TypeScript example incorrectly. 
- https://docs.nativescript.org/cookbook/ui/text-field
- https://docs.nativescript.org/cookbook/ui/text-view

**Comment by tjvantoll** [comment]
Thanks for pointing this out @TheOriginalJosh.

Ping @PanayotCankov @ErjanGavalji. Hey guys, any idea why this is happening? I [tracked down the snippets in the NativeScript/NativeScript repo](https://github.com/NativeScript/NativeScript/blob/dfaf481d6d2538372c13f9eab08d523cb5f6e9af/tests/app/ui/text-view/text-view-tests.ts#L16-18) but I can’t for the life of me figure out what causes those tab titles to be off.

**Comment by NickIliev** [comment]
PR [https://github.com/NativeScript/NativeScript/pull/3966](https://github.com/NativeScript/NativeScript/pull/3966)
