### ISSUE TITLE
"How To" doc sessions disappeared

### ISSUE THREAD

**Issue by calebeaires** [NativeScript/docs-v7#339]
Since NativeScript 2.0, search and links on docs redirect us to the API REFERENCE. The way that was before is better because there was code examples and "how to" pages. The way it is now I cant access those page anymore.

**Comment by tjvantoll** [comment]
Thanks for the feedback @calebeaires. The pages are still there, but they’re now under the “COOKBOOK” section of the docs. We’re thinking of ways to make those pages more visible, and also to improve the examples there.

**Comment by calebeaires** [comment]
Before, when 1.7 to 2.0, search were sending all results to API page. know it is good
