### ISSUE TITLE
"Chapter 2 - Building the UI" - section 2.1- typo with line count

### ISSUE THREAD

**Issue by cfjedimaster** [NativeScript/docs-v7#352]
This text:

Let's start with app/app.js, as it's the starting point for NativeScript apps. Your app.js contains the three lines below:

Should be changed to say _two_ lines.

**Comment by cfjedimaster** [comment]
Or include the 3rd line - yeah - add that. :)

**Comment by cfjedimaster** [comment]
Yeah, add the 3rd line. The text going on refers to it.

**Comment by tjvantoll** [comment]
See also https://github.com/NativeScript/sample-Groceries/commit/03d3918f91dc8f10fcf86dbdbd6fc3f0d5404586.

Thanks @cfjedimaster 😀
