### ISSUE TITLE
Chapter 3.1 - add a note about console

### ISSUE THREAD

**Issue by cfjedimaster** [NativeScript/docs-v7#353]
If the user doesn't see the console message, they may need to restart tns - I needed to. Perhaps add a small warning/tip.

**Comment by tjvantoll** [comment]
Hmmmm, that’s odd. I’ll add this to my list of things to check out with my next pass through the guide. We have a bunch of improvements coming to the CLI in our next release so hopefully this experience improves.

Thanks for the feedback.

**Comment by tjvantoll** [comment]
Hey @cfjedimaster,

I’m going to close this for now as we haven’t heard this from other users and I can’t recreate the problem.

If you are a casual google searcher that stumbles upon this issue, and you’ve also experienced the problem, please let me know and we can add a note or fix the underlying issue.
