### ISSUE TITLE
Chapter 4.4 - grocery-list-view-model.js

### ISSUE THREAD

**Issue by cfjedimaster** [NativeScript/docs-v7#356]
This is _really_ minor, but this part:

A starting view model for this page is already in the file at app/shared/view-models/grocery-list-view-model.js, which contains code that looks a lot like what you already have in list.js:

The code shown on the page does not match, exactly, the default code you have. Specifically the handleErrors code is not on the web page. I don't imagine this will trip people up, but...

**Comment by tjvantoll** [comment]
Thanks @cfjedimaster.

Good point. I’m adding this to my list for my next full pass through the guide.

**Comment by radeva** [comment]
Closing this issue since the tutorial is now moved to https://play.nativescript.org
