### ISSUE TITLE
Document how to create a new Android AVD

### ISSUE THREAD

**Issue by tjvantoll** [NativeScript/docs-v7#358]
I think this trips a lot of people up, and we currently don’t have anything on our docs to address the topic. Cordova’s docs on the topic are really good http://cordova.apache.org/docs/en/5.1.1/guide/platforms/android/index.html#configure-an-emulator

**Comment by NickIliev** [comment]
Article awaiting revision

https://github.com/NativeScript/docs/blob/niliev-create-avd/tooling/android-virtual-devices.md

**Comment by tjvantoll** [comment]
Awesome @NickIliev! Here are my notes.

> By default, the Android SDK does not provide an instance of AVD so in this article we are going to cover the process of creation and usage of AVDs.

By default, the Android SDK does not provide an instance of an AVD, so in this article we are going to cover the process of creating and using one.

> Create new emulator

Create a new emulator

> In the screenshot below are shown installed system images for Android API 24.

The screenshot below shows installed system images for Android API 24.

Also, these instructions don’t make it clear exactly what the user should be doing. Should they install all of these system images? Is there a preferred one we can recommend? What is the difference between all of these options?

> You can accelerate the virtual device using Virtualization Technology. For hardware with Intel CPUs this can be achieved with HAXM installer. AMD Virtualization is only supported for Linux.

There should be specific instructions that say to select the “Intel x86...” checkbox and click the Install Packages button.

> By default, with fresh Android SDK installation

By default, with a fresh Android SDK installation

> To launch NativeScript application on specific device you can pass --device <id>

To launch a NativeScript application on a specific device you can pass `--device <id>`.

> To launch NativeScript application on all connected devices simultaneously simply ignore --device flag

To launch a NativeScript application on all connected devices simultaneously, simply ignore the `--device` flag.

**Comment by tjvantoll** [comment]
Also we may want to consider updating the Windows and OS X installation docs to recommend going through this process instead of sending them off to Genymotion.

**Comment by NickIliev** [comment]
Hey @tjvantoll thanks for the notes - I will revise the article asap.
