### ISSUE TITLE
Camera doc typo

### ISSUE THREAD

**Issue by cfjedimaster** [NativeScript/docs-v7#359]
On this page, http://docs.nativescript.org/hardware/camera, there is a typo here:

"What device independent pixels means?"

Missing "does"

**Comment by sipacate** [comment]
OK I fixed this and it'll get reflected on the next prod doc compilation.

**Comment by tjvantoll** [comment]
Closed with d4f59b5148ca20db9f9275cc37a1e2bdae7e98d9.
