### ISSUE TITLE
links of Modules not found_and other broken links

### ISSUE THREAD

**Issue by kazemihabib** [NativeScript/docs-v7#360]
none of the links of  [Modules](http://docs.nativescript.org/angular/core-concepts/modules) works

**Comment by hdeshev** [comment]
Fixed. Thanks for reporting it!

**Comment by kazemihabib** [comment]
breaks again.404 error for links.

**Comment by hdeshev** [comment]
Works now. I hope this time it stays that way :disappointed_relieved:

**Comment by kazemihabib** [comment]
404 error for https://docs.nativescript.org/cookbook/ui/html-view the link is in this page : 
https://docs.nativescript.org/ui/components#htmlview
