### ISSUE TITLE
Redirect 301 from older docs to new docs URL pattern

### ISSUE THREAD

**Issue by leocaseiro** [NativeScript/docs-v7#373]
Hi, I'm new into NativeScript and I got myself frustrated with all broken links that are indexed by Google. Especially because the {N} site uses Google Search.

![screen shot 2016-05-26 at 11 30 05 am](https://cloud.githubusercontent.com/assets/940070/15561041/440070b0-2335-11e6-9ad1-3e8835f62958.png)

My suggestion is to map the old links with the new links.
Examples:
- From [https://docs.nativescript.org/ApiReference/ui/text-field/README.html](https://docs.nativescript.org/ApiReference/ui/text-field/README.html) to [http://docs.nativescript.org/api-reference/modules/_ui_text_field_.html](http://docs.nativescript.org/api-reference/modules/_ui_text_field_.html)
- From [http://docs.nativescript.org/ApiReference/ui/search-bar/SearchBar.html](http://docs.nativescript.org/ApiReference/ui/search-bar/SearchBar.html) to [http://docs.nativescript.org/api-reference/modules/_ui_search_bar_.html](http://docs.nativescript.org/api-reference/modules/_ui_search_bar_.html)

Normally, when you find these links, you are redirected to [Api reference page](http://docs.nativescript.org/api-reference/) which is REALLY frustrated.

The best way is with [redirect 301](https://support.google.com/webmasters/answer/93633?hl=en) which can be set with code or on the server.

PS: The redirect 301 will also make sure you keep your [PageRank](https://en.wikipedia.org/wiki/PageRank) as it was before instead of loose with broken links.

**Comment by tjvantoll** [comment]
Thanks @leocaseiro for reporting this. I was hitting this myself for a while. I _think_ Google has picked up on the new URLs, because I’m no longer having this issue when searching. I think we’ve finally also cleaned up the bad links in the docs themselves. Are you seeing this problem anymore?

**Comment by leocaseiro** [comment]
Hi @tjvantoll. looks good now.

I'm happy to close this issue.

Thanks for your feedback.
