### ISSUE TITLE
"Cookbook" section seems improperly named

### ISSUE THREAD

**Issue by cfjedimaster** [NativeScript/docs-v7#375]
I know this will be a bit vague, and it's also a matter of opinion, but I was _convinced_ that NS did not include the ability to detect connection status. Why? Because the connectivity thing was "hidden" in the Cookbook section. I've barely looked at that section because, typically, a "cookbook" refers to various examples, ie, "How do I build a RSS reader in NS". Opening that section up, it looks to be more of an API reference. I really think this needs to be renamed or reorganized in some way.

**Comment by tjvantoll** [comment]
Just as an update, changes to the “cookboook” are in the works—hopefully landing with the next release 😄

**Comment by etabakov** [comment]
With the latest update in the documentation, the cookbook section no longer exists and the content is distributed in the appropriate sections
