### ISSUE TITLE
Missing typescript extend syntax

### ISSUE THREAD

**Issue by petekanev** [NativeScript/docs-v7#376]
The [following article](https://docs.nativescript.org/runtimes/android/generator/extend-class-interface.html) shows how users can extend classes in NativeScript with JavaScript syntax but does not mention its TypeScript equivalent where it's necessary to return the native object reference in the class constructor. 

Consider the following:

``` typescript
class Config extends A.B.AbstractConfig {
    public a(): string { return ""; }
}
```

is not the same as 

``` typescript
class Config extends A.B.AbstractConfig {
    constructor() {
        super();
        return global.__native(this);
    }
    public a(): string { return ""; }
}
```

but code sample 2 is the same as this javascript

``` javascript
var Config = A.B.AbstractConfig.extend({
   a: function() { return ""; }
}
```

If the class is not correctly extended in TypeScript it may cause conversion errors and crash the application.

**Comment by georgeedwards** [comment]
Additionally, the code referenced in the article:

```
var constructorCalled = false;
var MyButton = android.widget.Button.extend({
        //constructor
        init: function() {
...
```

throws error:

> [ts] Property 'extend' does not exist on type 'typeof IntentService'.

So the definition files don't seem to reflect the extend property?

**Comment by roblav96** [comment]
@Pip3r4o can I get your email moving forward with making docs pull-requests?

**Comment by manoldonev** [comment]
Closing this as [article](https://docs.nativescript.org/core-concepts/android-runtime/binding-generator/extend-class-interface) seems to be updated with relevant TypeScript-specific examples.
