### ISSUE TITLE
missing requirement documentation

### ISSUE THREAD

**Issue by alvarolorentedev** [NativeScript/docs-v7#377]
the [installation steps](https://docs.nativescript.org/start/quick-setup) is missing the requirement of Python 2.x, that will cause the installation of nativescript to fail when running `npm i -g nativescript`.
The documentation sohould ash the user to install Python V2.x and make sure they add Python to the PATH (this is an option on the installation steps).

**Comment by tjvantoll** [comment]
Hey @kanekotic,

Sorry for the late reply here. By chance do you remember details of the error you received? Python is only a dependency if you’re using older versions of Node.js, as well as OS X or Linux. And since Python is installed by default on both we didn’t think we’d need to add this information to the docs.

**Comment by alvarolorentedev** [comment]
Yes, I agree so my environment was an Ubuntu-16.04 VM.
If I am not mistaken this version and most likely upcoming versions come by default with [python3](https://wiki.ubuntu.com/XenialXerus/ReleaseNotes). So the 2.x version in the latest LTS will not anymore be a default dependency.
Re-reading your documentation now it is true that you mention this is for 14.04 LTS version. So is my fault as i had a different environment. Just keep in mind when moving  documentation to a newer LTS version (16.04)  this will be a change.
Anyway, the good news that is the only difference on documentation I have found regarding compatibility of new version of Ubuntu and NativeScript.

**Comment by tjvantoll** [comment]
Ok thanks @kanekotic. I’m going to close this for now as it sounds like we’re good with 14.04 LTS, but this is a good thing to know when we upgrade. Ping @rosen-vladimirov for visibility.
