### ISSUE TITLE
Angular Components - 4040

### ISSUE THREAD

**Issue by leocaseiro** [NativeScript/docs-v7#381]
I've noticed all links from Angular Components page go to 404.

http://docs.nativescript.org/angular/ui/ui-views.html

It needs to switch from http://docs.nativescript.org/angular/angular/cookbook/ to http://docs.nativescript.org/cookbook/ instead.

Eq: http://docs.nativescript.org/angular/angular/cookbook/ui/search-bar

**Comment by tjvantoll** [comment]
Thanks @leocaseiro!

Some of these had been fixed in the master branch, and I think I just [cleaned up the rest](ad4bb97cd731c3725c1de3a4689d428fcf8d72f0). The fixes will be live the next time we push the docs out. Thanks again.
