### ISSUE TITLE
Chapter 1.1 - suggest installing node via homebrew on OSX instead of the pre-built installer

### ISSUE THREAD

**Issue by nirinchev** [NativeScript/docs-v7#389]
The docs [suggest](http://docs.nativescript.org/tutorial/chapter-1#11-install-nativescript-and-configure-your-environment) installing node.js via the pre-built installer which has the downside of requiring sudo on OSX to install packages (as explained in the step 2 note).

A better approach would be to point users to using homebrew (which they most likely are anyway) - this takes care of the npm permissions and is a requirement for the automatic script in step 3 anyway. Perhaps a note below/above the tip would suffice?

**Comment by tjvantoll** [comment]
Excellent idea. Implemented in 26f8e1b93d5b2191221ee92049e2466f74c86563. Thanks @nirinchev!
