### ISSUE TITLE
Review the articles within the hardware and cookbook

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/docs-v7#400]
- https://github.com/NativeScript/docs/blob/production/hardware/camera.md
- https://github.com/NativeScript/docs/blob/production/hardware/location.md
- https://github.com/NativeScript/docs/blob/production/cookbook/formatted-string-ng.md

**Comment by erikruth** [comment]
I edited the first two articles and because there were comments to address in both of them, I did not save them into into production. The cookbook link is producing a 404 error so I am  unable to edit it.

**Comment by tsonevn** [comment]
Hi @erikruth,

Excuse me for the delay in replying. I  changed the last link with the correct one.

**Comment by erikruth** [comment]
Hello @tsonevn, 

Thank you for fixing the cookbook link. I reviewed the article and have no copyediting changes. Nice work whoever wrote it.
Erik

**Comment by tsonevn** [comment]
Hi @erikruth,
Thank you for your reply.  If there is nothing to be fixed in the last article, I will close  this issue.
tsonevn
