### ISSUE TITLE
Anchor links on publishing android page not working

### ISSUE THREAD

**Issue by sitefinitysteve** [NativeScript/docs-v7#408]
Example: 
http://docs.nativescript.org/core-concepts/publishing-android-apps#submit-with-the-google-play-developer-console

**Comment by tjvantoll** [comment]
Hmmm... the problem here looks like our Jekyll setup doesn’t automatically add `id` attributes to `<h4>` elements, so the five anchor links to `<h4>` headers are all broken.

Ping @ErjanGavalji @hshristov. Should our Jekyll setup add these id attributes, or should we just remove the anchor links from this page?

**Comment by tjvantoll** [comment]
Also, thanks @sitefinitysteve once again for reporting these things 😄

**Comment by sitefinitysteve** [comment]
I would like the links to not go away if possible :smile:

**Comment by hshristov** [comment]
@hdeshev Should know better :)

**Comment by tjvantoll** [comment]
Oh man, that’s embarrassing. Too many Hristos 😛

**Comment by ErjanGavalji** [comment]
Though I set the `toc_levels` to 1..6 both in the global configuration file and the local file (via `{:options ...}`), [kramdown](http://kramdown.gettalong.org/converter/html.html) refused generating ids for heading level higher than 3.

I guess the problem might be related to using an older version of the parser. That would mean upgrading the entire jekyll environment to a more current version, but this is a larger task I'd leave for later.

What's your opinion, guys?

Cheers,
Erjan

**Comment by tjvantoll** [comment]
Hey @ErjanGavalji,

Yeah I definitely don’t think it’s worth a full Jekyll upgrade just for this. I did a quick search and I _think_ this is the only page with `<h4>` elements that we link to, so we can just use `#### Submit with Telerik AppManager` --> `<h4 id="submit-...">Submit with Telerik AppManager</h4>` for now.

**Comment by sitefinitysteve** [comment]
Yeah I would rather the resources are spent on the product not the docs :)  It's just that when you encounter this it feels like the link is there, but the content on the page is missing (like when you click it)... I mean I can just scroll down too, but you've made it historically too easy to jump around :+1:

**Comment by sitefinitysteve** [comment]
@tjvantoll Should you maybe run this by @hshristov ? :smiling_imp:

**Comment by hdeshev** [comment]
I have a PR with a Jekyll upgrade to 3.0.1 (using 3.0.0 now), but I doubt it will fix it. I can try another upgrade once my 3.0.1 PR lands in master.

**Comment by ErjanGavalji** [comment]
👍 
let's get the release and have Jekyll blown to the skies :)

**Comment by sitefinitysteve** [comment]
![image](https://cloud.githubusercontent.com/assets/1542376/16307069/ee970dbe-392d-11e6-83a3-fa7a53edc695.png)
