### ISSUE TITLE
angular components 404 pages

### ISSUE THREAD

**Issue by lawrencetaur** [NativeScript/docs-v7#415]
Many links on this page lead to 404s

https://docs.nativescript.org/angular/ui/ui-views.html#button

goes to https://docs.nativescript.org/angular/angular/cookbook/ui/button

supposed to go to https://docs.nativescript.org/angular/cookbook/ui/button

remove the extra **angular** in the urls

**Comment by hdeshev** [comment]
Thanks for your report! I have this issue fixed in the the master documentation branch, and it will be probably be easiest to deploy the fix to the official site once we release {N} 2.1 (coming really soon!)
