### ISSUE TITLE
search box problems in doc page

### ISSUE THREAD

**Issue by kazemihabib** [NativeScript/docs-v7#419]
1-by typing something in search box  when it says 
![nativescript-doc-search1](https://cloud.githubusercontent.com/assets/10830552/16545509/5c37f592-4142-11e6-95a4-f44c53be6cf3.png)
if press Enter it will redirect to [https://docs.nativescript.org/api-reference/classes/undefined](url)

2-the items shown below are not work by mouse click, they work just by keyboard keys and Enter
![nativescript-doc-search2](https://cloud.githubusercontent.com/assets/10830552/16545536/fe4f25a8-4142-11e6-8f2f-6d6280a2ceed.png)
3-In the above image as you see it's hard to read the items because of background texts.

**Comment by tjvantoll** [comment]
Hey @kazemihabib,

Thanks for the feedback here. I’ll definitely +1 all three of your points, as I’ve hit them all as well, and just in general find the API docs’ search functionality frustrating to use.

Ping @ErjanGavalji. Anything we can do here? I’m not sure what we’re using to generate the API docs, so I’m not sure where this actually comes from.

**Comment by etabakov** [comment]
All three items are resolved. Closing the isssue.
