### ISSUE TITLE
Cookbook should link to class-reference.

### ISSUE THREAD

**Issue by m-abs** [NativeScript/docs-v7#435]
It would be very nice, if the cookbook examples had a link to the class-reference of the element it's describing.

For example the cookbook page for the [Button](https://docs.nativescript.org/angular/cookbook/ui/button)-element should link to [Class Button](https://docs.nativescript.org/api-reference/classes/_ui_button_.button.html)

**Comment by tjvantoll** [comment]
I like this idea. @ErjanGavalji > do you know who’s working on our cookbook updates? This is good feedback to pass along.

**Comment by ErjanGavalji** [comment]
Team are working on removing the cookbook section in favor of a better structured SDK Examples section, which will be supported by an app. Each codeblock will have a link to the real code of the app.

**Comment by etabakov** [comment]
With the latest redesign all articles have links to the respective API Reference articles mentioned in the right sidebar.
