### ISSUE TITLE
Selected class not applied correctly in NativeScript Documentation Navigation

### ISSUE THREAD

**Issue by harlankoehn** [NativeScript/docs-v7#437]
Fairly minor issue but can be confusing. When you're in the Angular documentation, the Angular navigation item doesn't have the css selected class applied to it. Instead, the main documentation does.

**Comment by harlankoehn** [comment]
I see now that this issue has been documented #351

**Comment by tjvantoll** [comment]
Thanks for reporting this @harlankoehn. We should have this patched up soon. Closing in favor of #351.
