### ISSUE TITLE
AutocapitalizationType enumeration link broken

### ISSUE THREAD

**Issue by DewaldDeJager** [NativeScript/docs-v7#439]
The link under [autocapitalizationType](http://docs.nativescript.org/api-reference/classes/_ui_text_field_.textfield.html#autocapitalizationtype) is broken. The other place I found this enumeration was at [ui/enums](https://github.com/NativeScript/NativeScript/blob/release/tns-core-modules/ui/enums/enums.d.ts):322

**Comment by tjvantoll** [comment]
Thanks @DewaldDeJager! We’ll try to get this resolved in our next release.

**Comment by etabakov** [comment]
Currently, it looks like this is working. Feel free to reopen if the problem arises again.
