### ISSUE TITLE
Improve Bindings Doc to show propertyChange XML binding

### ISSUE THREAD

**Issue by sitefinitysteve** [NativeScript/docs-v7#440]
Please add a sample in the docs to show XML binding to propertyChange

``` xml
<Switch checked="{{ filterNeedSummary }}" propertyChange="onFilterItemChange" />
```

``` js
export function onFilterItemChange(args){
   alert("Property Changed");
}
```

I encounter this every once and a while, and the docs elude to propertyChange, but there's no XML binding sample for it.

**Comment by NickIliev** [comment]
PR[https://github.com/NativeScript/docs/pull/454](https://github.com/NativeScript/docs/pull/454)
