### ISSUE TITLE
Broken link in ListView documentation

### ISSUE THREAD

**Issue by marciovicente** [NativeScript/docs-v7#474]
http://docs.nativescript.org/ui/components#listview

![screen shot 2016-08-11 at 11 42 08 pm](https://cloud.githubusercontent.com/assets/1021901/17611412/637ddc8c-601d-11e6-8916-a5cf2aa49f03.png)

![image](https://cloud.githubusercontent.com/assets/1021901/17611415/6a766932-601d-11e6-9555-6d9e1969ce1d.png)

**Comment by tjvantoll** [comment]
Thanks @marciovicente!
