### ISSUE TITLE
Tutorial App segfault on iOS when using Http in UserService 

### ISSUE THREAD

**Issue by ghost** [NativeScript/docs-v7#483]
Hi,

I'm following the tutorial on iOS and when reaching the end of 3.4 Services, I get a segfault:

> Aug 25 21:06:33 Brieucs-MBP sampleGroceries[59400]: 1   0x1013a3c67 -[TNSRuntime executeModule:]
> Aug 25 21:06:33 Brieucs-MBP sampleGroceries[59400]: 2   0x100fd8702 main
> Aug 25 21:06:33 Brieucs-MBP sampleGroceries[59400]: 3   0x10447d145 start
> Aug 25 21:06:33 Brieucs-MBP sampleGroceries[59400]: file:///app/tns_modules/nativescript-angular/file-system/ns-file-system.js:11:30: JS ERROR ReferenceError: Can't find variable: __decorate
> Aug 25 21:06:33 Brieucs-MBP com.apple.CoreSimulator.SimDevice.B319AC3F-E5AA-4D18-8EBC-2B408BD6E61F.launchd_sim[58649](UIKitApplication:org.nativescript.groceries[0x4e33][59400]): Service exited due to signal: Segmentation fault: 11

When I check out the branch angular-end, everything works like a charm, so I'm a little confuse. I reverted back to the a step where the app was working and followed again the instructions to add the UserService using Http but I can't get it to work... 

Has anyone add the same issue ? Is there an obvious thing I'm missing ? 

thanks for your help.

PS: here my package.json for info

> {
>   "name": "Groceries",
>   "version": "1.0.0",
>   "description": "A NativeScript-built iOS and Android app for managing grocery lists",
>   "repository": {
>     "type": "git",
>     "url": "https://github.com/nativescript/sample-Groceries.git"
>   },
>   "keywords": [
>     "NativeScript"
>   ],
>   "author": "TJ VanToll tj.vantoll@gmail.com (http://tjvantoll.com/)",
>   "license": "MIT",
>   "bugs": {
>     "url": "https://github.com/nativescript/sample-Groceries/issues"
>   },
>   "homepage": "https://github.com/nativescript/sample-Groceries/groceries",
>   "nativescript": {
>     "id": "org.nativescript.groceries",
>     "tns-ios": {
>       "version": "2.2.1"
>     },
>     "tns-android": {
>       "version": "2.2.0"
>     }
>   },
>   "dependencies": {
>     "@angular/common": "2.0.0-rc.4",
>     "@angular/compiler": "2.0.0-rc.4",
>     "@angular/core": "2.0.0-rc.4",
>     "@angular/http": "2.0.0-rc.4",
>     "@angular/platform-browser": "2.0.0-rc.4",
>     "@angular/platform-browser-dynamic": "2.0.0-rc.4",
>     "@angular/platform-server": "2.0.0-rc.4",
>     "@angular/router": "3.0.0-beta.2",
>     "nativescript-angular": "0.3.1",
>     "rxjs": "5.0.0-beta.6",
>     "tns-core-modules": "2.2.1"
>   },
>   "devDependencies": {
>     "babel-traverse": "6.7.6",
>     "babel-types": "6.7.7",
>     "babylon": "6.7.0",
>     "filewalker": "0.1.2",
>     "lazy": "1.0.11",
>     "nativescript-dev-typescript": "^0.3.2",
>     "typescript": "^1.8.10"
>   }
> }

**Comment by jonathanvivero** [comment]
Hi, applequist.
I had the same problem. I fixed with this: In file main.ts, I put the line

import {nativeScriptBootstrap} from "nativescript-angular/application"; 
the first one, and everything working again ;D

**Comment by tjvantoll** [comment]
Thanks @applequist and @jonathanvivero.

I unfortunately broke this when I updated the tutorial to Angular RC 4 and NativeScript 2.2. @jonathanvivero is correct, `nativeScriptBootstrap` needs to be imported first, and I just pushed up a commit to fix that.

Sorry you ran into problems here. I’ll try to not screw up when I update this tutorial to yet another Angular RC release next week.
