### ISSUE TITLE
Breaking changes hasn't been updated since 1.6

### ISSUE THREAD

**Issue by lawrencetaur** [NativeScript/docs-v7#485]
https://docs.nativescript.org/releases/breaking-changes 

Would be useful for newcomers to see what breaking changes are.

**Comment by tjvantoll** [comment]
Hey @lawrencetaur,

Thanks for pointing this out. We’re chatting about how to update this page. For now you should be able to find the information you need in our changelogs (for example https://docs.nativescript.org/releases/Cross-Platform%20Modules).

**Comment by etabakov** [comment]
The page has been updated in ##1433 with the latest changes in 5.0 and we added additional step in the release checklist for documenting the breaking changes so that we don't forget it.
