### ISSUE TITLE
Broken links in ng-chapter-2.md#22-starting-up

### ISSUE THREAD

**Issue by fdnhkj** [NativeScript/docs-v7#491]
In [ng-chapter-2.md#22-starting-up](https://github.com/NativeScript/docs/blob/production/tutorial/ng-chapter-2.md#22-starting-up), links to _Angular 2’s own bootstrap() function_ and to _application.ts file_ are broken.

**Comment by tjvantoll** [comment]
Ah, gotta love Angular removing APIs at a whim 😄 

When I upgrade the guide to Angular RC 6 next week this whole section will change a bit, so for now I’ll just remove the link to avoid confusing people.

Thanks for reporting this @fdnhkj!
