### ISSUE TITLE
Add more info on Signing iOS

### ISSUE THREAD

**Issue by pkoleva** [NativeScript/docs-v7#516]
A lot of people get confused with Apple's way of deploying apps on devices, so we can borrow some content from the article [here](http://docs.telerik.com/platform/appmanager/appmanager-portal/managing-apps/publishing-apps/publishing-ios-apps/resigning-ios-apps#code-signing-ios-apps) and explain what do you need to be able to deploy on yours and other devices.

**Comment by NickIliev** [comment]
After a discussion, we have agreed that the Code signing process is too specific for the different platforms and very well covered in the Apple resources which are included as links in [this article](https://docs.nativescript.org/publishing/publishing-ios-apps#certificates-identifiers--profiles).

Currently, no new article is needed - will re-open this issue if this is considered as need-to.
