### ISSUE TITLE
Missing content + extend docs

### ISSUE THREAD

**Issue by Plamen5kov** [NativeScript/docs-v7#518]
Missing content on [how to create a webview](https://docs.nativescript.org/cookbook/ui/web-view) + using it with XML. Also the content can be contributed to.

**Comment by tsonevn** [comment]
The docs has been fixed and the example, how to use WebView with XML, is available [https://docs.nativescript.org/cookbook/ui/web-view#declaring-a-webview](https://docs.nativescript.org/cookbook/ui/web-view#declaring-a-webview)
