### ISSUE TITLE
Sample Apps - broken links

### ISSUE THREAD

**Issue by leocaseiro** [NativeScript/docs-v7#522]
The page http://docs.nativescript.org/start/samples is full of examples that don't exist anymore.

Such as: 
1. Tasks
2. Friends
3. Expensity

**Comment by valentinstoychev** [comment]
Hey Leo - thanks! How did you get to that page?

**Comment by leocaseiro** [comment]
Maybe Google? I'm not sure, honestly

**Comment by tjvantoll** [comment]
Thanks @leocaseiro. That page was deprecated in favor of https://www.nativescript.org/app-samples-with-code, but it seems we never got rid of it. Oops 😄  

It’s gone now—or it will be when Jekyll finishes doing its thing. Thanks again!

**Comment by leocaseiro** [comment]
No worries!

Thanks @tjvantoll.
