### ISSUE TITLE
New Camera plugin documentation

### ISSUE THREAD

**Issue by 3rror404** [NativeScript/docs-v7#530]
Hi all,

could we please get some documentation for the new [nativescript-camera](https://github.com/NativeScript/nativescript-camera) plugin?

I'd also love to see an example combining the camera plugin and the [nativescript-background-http](https://github.com/NativeScript/nativescript-background-http) plugin to upload an image direct from the devices camera.

**Comment by valentinstoychev** [comment]
This will be a great addition to the code samples too. @zh-m, do you think?

**Comment by 3rror404** [comment]
It would also be great if the documentation covered saving the image to the file system. I've wasted quite a bit of time today with [this issue](https://github.com/NativeScript/NativeScript/issues/2871) as the current documentation doesn't actually mention the type returned by the camera module.

**Comment by NickIliev** [comment]
@3rror404, @valentinstoychev 
The article for the nativescript-camera plugin is ready with this [PR](https://github.com/NativeScript/docs/pull/546) - need revision and upvote.

Article is also added as PR [at the plugin README](https://github.com/NativeScript/nativescript-camera/pull/21)

Also, new examples are added to nativescript-sdk-examples-ng for [working with the new camera plugin](https://github.com/NativeScript/nativescript-sdk-examples-ng/tree/master/app/camera)
