### ISSUE TITLE
Web Worker Clarification

### ISSUE THREAD

**Issue by 9thwall** [NativeScript/docs-v7#548]
Can you please update the documentation on web workers with more live examples?
I tried running the examples currently on there but I'm getting "work is undefined". 
I'm using {N} with Angular2.

**Comment by petekanev** [comment]
@9thwall Hey, the multithreading article is up earlier on the documentation website than the actual release when Workers are introduced (2.4) so people know what to anticipate. The worker functionality is up in both preview channels for the android and ios runtimes. 

If you don't want to wait till the 2.4 release to try them out you can use the latest runtimes by using `tns platform remove && tns platform add <android>/<ios>@next`

Also you can check out a `live example` when you fetch -> https://github.com/NativeScript/demo-workers and install the latest runtimes, and simply run the app.

**Comment by 9thwall** [comment]
Sweet! Thank you for the info.
I will check it out.
