### ISSUE TITLE
Please fix your search box

### ISSUE THREAD

**Issue by 9thwall** [NativeScript/docs-v7#550]
Hi,
I know this is such a tiny thing but can you guys PLEASE fix this css issue. 
As a web designer / developer it makes me cringe each time I see it and read your docs. It's so ugly!

![fix this](https://cloud.githubusercontent.com/assets/1660992/19949923/bc682e12-a111-11e6-9aaf-aab4e89d85d7.jpg)

**Comment by tjvantoll** [comment]
Hey @9thwall,

We just massively updated our design, including the search. Hopefully they’re not so ugly now 😄
