### ISSUE TITLE
Documentation needed for tns-platform-declarations

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/docs-v7#558]
_From @NathanWalker on November 6, 2016 23:15_

I personally have struggled getting a tsconfig to work with `tns-platform-declarations` since day 1. I just tried using the `next` tag of these declarations to see if things have improved, but same issues. Sometimes I can get it to work, othertimes it's purely a guessing game of type definitions and it's just highly frustrating.

Here's a tsconfig that I hope would work:
```
{
    "compilerOptions": {
        "target": "es5",
        "module": "commonjs",
        "declaration": true,
        "removeComments": true,
        "noLib": false,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "lib": [
            "es2016"
        ],
        "sourceMap": true,
        "pretty": true,
        "allowUnreachableCode": false,
        "allowUnusedLabels": false,
        "noEmitHelpers": true,
        "noEmitOnError": false,
        "noImplicitAny": false,
        "noImplicitReturns": true,
        "noImplicitUseStrict": false,
        "noFallthroughCasesInSwitch": true,
        "typeRoots": [
            "./node_modules/@types",
            "./node_modules"
        ]
    },
    "exclude": [
        "demo",
        "node_modules"
    ],
    "compileOnSave": false
}
```

However this sadly results in these annoying errors:
```
 declare var AudioBuffer: interop.StructType<AudioBuffer>;
              ~~~~~~~~~~~

node_modules/tns-platform-declarations/ios/objc-i386/objc!CoreAudio.d.ts(7,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'AudioBuffer' must be of type '{ new (): AudioBuffer; prototype: AudioBuffer; }', but here has type 'StructType<AudioBuffer>'.


4954 declare class UIEvent extends NSObject {
                   ~~~~~~~

node_modules/tns-platform-declarations/ios/objc-i386/objc!UIKit.d.ts(4954,15): error TS2300: Duplicate identifier 'UIEvent'.


4954 declare class UIEvent extends NSObject {
                   ~~~~~~~

node_modules/tns-platform-declarations/ios/objc-i386/objc!UIKit.d.ts(4954,15): error TS2417: Class static side 'typeof UIEvent' incorrectly extends base class static side 'typeof NSObject'.
  Types of property 'alloc' are incompatible.
    Type '() => UIEvent' is not assignable to type '() => NSObject'.
      Type 'UIEvent' is not assignable to type 'NSObject'.
        Property 'accessibilityActivationPoint' is missing in type 'UIEvent'.


15879 interface UIEvent extends Event {
                ~~~~~~~

node_modules/typescript/lib/lib.d.ts(15879,11): error TS2300: Duplicate identifier 'UIEvent'.


15885 declare var UIEvent: {
                  ~~~~~~~

node_modules/typescript/lib/lib.d.ts(15885,13): error TS2300: Duplicate identifier 'UIEvent'.
```

Using a `references.d.ts` file like this:
```
/// <reference path="./node_modules/tns-core-modules/tns-core-modules.d.ts" />
/// <reference path="./node_modules/typescript/lib/lib.d.ts" />
/// <reference path="./node_modules/tns-platform-declarations/android.d.ts" />
/// <reference path="./node_modules/tns-platform-declarations/ios.d.ts" />
```

What is the suggested setup to use them and could this be blatantly obvious in the docs somewhere? Please help. Can bleed no longer. 

_Copied from original issue: NativeScript/NativeScript#3033_

**Comment by NickIliev** [comment]
Hey @NathanWalker 

You can refer to the [README file ](https://github.com/NativeScript/NativeScript/tree/master/tns-platform-declarations)of tns-platform-declarations.

Notice that this workflow will require tns-core-modules from master branch (at this moment @next)

**Comment by onury** [comment]
I get the same errors even after following the README file.

**Comment by NathanWalker** [comment]
Just wanted to follow up here and say the latest 2.5.0 and this example project solved everything with declarations setup: https://github.com/NativeScript/nativescript-sdk-examples-ng
Brilliant and thank you!!

**Comment by NickIliev** [comment]
Hey @onury, @NathanWalker 

With NativeScript 3.0.0 you can install the tns-platform-declarations without having to cast extra variables in references.d.ts. Meaning that you have to follow [these instructions](https://www.npmjs.com/package/tns-platform-declarations) to enable the declarations n both non-Angular and Angular enabled projects.

You can always use [nativescript-sdk-examples-ng application](https://github.com/NativeScript/nativescript-sdk-examples-ng) as a reference for an application working with tns-platform-declarations.

Closing as resolved via [https://github.com/NativeScript/docs/pull/755](https://github.com/NativeScript/docs/pull/755)
