### ISSUE TITLE
Logo glitches in tutorial

### ISSUE THREAD

**Issue by astorije** [NativeScript/docs-v7#569]
When browsing http://docs.nativescript.org/angular/tutorial/ng-chapter-0, I noticed these:

<img width="280" src="https://cloud.githubusercontent.com/assets/113730/20370507/15d807da-ac2d-11e6-81e5-f4682bb8c09f.png"> <img width="350" src="https://cloud.githubusercontent.com/assets/113730/20370508/15db4058-ac2d-11e6-8154-5daba258bdef.png">

I would try to fix these myself, but I must be blind as I was not able to find where this markup lives in the repo...

**Comment by tjvantoll** [comment]
Thanks @astorije! We pushed out some changes earlier today that should resolve this. Let us know if you’re still having this problem.

**Comment by astorije** [comment]
All good now, good job!
