### ISSUE TITLE
Broken links in README.md

### ISSUE THREAD

**Issue by tjvantoll** [NativeScript/docs-v7#57]
The iOS- and Android-specific links at the bottom of index.md are broken. I'd fix them but I'm not sure where they should link to.

**Comment by adityasaxena** [comment]
I guess - to GitHub equivalents of http://docs.nativescript.org/runtimes/android/overview and http://docs.nativescript.org/runtimes/ios/Overview

**Comment by tjvantoll** [comment]
This was fixed by 650ec48babddf96ad9266197d60ed8c10fc414b5.
