### ISSUE TITLE
location module is no more

### ISSUE THREAD

**Issue by pelegri** [NativeScript/docs-v7#576]
The location module is no longer available - it new needs to be loaded from npm at https://www.npmjs.com/package/nativescript-geolocation - but there are still references to it in the documentation.

Example, at the end of Chapter 4 (http://docs.nativescript.org/angular/tutorial/ng-chapter-4):
>>
TIP: There are several modules that come out of the box with your NativeScript installation that we did not have time to cover in this guide—including a location service, a file-system helper, a timer module, a camera module, and a whole lot more. Make sure to peruse the “Modules API” of the NativeScript documentation, or just look around your node_modules/tns-core-modules folder to see all of what’s available.
>>

**Comment by tjvantoll** [comment]
Thanks @pelegri!

Fixed with 86d7c8085e4dc02e6833bd57927cbfd5c5cf3c22 and a2e2fd5e90bfda0eb056859615f8cb0b4261766b.
