### ISSUE TITLE
New docs need some screen shot examples

### ISSUE THREAD

**Issue by 9thwall** [NativeScript/docs-v7#577]
Hi, thank you for updating the docs!
I love how there are many more code examples to help the learning process. I'm just still confused why there aren't any screen shot examples for many of the codes. Example: [ListView](https://docs.nativescript.org/angular/code-samples/common-screens/listview.html). Wouldn't it make it a lot easier for people to see what the result of code would look like so they don't have to copy / paste, run livesync each one? Just my 2cents.. Regardless, thank you for all the additions. It's been very helpful.

**Comment by kazemihabib** [comment]
yes,and it's event better to use emulators like 
https://appetize.io/
https://www.manymo.com/
to show the result of code on an emulator

**Comment by NickIliev** [comment]
Closing the issue as currently the new examples are also linked to [a Playground demo](https://play.nativescript.org/)
