### ISSUE TITLE
More complete XML schema definition is needed

### ISSUE THREAD

**Issue by kdubious** [NativeScript/docs-v7#59]
The UI components are lacking definitions for the XML properties that are available. For example, what attributes are valid for the `Image` tag?

**Comment by froyke** [comment]
+1
This could support advanced CI / automated builds use-cases (validating the view's xml against the schema)

**Comment by ayongw** [comment]
+1 this is needed in 3rd party IDE

**Comment by enchev** [comment]
Already avaliable https://www.npmjs.com/package/tns-core-modules-xsd-schema
