### ISSUE TITLE
TextField code-samples article returns 404

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/docs-v7#592]
_From @dogabudak on November 23, 2016 11:23_

Although it referenced quite frequently , http://docs.nativescript.org/angular/code-samples/text-field link gives 404 error, is it possible that can you fix it or reference something else ? 

_Copied from original issue: NativeScript/NativeScript#3158_

**Comment by NickIliev** [comment]
Hey @dlgabudak can you tell us from where you are getting this reference.

We have updated our documentation and the updated link for TextField in angular section is [https://docs.nativescript.org/angular/code-samples/ui/text-field.html](https://docs.nativescript.org/angular/code-samples/ui/text-field.html)

**Comment by dogabudak** [comment]
Hey  Nick
I saw that link while i was using search button at https://docs.nativescript.org . I wrote collapse on the search field and that link was there.
 Thanks for quick update

**Comment by tjvantoll** [comment]
Just as an update I still see the broken link @dogabudak refers to if I do a search for “text field” today.

**Comment by dogabudak** [comment]
Also at this link here :> [https://www.nativescript.org/blog/using-device-local-settings-with-nativescript]  there  'application-settings module' link is directing me to an empty page

**Comment by robcaa** [comment]
Textfield and Button code sample link is broken in Chapter 2, in the Tip box:

> TIP:
> The code samples portion of the NativeScript documentation is a great place to find copy-and-paste friendly examples of the various NativeScript UI components. The **TextField** and **Button** code sample pages are great places to get started.

Link:
http://docs.nativescript.org/angular/tutorial/ng-chapter-2

**Comment by kazemihabib** [comment]
links here https://docs.nativescript.org/api-reference/classes/_ui_text_field_.textfield.html#borderwidth
are broken too.
like https://docs.nativescript.org/api-reference/enums/ReturnKeyType/README.md

**Comment by NickIliev** [comment]
Thanks all for noticing the broken links. The links from the search engine for TextField are now all operational. So is the link for [ReturnKeyType](http://docs.nativescript.org/api-reference/modules/_ui_enums_.returnkeytype.html)
