### ISSUE TITLE
Request: add a chapter for SideDrawer

### ISSUE THREAD

**Issue by realtebo** [NativeScript/docs-v7#602]
One the most common developer dream is to implement a side drawer. I, too, have this dream.

I really am NOT able to understand what plugin name add to the tutorial project, and HOW to add a side drawer to the list page.

Please, please, please....

**Comment by valentinstoychev** [comment]
Here is a sample that explains everything about using SideDrawer in NativeScript - https://github.com/telerik/nativescript-ui-samples/blob/release/sdk/app/sidedrawer/getting-started/getting-started.xml

**Comment by realtebo** [comment]
For a newbie (like me) there are too many things to do for the first time to be able to understand all of them from an uncommented example.

**1. Add the plugin in the right way**

We cannot use npm but instead we must use

    tns plugin add nativescript-telerik-ui 

becase there add some os-specif task to do apart the simple plugin installation. 

After that I think it's absolutely needed to do 

    tns platform remove android
    tns platform add android

**2. Do the right import** 

This step in absolutely undocumented. 

    import { RadSideDrawer } from "nativescript-telerik-ui/sidedrawer";

**3. How to access to the chield view from inside our app component**

Actually I use this way:

    @ViewChild(RadSideDrawer) public drawerComponent: RadSideDrawer;

Note: This require to import `ViewChild` from `@angular/core` 

**4. What to insert in the template file**

This _should_ be a valid html template. _Please note that you linked me an `.xml` file_ and I have no idea on how to use an XML with {N}+ng2 !

```
<RadSideDrawer tkExampleTitle tkToggleNavButton>
    <StackLayout tkDrawerContent class="sideStackLayout">
        <StackLayout class="sideTitleStackLayout">
            <Label text="Navigation Menu"></Label>
        </StackLayout>
        <StackLayout class="sideStackLayout">
            <Label text="Primary" class="sideLabel sideLightGrayLabel"></Label>
            <Label text="Social" class="sideLabel"></Label>
            <Label text="Promotions" class="sideLabel"></Label>
            <Label text="Labels" class="sideLabel sideLightGrayLabel"></Label>
            <Label text="Important" class="sideLabel"></Label>
            <Label text="Starred" class="sideLabel"></Label>
            <Label text="Sent Mail" class="sideLabel"></Label>
            <Label text="Drafts" class="sideLabel"></Label>
        </StackLayout>
    </StackLayout>
    <StackLayout >
        <Label [text]="mainContentText" textWrap="true" class="drawerContentText"></Label>
        <Button text="OPEN DRAWER" (tap)="openDrawer($event)"></Button>
    </StackLayout>
</RadSideDrawer>
```


**5. How to open the drawer programmatically**

How you can see I add a button and an event

    <Button text="OPEN DRAWER" (tap)="openDrawer($event)"></Button>

In my component I use this code to react to the event

    openDrawer( event: any) : void {

    	console.log ("you clicked open !");
    	console.log (event);
    }

And i stopped here.

**First problem**: 

When I run the app 

    tns build android

The visual results is really ugly, the (supposed) hidden content of side bar is showed under the main content

**Second problem**: 

I cannot open the drawer, I've tried

    this.drawerComponent.showDrawer();

But this throws a runtime exception, telling me that javascript is unable to execute the on click event. 
I have NO idea of what is the problem, because replacing the previous line with a `console.log()` simply works and so ... I'm in the mobile sands.

This is the reason because I really need a tutorial for {N}+ng2 newbies to help me to use the SideDrawer.

**Comment by realtebo** [comment]
I tried another way. In my app.module.ts 

    import { RadSideDrawerComponent } from "nativescript-telerik-ui/sidedrawer/angular";

This is my component 
```

import { Component, ViewChild} from "@angular/core";

import { RadSideDrawerComponent } from "nativescript-telerik-ui/sidedrawer/angular";

@Component({
  selector: "third",
  templateUrl: "pages/third/third.html",
})
export class ThirdComponent {

	@ViewChild(RadSideDrawerComponent) public drawerComponent: RadSideDrawerComponent;
	mainContentText : string = "This is the main text";

    openDrawer( event: any) : void {

    	console.log (" you clicked open");
    	console.log (event);

    	this.drawerComponent.sideDrawer.showDrawer();
    }

}
```

and this is `third.html` template file

```
<RadSideDrawer tkExampleTitle tkToggleNavButton>
    <StackLayout tkDrawerContent class="sideStackLayout">
        <StackLayout class="sideTitleStackLayout">
            <Label text="Navigation Menu"></Label>
        </StackLayout>
        <StackLayout class="sideStackLayout">
            <Label text="Primary" class="sideLabel sideLightGrayLabel"></Label>
            <Label text="Social" class="sideLabel"></Label>
            <Label text="Promotions" class="sideLabel"></Label>
            <Label text="Labels" class="sideLabel sideLightGrayLabel"></Label>
            <Label text="Important" class="sideLabel"></Label>
            <Label text="Starred" class="sideLabel"></Label>
            <Label text="Sent Mail" class="sideLabel"></Label>
            <Label text="Drafts" class="sideLabel"></Label>
        </StackLayout>
    </StackLayout>
    <StackLayout >
        <Label [text]="mainContentText" textWrap="true" class="drawerContentText"></Label>
        <Button text="OPEN DRAWER" (tap)="openDrawer($event)"></Button>
    </StackLayout>
</RadSideDrawer>
```


Now the page is simply blank, nothing drawn. I'm really discouraged

**Comment by NickIliev** [comment]
Hey @realtebo 

I would recommend using [this article](http://docs.telerik.com/devtools/nativescript-ui/Controls/Angular/SideDrawer/getting-started) and in the same time [clone and run this sample application](https://github.com/telerik/nativescript-ui-samples-angular) (used in the same article mentioned).

This way you can see the actual implementation in progress and understand better the steps described in the official documentation.

For example, in the [getting started section ](https://github.com/telerik/nativescript-ui-samples-angular/blob/release/sdkAngular/app/sidedrawer/getting-started/getting-started.component.ts)a basic usage of **showDrawer** method is demonstrated. What you should consider is that the **_drawerComponent_** is initialized in **_ngAfterViewInit_** (in other examples you can see the same action in **_ngOnInit_**) which are specific [lifecycle hooks](https://angular.io/docs/ts/latest/guide/lifecycle-hooks.html) in Angular-2 application.

**Comment by realtebo** [comment]
thanks for the links. I'll study.

Be patient, understand that [this page](http://docs.telerik.com/devtools/nativescript-ui/Controls/Angular/SideDrawer/getting-started) is aboslutely useless for a newbie. No info about imports on module and on component, no info about available methods, and so on. More info is available on api pages, but here there are NO example (because it's an API ref, yes....)

Anyway, a code sample in the main website, under Nativescript with angular will be very usefull

**Comment by NickIliev** [comment]
Hey @realtebo the only reason this is not in the official documentation is because it is a control that comes from a plugin, which already has a documentation on its own. Of course, if you need assistance do not hesitate to contact me or the guys from nativescript-telerik-ui. [Here ](https://github.com/telerik/nativescript-ui-feedback/issues)you can leave feedback or make suggestions for improvements related to nativescript-telerik-ui plugin.
