### ISSUE TITLE
Broken link to github repo

### ISSUE THREAD

**Issue by realtebo** [NativeScript/docs-v7#608]
I'm not able to identify the most correct repository where to open this issue, so I open here.

I'm referring to this page: https://www.nativescript.org/app-samples-with-code 

When speaking about Groceries, you point the user to "another that uses Firebase as a backend."

This links to: https://github.com/nativescript/sample-groceries/tree/angular-firebase

That is non-existing (at now)

**Comment by tjvantoll** [comment]
Thanks @realtebo! We’ve removed the link for now.  Long term we plan on bringing the Firebase functionality back, but we need some time to do some updates and such. The code still lives on in my fork of Groceries if you’re curious: https://github.com/tjvantoll/sample-Groceries/tree/angular-firebase.
