### ISSUE TITLE
 improve docs for Two-way binding w/ NativeScriptFormsModule

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/docs-v7#630]
_From @SamuelGRwebfab on December 16, 2016 17:31_

I noticed this page of the docs is incorrect https://docs.nativescript.org/angular/cookbook/tab-view-ng.html#binding-two-way-tabview-selectedindex

using `[(ngModel)]="tabSelectedIndex"` throws an error and crashes the app, what needs to be done is this `[selectedIndex]="tabSelectedIndex"`

just a small change, didn't notice anything else wrong. 

_Copied from original issue: NativeScript/NativeScript#3307_

**Comment by ButterMeWaffle** [comment]
@NickIliev hey sorry for posting it in the wrong spot. Thanks for moving it for me!

**Comment by NickIliev** [comment]
Hey @SamuelGRwebfab 

The tab view should work with ngModel as expected as there are some scenarios where you would want two-way binding. However, in order for ngModel to work, you will have to import **NativeScriptFormsModule** in your ngModel imports

Full example [here](https://github.com/NativeScript/nativescript-sdk-examples-ng/blob/dabe29034e26cf3a6f329fd4b52d6ece76b23d47/app/color/color-examples.module.ts#L28)

```
import { NativeScriptFormsModule } from "nativescript-angular/forms";
...
@NgModule({
    imports: [
        ...
        NativeScriptFormsModule,
        ...
    ],
})

```

**Comment by ButterMeWaffle** [comment]
@NickIliev oh I see, could we have this added to the docs? I dont rememeber seeing that in there

**Comment by NickIliev** [comment]
It is mentioned indirectly [here](https://docs.nativescript.org/core-concepts/angular-bootstrap#customizing-di-providers) and in the tutorial for the part of two-way binding in the middle of this chapter [here](https://docs.nativescript.org/tutorial/ng-chapter-3) but you are absolutely right - we should update the data binding section of the documentation.

**Comment by ButterMeWaffle** [comment]
I appreciate it @NickIliev !!

**Comment by NickIliev** [comment]
Article containing good descript on NativeScriptFormsModule usage can be found [here](https://docs.nativescript.org/core-concepts/angular-data-binding#data-binding)
