### ISSUE TITLE
How do you get access to the frame?

### ISSUE THREAD

**Issue by alexprice1** [NativeScript/docs-v7#64]
var frameModule = require("ui/frame");
console.log(frameModule.topmost())

This always returns undefined?

**Comment by devangpaliwal** [comment]
Same for me. Any suggestions ?

**Comment by devangpaliwal** [comment]
Got the solution.
You should write this code "frameModule.topmost()" in the any eventHandler code.

For example: 
exports.onTapHandler = function(args){
  console.log(frameModule.topmost());
}

Doing this  --
var frameModule = require("ui/frame");
console.log(frameModule.topmost())

will print undefined to the console.

**Comment by ikoevska** [comment]
I am not sure whether this issue is for the documentation. We can note this behavior in the behavior but if you consider it a bug, you should probably duplicate the issue at https://github.com/NativeScript/NativeScript

**Comment by N3ll** [comment]
This issue was moved to NativeScript/NativeScript#1225
