### ISSUE TITLE
<ActionItem (tab)... crashing - ngTutorial share plugin example

### ISSUE THREAD

**Issue by mrsoto** [NativeScript/docs-v7#641]
Hello,
   I've a crash when share event is activated in the iOS emulator for  angular tutorial Chapter 5. As far as I understand I've applied all changes (the demo doesn't show expected source).

My source:

    <ActionBar title="Groceries">
      <ActionItem text="Share" 
      (tap)="share()" 
      android.systemIcon="ic_menu_share_holo_dark"   ios.systemIcon="9"  ios.position="right">
     </ActionItem>
    </ActionBar>
    <GridLayout rows="auto, *">
   ...

    @Component({
        selector: "list",
        templateUrl: "pages/list/list.html",
        styleUrls: ["pages/list/list-common.css", "pages/list/list.css"],
        providers: [GroceryListService]
    })
    export class ListComponent implements OnInit {
    ...
        share() {
            let listString = this.groceryList
                .map(grocery => grocery.name)
                .join(", ").trim();
 
            SocialShare.shareText(listString);
        }

Just after share is touched this error appear:

1   0x10a04aa6b NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
2   0x10a7ca90e ffi_closure_unix64_inner
Dec 30 23:44:22 mbp01 mysampleGroceries[83423]: 3   0x10a7cb2c2 ffi_closure_unix64
4   0x10b7f44a1 -[UIBarButtonItem(UIInternal) _sendAction:withEvent:]
5   0x10b3b28bc -[UIApplication sendAction:to:from:forEvent:]
6   0x10b538c38 -[UIControl sendAction:to:forEvent:]
Dec 30 23:44:22 mbp01 mysampleGroceries[83423]: 7   0x10b538f51 -[UIControl _sendActionsForEvents:withEvent:]
8   0x10b5390db -[UIControl _sendActionsForEvents:withEvent:]
9   0x10b537e4d -[UIControl touchesEnded:withEvent:]
10  0x10b420545 -[UIWindow _sendTouchesForEvent:]
11  0x10b421c33 -[UIWindow sendEvent:]
12  0x10b3ce9ab -[UIApplication sendEvent:]
13  0x10bbbb72d __dispatchPreprocessedEventFromEventQueue
14  0x10bbb4463 __handleEventQueue
15  0x10db39761 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
16  0x10db1e98c __CFRunLoopDoSources0
17  0x10db1de76 __CFRunLoopRun
18  0x10db1d884 CFRunLoopRunSpecific
19  0x10fa86a6f GSEventRunModal
20  0x10b3b0c68 UIApplicationMain
21  0x10a7cb11d ffi_call_unix64
22  0x12a138480
file:///app/tns_modules/@angular/core/bundles/core.umd.js:9427:77: JS ERROR Error: Error in pages/list/list.html:2:4 caused by: self.context.share is not a function. (In 'self.context.share()', 'self.context.share' is undefined)
Dec 30 23:44:22 mbp01 com.apple.CoreSimulator.SimDevice.87FC9103-AA60-4B88-9DF6-6376B728DB72.launchd_sim[83330] (UIKitApplication:org.nativescript.groceries[0xd099][83423]): Service exited due to Segmentation fault: 11

I saw https://github.com/NativeScript/sample-Groceries but this sample project did not use any more ActionBar

Did the ActionBar was replaced by <GridLayout  class="action-bar-custom"> ?

**Comment by NickIliev** [comment]
@mrsoto you can switch to angular-end branch and look at the final code of sample-Groceries tutorial. The action bar with the share button is implemented there and you can diff check it with your implementation.
