### ISSUE TITLE
Documentation could be optimized

### ISSUE THREAD

**Issue by Steviey** [NativeScript/docs-v7#646]
Please provide file names for every code snipped in: 
https://docs.nativescript.org/core-concepts/angular-navigation
Be consistent. If possible sum it up with a complete code sample as Microsoft it does.
This would help a lot.

**Comment by tsonevn** [comment]
Hi @Steviey,
Could you provide some info about the need of including the file names for the code snippets in this article?
For further help, you could use review [nativescript-sdk-examples-ng](https://github.com/NativeScript/nativescript-sdk-examples-ng/), which has been created to show some basic scenario, while using NativeScript components.

Regards,
@tsonevn

**Comment by NickIliev** [comment]
@Steviey you can use the markdown table to get links to the respective article sections (and from there to the included snippets)
