### ISSUE TITLE
Please have an english language team member edit the documentation. I find it very difficult to understand many of the concepts with so many misused words and poorly constructed sentences.

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/docs-v7#652]
_From @nhrones on January 16, 2017 21:10_

Dear friend, we, the rest of the NativeScript community really
appreciate your feedback! While we are doing all we can to take care of every
issue, sometimes we get overwhelmed. Because of that, we will consider issues
that are not constructive or problems that cannot be reproduced "dead".
Additionally, we will treat feature requests or bug reports with unanswered
questions regarding the behavior/reproduction for more than 20 days "dead". All
"dead" issues will get closed.

### Tell us about the problem
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

### Which platform(s) does your issue occur on?
iOS/Android/Both

### Please provide the following version numbers that your issue occurs with:
- CLI: (run `tns --version` to fetch it)
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the
`package.json` file of your project)
- Plugin(s): (look for the version number in the `package.json` file of your
project)

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

_Copied from original issue: NativeScript/NativeScript#3500_

**Comment by tsonevn** [comment]
Hi @nhrones,

Could you provide some more info about the issues, which you are facing with the documentations? 
It would also help if you give us the exact articles you think, that should be edited?

Regarding to that at the end of every article, you will find  `Improve the article` button, which allows you to edit them.

Regards,
@tsonevn

**Comment by nhrones** [comment]
I would love to help.  I've tried the 'improve this article', but could not figure out how t use it. Could you point me to the documentation so that I may contribute?

**Comment by tsonevn** [comment]
Hi @nhrones,

when you click on `Improve this article` button, you will be redirect to the Github Markdown file, which contains the article. 
1. In the upper right corner of the file view, click 
![screenshot 30](https://cloud.githubusercontent.com/assets/17448734/22057263/9c617e2e-dd6c-11e6-8cad-edee72044cda.png)  to open the file editor. 
2. Make any changes you need to the file. 
3. Click on  `Propose file change` button.

For further info, how to editing files in another user's repository, review the instructions [here](https://help.github.com/articles/editing-files-in-another-user-s-repository/).

Hope this helps.

**Comment by nhrones** [comment]
Thank you.  As time permits, I'll propose edits and corrections to these
documents. I'm a fan of NativeScript and welcome the opportunity to
contribute.
