### ISSUE TITLE
http request

### ISSUE THREAD

**Issue by vishnurajoasys** [NativeScript/docs-v7#66]
<pre><code>mainViewModel.testButton = function () {
    var http = require("http");
 http.getJSON("http://httpbin.org/get").then(function (r) {
    alert(JSON.stringify(r))
}).fail(function (e) {
    // Argument (e) is Error!
    alert("Failed")
});
}</code></pre>

when i click on button application is getting crashed. I changed the button action to a string alert, it worked. So i made some mistakes in http request part it seems.

**Comment by ErjanGavalji** [comment]
@vishnurajoasys Could you please, sign the [Contribution License Agreement](http://www.nativescript.org/cla)

**Comment by ikoevska** [comment]
Hello, is this a documentation issue? If not, please, duplicate it at https://github.com/NativeScript/NativeScript If yes, would you, please, state the problem as it is unclear from your description.

Thanks!

**Comment by ErjanGavalji** [comment]
Closing the issue for it seems it is not a documentation contribution
