### ISSUE TITLE
6.1 frameModule is introduced without noting dependency requirement

### ISSUE THREAD

**Issue by dbvisel** [NativeScript/docs-v7#676]
In section 6.1, this code:

> if (page.ios) {
>     var navigationBar = frameModule.topmost().ios.controller.navigationBar;
>     navigationBar.barStyle = UIBarStyle.UIBarStyleBlack;
> }

requires the module `frameModule`, which isn't mentioned in the text. It should be noted that the user needs to add this:

> var frameModule = require("ui/frame");

to the top of _list.js_ to make it work correctly on iOS.

**Comment by NickIliev** [comment]
Hey @dbvisel the usage of different modules is widely covered through the different chapters and the first appearance of frameModule is in chapter 3 ([here](https://docs.nativescript.org/tutorial/chapter-3#32-navigating-screens)) so I think it si covered by the tutorial,
