### ISSUE TITLE
Update on Webview documentation needed

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/docs-v7#677]
_From @AndersGerner on February 15, 2017 7:1_

Hello NativeScript team.

I'm in the middel of creating an app with a webview and found your documentation here: https://docs.nativescript.org/cookbook/ui/web-view

I did not see a "Improve this article" on that page, so this is why I'm writing to you here.

I would like to suggest an improve in regards to the headlines. It says "Using WebView" on all 3 code examples, but it should be something like:
Using Webview with remote URL
Using Webview with local file
Using Webvies with raw HTML

This might make it easier for people to find the correct sample they need. 

Have a great day :)

//Anders Gerner 

_Copied from original issue: NativeScript/NativeScript#3639_

**Comment by NickIliev** [comment]
Hey @AndersGerner thnak you for you suggestions - as NativeScript is an open source project you can also join the contributors and improve our documentation with PRs in [https://github.com/NativeScript/docs](https://github.com/NativeScript/docs) - All pull request should be made against our master branch and once approved by other team members will be merged and published in the live documentation

**Comment by AndersGerner** [comment]
Hey @NickIliev, I would love to, and I actually spend some time, trying to figure out how, but even after your comment, I can't find the specific page about webview in the docs repo.

Maybe it' me who is blinded, but should it be under either "Cookbook" or "UI", which it's not :/ And I have tried to search, but can't find the heading "Using Webview" in the repo.

**Comment by NickIliev** [comment]
Hey, @AndersGerner - my bad for misleading you! I've just realized that you are talking about real examples from Cookbook section which are deployed from test applications анд то бе more specific in the case of the web-view example from [here](https://github.com/NativeScript/NativeScript/tree/17610daa9a182fd999efb7c5b69a983015801b17/tests/app/ui/web-view).
 I will take care of improving this example and improve the titles for each example given!

**Comment by AndersGerner** [comment]
No problem, @NickIliev ! :) Glad to get it corrected.
