### ISSUE TITLE
Typo: Missing "p" in cookbook dock-layout page

### ISSUE THREAD

**Issue by edenberger** [NativeScript/docs-v7#695]
I couldn't find [this page](
https://docs.nativescript.org/cookbook/ui/layouts/dock-layout) on the github docs -

`git clone https://github.com/NativeScript/docs.git `
` grep -R \ roperty docs`

It's missing a p in "Setting the dock property".

**Comment by NickIliev** [comment]
Resolved by [https://github.com/NativeScript/NativeScript/pull/3819](https://github.com/NativeScript/NativeScript/pull/3819)
