### ISSUE TITLE
ng-chapter-1 fault and question

### ISSUE THREAD

**Issue by krokofant** [NativeScript/docs-v7#710]
It states:

---
Find the line of code that declares an `<ActionBar>` (line 6 of your `app/app.component.ts` file). Remove that line’s final `>` character so that the line looks like this.

``` XML
<ActionBar title="My Apple" class="action-bar"
```
---
while after removing the text it really reads:
```
<ActionBar title="My Apple" class="action-bar"></ActionBar
```

I'm running on Android and the log seems cut of and does not at all match the one specified in the tutorial.

Ot only outputs the following in the Terminal:
```
04:45:19 - Compilation complete. Watching for file changes.

03-23 04:45:23.327  8120  8120 W System.err: 	at com.tns.Runtime.callJSMethodNative(Native Method)
03-23 04:45:23.327  8120  8120 W System.err: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1197)
03-23 04:45:23.327  8120  8120 W System.err: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:1061)
03-23 04:45:23.327  8120  8120 W System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1047)
03-23 04:45:23.327  8120  8120 W System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1028)
03-23 04:45:23.327  8120  8120 W System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1018)
```

while the exception logs:
[Exception.txt](https://github.com/NativeScript/docs/files/863587/Exception.txt)

and the logcat
[Log-2017-03-23-04-53-29.txt](https://github.com/NativeScript/docs/files/863580/Log-2017-03-23-04-53-29.txt)

**Comment by tjvantoll** [comment]
Hey @krokofant,

Thanks so much for reporting this. I went ahead and changed the tutorial with the suggestions that you recommended in 60d4baee68d991ec0d8197da28a037fb6f9a10da. The bug you hit is documented in https://github.com/NativeScript/nativescript-cli/issues/2603, so I added a note to the tutorial so (hopefully) others aren’t confused by this also.

Thanks again!
