### ISSUE TITLE
"Extend your existing iOS app with Angular 2 and NativeScript" article outdated info

### ISSUE THREAD

**Issue by georgij** [NativeScript/docs-v7#720]
I can't find TNSWidgets.framework and ./metadata-generation-build-step.

**Comment by NickIliev** [comment]
@georgij the article is outdated as in the current state NativeScript CLI is not bringing TNSWidgets.framweork to the **platforms** folder at all. In the current state this framework file is taken directly from the **node_modules** folder (as part of the tns-core-modules plugin it is located inside the folder of the plugin)

**Comment by radeva** [comment]
Closing since the article is updated and the issue is not relevant.
