### ISSUE TITLE
Imporive multithreading artice snippet fix

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/docs-v7#724]
Check if the snippets in [this article](https://docs.nativescript.org/angular/core-concepts/multithreading-model.html) needs to be fixed with references to **global** as discussed in  [https://github.com/NativeScript/NativeScript/issues/3786#issuecomment-286449083](https://github.com/NativeScript/NativeScript/issues/3786#issuecomment-286449083)

**Comment by tsonevn** [comment]
@Pip3r4o

**Comment by petekanev** [comment]
Addressed with PR https://github.com/NativeScript/docs/pull/732
