### ISSUE TITLE
[discussion] Restructuring of the docs

### ISSUE THREAD

**Issue by PetyaSotirova** [NativeScript/docs-v7#735]
_From @chrillewoodz on April 17, 2017 14:18_

I thought I'd create an issue to keep an open discussion about the docs, as they are horrible to navigate through as of today. I would recommend a big restructuring so you don't have to rip your teeth out every time you want to find something fast.

My proposed changes are:

- **Have the same structure in both the Core and the Angular docs**

- **Don't link to the NativeScript Core section in the Angular docs**
If I go to "User Interface" and then click on "Components" within the Angular docs it displays all the components you can use, however if I then click on a component it takes me to the Core docs. Which is useless if you're using angular. Instead you have to go to "code samples" and then "ui" and then "components" in order to know how to use it in Angular. This just doesn't make any sense.

- **Don't overcomplicate the examples**
Now if I go into a code sample for "ListView", you will get instantly confused. This is because you're dynamically creating the list, all for nothing really. Instead just show a simple array binding. Then you can have another example which shows how to create a ListView array dynamically. But don't assume that that's what everyone is going to do. Because it makes you think that you have to create the list that way, regardless if you already have a populated array from the database for example.

_I will add more things when I find the time to write more_

Please feel free to share your ideas so we can make the docs better. 

_Copied from original issue: NativeScript/nativescript-angular#754_

**Comment by PetyaSotirova** [comment]
Thank you for sharing your feedback @chrillewoodz. We're discussing some improvements to the information structure of the docs in the near future and the first two topics you raised are pain points for a lot of users that we are planning to address.
While I understand your point about simple examples, I'm not sure which samples for ListView you are referring to exactly so a link to the resource would be helpful. 
Also, if you are interested in helping us make the docs better, we do accept (and highly appreciate) pull requests.

**Comment by erjdriver** [comment]
The docs.nativescript.org page is messed up.

I'm trying to get to API REFERENCE and all I see is globals - no way to get to other classes.

**Comment by bathejasumeet** [comment]
@erjdriver  Same here.. :D all I can do right now is go through tns-core-modules source to hunt down the  APIs

**Comment by chrillewoodz** [comment]
One thing that is also missing is available attributes for a component. 

@PetyaSotirova Also, here is an over-complicated example of `ListView`: 

http://docs.nativescript.org/angular/code-samples/ui/listview.html

There are no point in using a class with a constructor and a loop to populate the array. One would almost never do it this way.
