### ISSUE TITLE
All NS's api-reference  return 404

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/docs-v7#738]
_From @1392324000 on April 21, 2017 0:41_

All NS's api-reference  return 404.This happens for days,U didn't notice it ???

_Copied from original issue: NativeScript/NativeScript#4034_

**Comment by tsonevn** [comment]
_From @1392324000 on April 21, 2017 1:22_

It works now,but it shows server's content.Hacking???

**Comment by tsonevn** [comment]
_From @danielgek on April 21, 2017 8:7_

@1392324000 the team is aware and taking care of it

**Comment by tsonevn** [comment]
Hi @1392324000, 
Thank you for pointing this problem,
Indeed there is an issue with building the `api-reference` for NativeScript docs.
As @danielgek mentioned we are aware of this behavior and will do our best to provide a need fix as soon as possible.

**Comment by PetyaSotirova** [comment]
Hi everyone,
We resolved the issue and the API should be in place and functioning. Apologies for any inconvenience this has caused you.
