### ISSUE TITLE
No provider for Http! error in Angular services tutorial

### ISSUE THREAD

**Issue by eablokker** [NativeScript/docs-v7#744]
https://docs.nativescript.org/angular/tutorial/ng-chapter-3#34-services

In the section "Exercise: Use an Angular service" the pasted code gives me an error: **No Provider for Http!**

Using these versions:
    "@angular/common": "2.4.3",
    "@angular/compiler": "2.4.3",
    "@angular/core": "2.4.3",
    "@angular/forms": "2.4.3",
    "@angular/http": "2.4.3",
    "@angular/platform-browser": "2.4.3",
    "@angular/platform-browser-dynamic": "2.4.3",
    "@angular/router": "3.4.3",
    "nativescript-angular": "1.4.0",
    "nativescript-theme-core": "~1.0.2",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.0.1",
    "tns-core-modules": "2.5.0"

**Comment by sis0k0** [comment]
Hey @eablokker,

Thanks for your interest in NativeScript! If you continue reading that section, everything will get clear. Look at `Exercise: Create an account` which is slightly below:

> Open app/app.module.ts and replace its contents with the following code, which adds a new NativeScriptHttpModule to the list of imports.
...
NativeScriptHttpModule is a NativeScript wrapper of Angular’s HttpModule, a module that declares all of Angular’s HTTP-based services—including the Http service that UserService uses.

**Comment by eablokker** [comment]
Oh ok, it wasn't clear. I was stuck on this for a while. I should have just kept going. Thanks!
