### ISSUE TITLE
Create article about creating UI Plugins with modules 3.0.0

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/docs-v7#754]
Related to [https://github.com/NativeScript/docs/pull/751](https://github.com/NativeScript/docs/pull/751)

To be synced the ns-plugins team. The old article is currently unpublished with a slug.

**Comment by bradmartin** [comment]
This is still being published @NickIliev. Found your note here: https://github.com/NativeScript/docs/commit/628d9b8953c1ac90314189c37143d6db80e3671d
but the page is still live (https://docs.nativescript.org/plugins/ui-plugin) - if it's not gonna be removed maybe just a header at the top that it's for `<3.0` or something to avoid confusion with new devs coming on right now with the breaking changes of 3.0

**Comment by PetyaSotirova** [comment]
I actually think that's cached and should go away in the next days, but let's make sure someone doesn't get really confused in the meantime. Good catch @bradmartin, thanks!

**Comment by codyfoss** [comment]
What are the chance we could get an article documenting the actual minimum requirements for a UI plugin? I can't seem to find that anywhere. Ideally with JS vanilla examples. Typescript and shell scripts are cool, but not super helpful for anyone trying to learn how to build vanilla JS plugins from scratch.

**Comment by NickIliev** [comment]
The articles about building of UI plugins are now updated and published.

[https://docs.nativescript.org/plugins/ui-plugin-composite](https://docs.nativescript.org/plugins/ui-plugin-composite)

[https://docs.nativescript.org/plugins/ui-plugin-custom](https://docs.nativescript.org/plugins/ui-plugin-custom)
