### ISSUE TITLE
Chapter 3 - ViewModel initialization

### ISSUE THREAD

**Issue by ElNinjaGaiden** [NativeScript/docs-v7#760]
Ok, I'm kind of new on NativeScript and I'm not sure if this is an issue related to the documentation or a (bad) usage of the framework I'm doing, but I tried this in 3 "hello world" apps and I got the same result on each of them.

It seems the inline initialization of a viewModel doesn't work. If I initialize a viewModel the way the chapter 3 shows, I don't get the properties bind on load time.

This doesn't work:

```
var Observable = require("data/observable").Observable;

var viewModel = new Observable({
    email: "user@domain.com",
    password: "password"
});

exports.loaded = function(args) {
    var page = args.object;
    page.bindingContext = viewModel;
};
```

This does:

```
var Observable = require("data/observable").Observable;
var viewModel = new Observable();

exports.loaded = function(args) {
    var page = args.object;
    viewModel.set('email', 'user@domain.com');
    viewModel.set('password', 'password');
    page.bindingContext = viewModel;
};
```

With _does not work_ I mean email and password are not displayed in textfields when the page loads

This is the view I'm using (is the same code that chapter 3 use):

```
<Page loaded="loaded">
    <StackLayout orientation="vertical">
        <Image src="res://logo" stretch="none" horizontalAlignment="center" />
        <TextField id="email" text="{{email}}" hint="Email Address" keyboardType="email" autocorrect="false" autocapitalizationType="none" />
        <TextField hint="Password" text="{{password}}" secure="true" />
        <Button text="Sign in" tap="signIn" />
        <Button text="Sign up for Groceries" class="link" tap="register" />
    </StackLayout>
</Page>
```

**Comment by ElNinjaGaiden** [comment]
Using the `fromObject` function seems to be the only way to initialize a viewModel inline.
This works:

```
var observable = require("data/observable");

var viewModel = new observable.fromObject({
    email: "user@domain.com",
    password: "password"
});

exports.loaded = function(args) {
    var page = args.object;
    page.bindingContext = viewModel;
};
```

**Comment by faizmh** [comment]
It works for the below code as well. Its 2 way binding as well. But I suspect since this approach doesnt use observable, i may be not be able to handle custom events.
(my guess - its an object and reference is used anyway)
```
var user = {
    email: "user@domain.com",
    password: "password"
}

exports.loaded = function(args) {
    page = args.object;
    page.bindingContext = user;
};
```

**Comment by tjvantoll** [comment]
Thanks all,

Sorry I missed this issue when it was first reported, but this should’ve been resolved with https://github.com/NativeScript/docs/commit/f57dca9f85365a3a30c5ab0d835652c64bbdd3cf so I’m going to close this.

Thanks again for letting us know! And if anyone is still having problems feel free to comment and we’ll take a look.
