### ISSUE TITLE
Outdated official DOCs of breaking changes: docs/releases/breaking-changes.md

### ISSUE THREAD

**Issue by thiagoufg** [NativeScript/docs-v7#766]
The official docs are outdated:
http://docs.nativescript.org/angular/releases/breaking-changes

I followed that to upgrade from {N} 2.4 to 3.0 but got many errors.

Then I realized there is another link for the breaking changes:
https://github.com/NativeScript/NativeScript/blob/master/Modules30Changes.md

Hope you guys get the official docs updated! 

By the way, I loved the framework.
Good work!

Thanks!

**Comment by PetyaSotirova** [comment]
Thanks for bringing this up and for the kind words! 
I addressed this with https://github.com/NativeScript/docs/pull/779 and I'm closing this issue.
