### ISSUE TITLE
consider updating the "NativeScript Advanced Setup: macOS" section of the official document

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/docs-v7#768]
_From @c1ngular on May 9, 2017 8:4_

since there have been major changes of Android SDK Tools , the current steps/tutorials may not set Android SDK environments properly ! 

e.g.  "brew cask install android-sdk" , now installs Android SDK Tools 25.2.3 by default , and sdk installation location is different , and "android update sdk --filter tools,platform-tools,android-25,build-tools-25.0.2,extra-android-m2repository,extra-google-m2repository,extra-android-support --all --no-ui " is no longer working ! 

 

_Copied from original issue: NativeScript/NativeScript#4145_

**Comment by radogado** [comment]
This installation broke my Android emulator 👎

**Comment by vchimev** [comment]
Hey @radogado,

could you please elaborate more on this?

Thanks,
@vchimev
