### ISSUE TITLE
Outdated property documentation

### ISSUE THREAD

**Issue by Cayan** [NativeScript/docs-v7#774]
I was looking for some documentation on how Property is used so I could upgrade some new plugins and the first result from google lead me directly to https://docs.nativescript.org/core-concepts/properties#declaring

I saw a lot of outdated components there like dependencyObservable so I gave up on the docs and went straight for the code!

I'd suggest at least a deprecated tag on this file

**Comment by tsonevn** [comment]
Hi @Cayan,
Thank you for bringing our attention to this, indeed the above-mentioned article contains a lot of outdated information, however, we are working on updating the info in the `properties` and `Building UI Plugin` articles. 
In the meantime, you could review those two links:
https://github.com/NativeScript/docs/blob/niliev/properties/core-concepts/properties.md
https://github.com/NativeScript/docs/blob/niliev/properties/plugins/ui-plugin.md
, which contains all needed updates.

**Comment by NickIliev** [comment]
@Cayan the articles about creating plugins using Property are now updated and published.

[https://docs.nativescript.org/plugins/ui-plugin-composite#add-ui-bits](https://docs.nativescript.org/plugins/ui-plugin-composite#add-ui-bits)

[https://docs.nativescript.org/plugins/ui-plugin-custom](https://docs.nativescript.org/plugins/ui-plugin-custom)
