### ISSUE TITLE
[Suggestion] Add a mention for the cache used in ui/images

### ISSUE THREAD

**Issue by Cayan** [NativeScript/docs-v7#775]
It took me a while and a lot of different plugins until I realize that nativescript's image already uses a cache. I believe this is not clear and people may look for other sources like I did.

Looking though the sources I found that NS uses LRUCache for Android, I couldn't find what it uses for iOS (I'm not sure on how to dig into iOS code yet).

**Comment by tsonevn** [comment]
Hi @Cayan,
The info about the caching the image is already mentioned in the [Android Image Optimization](https://docs.nativescript.org/ui/images-optimisations) article.

**Comment by Cayan** [comment]
What I meant is that a new NS user may take a while to find this article. It took me months.
A mention for that on the first google page related to "ns images" would help a lot.
