### ISSUE TITLE
WebView Documentation Missing & Link is Broken

### ISSUE THREAD

**Issue by sean-perkins** [NativeScript/docs-v7#782]
The previous link for the web view API reference is broken (404): http://docs.nativescript.org/api-reference/modules/_ui_web_view_.html

The link is also missing from the top-level page: https://docs.nativescript.org/api-reference/globals.html

**Comment by PetyaSotirova** [comment]
Hey @sean-perkins,
Thanks for reporting this. Both issues were resolved and the links should work correctly now.
Let us know if you notice anything else unusual.
