### ISSUE TITLE
Angular Tutorial - files missing from base install

### ISSUE THREAD

**Issue by mikehamil10** [NativeScript/docs-v7#785]
Began following the tutorial with the command
`tns create HelloWorld --template nativescript-template-ng-tutorial`

The app was created successfully, but the very next instruction says to cd into the directory and doing a tns run android (or ios in my case). I get the following error message:

`We have failed to check if we need to add a compatability LaunchScreen.xib due to: Error: ENOENT: no such file or directory, open '/Users/mike/Developer/NativeScript/HelloWorld/app/App_Resources/iOS/Info.plist'
ENOENT: no such file or directory, scandir '/Users/mike/Developer/NativeScript/HelloWorld/platforms/ios/HelloWorld/Resources'`

When I look at the contents of the folder, I can confirm that the App_Resources folder is missing.

**Comment by tsonevn** [comment]
Hi @mikehamil10,
This issue could be related to an issue with downloading the template from NPM.  Could you verify, whether you still have the same problem? If the issue still exists, please provide some more info about your environment(NativeScript, node versions).

**Comment by PetyaSotirova** [comment]
@mikehamil10 I'm closing this one due to inactivity. If you're still experiencing issues please let us know.
