### ISSUE TITLE
Error in Chapter 4.3 of tutorial

### ISSUE THREAD

**Issue by rmayoss** [NativeScript/docs-v7#786]
I was following the angular/typescript tutorial but got an error on the step in chapter 4.3 where I added the following code to the list.html file:

```
<GridLayout>
  <ListView [items]="groceryList" class="small-spacing">
    <ng-template let-item="item">
      <Label [text]="item.name" class="medium-spacing"></Label>
    </ng-template>
  </ListView>
</GridLayout>
```

The error I got was: 'Template parse errors: "let-" is only supported on template elements.'  

I searched around for a while and could not find a solution (or anyone else who was having this problem so I apologize if this is "user error").  I finally tried changing the "ng-template" in <ng-template let-item="item>...</ng-template> tag to just "template" and suddenly the app worked again in the emulator.  I'm a complete beginner at nativescript/angular/typescript, so again I apologize if this issue I'm reporting is misplaced.  I'm guessing that I have not properly imported all the modules I need?

**Comment by tsonevn** [comment]
Hi @rmayoss,
I tested this case on my side, however, was unable to reproduce problem similar to the reported one. 
For your convenience, I am attaching a sample project. Also, make sure that you are using latest NativeScirpt 3.0.3. You could verify this while running `tns --version`. If you are using some old version, you could update to the latest with `npm install nativescript --g`.

[Archive.zip](https://github.com/NativeScript/docs/files/1080781/Archive.zip)

**Comment by rmayoss** [comment]
Thanks @tsonevn.  I believe that was exactly the issue.  I have since upgraded to 3.0.3 and will try it again soon.  Thanks for your response.
