### ISSUE TITLE
WebView - a broken link referenced to the API 

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/docs-v7#789]
_From @eladcandroid on May 28, 2017 12:18_

Here: https://docs.nativescript.org/angular/code-samples/ui/web-view.html

When clicking on "WebView Class" to show the API reference for the control, the link is broken.

_Copied from original issue: NativeScript/NativeScript#4284_

**Comment by tsonevn** [comment]
Hi @eladcandroid,
Thank you for reporting this issue, 
We will research, what is causing this problem and will fix it.

**Comment by PetyaSotirova** [comment]
Hi @eladcandroid,
This was resolved with https://github.com/NativeScript/NativeScript/pull/4255 and the link should work OK now.
