### ISSUE TITLE
TabView – incorrect reference from the Angular Components page

### ISSUE THREAD

**Issue by EmilStoychev** [NativeScript/docs-v7#790]
Here – http://docs.nativescript.org/angular/ui/components.html#tabview the link to the TabView navigates to the [TabView article in the Core documentation](http://docs.nativescript.org/cookbook/ui/tab-view), while it should navigate to the one in the [NG cookbook](http://docs.nativescript.org/angular/cookbook/tab-view-ng.html) or, even better, to the [TabView NG code samples](http://docs.nativescript.org/angular/code-samples/ui/tab-view.html).

**Comment by tsonevn** [comment]
fixed with PR: [#792](https://github.com/NativeScript/docs/pull/792)
