### ISSUE TITLE
UI Element API documentation DOES NOT list events

### ISSUE THREAD

**Issue by AlexBachmann** [NativeScript/docs-v7#798]
In https://github.com/NativeScript/docs/blob/master//tutorial/ng-chapter-3.md in section 3.1 the reader is promised to find a list of available events for each UI element in the API documentation.

However, this list does not exist:
http://docs.nativescript.org/api-reference/classes/_ui_button_.button.html

Is there a new place, where we can find out about the available events of a UI element?

**Comment by tsonevn** [comment]
Hi @Batch1211,
Thank you for reporting this issue.
I tested the link for Button API Reference and it seems to work and to load the needed content.
