### ISSUE TITLE
Ui feedback effect (e.g. ripple effect ) on tap / touch

### ISSUE THREAD

**Issue by marco-gagliardi** [NativeScript/docs-v7#829]
Running the starting angular template ( `tns create MyApp --ng` ) I've noticed that there is no UI feedback when tapping on a `ListItem` within a `ListView`. 
I expected `LisItem` to reproduce the underground platform's native effect (e.g. the ripple effect on Android) out of the box  when tapped but this is not the case. Is this the default behavior for `ListItem` or is there any kind of code that prevents the touch effect to propagate in this example?

**Comment by NickIliev** [comment]
@marco-gagliardi the ListView will have its native ripple-effect as long as it does not implement some custom tap action inside the template (e.g **tap** event or **nsRouterLink** which is the case with the default template).
To preserve the ripple effect and in the same time implement navigation on tap for your item template use **itemTap** event on ListView

e.g.
```
<StackLayout class="page">
    <ListView [items]="items" class="list-group" (itemTap)="itemTapped()">
        <ng-template let-item="item">
            <Label [text]="item.name"
                class="list-group-item"></Label>
        </ng-template>
    </ListView>
</StackLayout>
```

**Comment by marco-gagliardi** [comment]
Hi @NickIliev thank you, this works perfectly! I was actually wondering what was the advantage with using the own itemTap event of ListView component instead of handling the tap event on each  template. 
PS: perhaps it was my fault, but I didn't find anything in the doc about that, it might be useful to mention this difference!

**Comment by NickIliev** [comment]
@marco-gagliardi  one of the main differences is that when you use **itemTap** (and no custom styles for the item template) the default **ripple** effect will be preserved for the item tap. 
Another thing to consider is that you might have complex UI for your item template and multiple taps for the different segments that create the item template. In this case, **itemTap** would be obsolete and providing different tap events for the different parts of your template would be the way to go.
