### ISSUE TITLE
404 - Directory not found on visiting this page 

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/docs-v7#850]
_From @macin40 on July 27, 2017 19:30_

https://docs.nativescript.org/plugins/building-plugins/ 

![screen shot 2017-07-28 at 12 56 01 am](https://user-images.githubusercontent.com/22330484/28688632-21080a54-7330-11e7-92be-f689bc912482.png)

_Copied from original issue: NativeScript/NativeScript#4613_

**Comment by tsonevn** [comment]
Hi @macin40,
Thank you for pointing this issue.
We will research it and will fix the broken link. In the meantime, you could find the article [here](http://docs.nativescript.org/plugins/building-plugins).

**Comment by etabakov** [comment]
Hi @macin40,
Can you point us to the location where this broken link occurs, so we can fix it? Unfortunately, I couldn't find it using automated tools.
Thanks!

**Comment by codyfoss** [comment]
It's the trailing slash, of course. Most CMSes would handle this automatically. A simple redirect would fix the issue. If that's not an option (or it's something you'd prefer not to do), seems like the issue should be closed.

**Comment by etabakov** [comment]
Thanks for the suggestions @codyf. A redirect is already put in place.
