### ISSUE TITLE
Cannot read property "text" of undefined.

### ISSUE THREAD

**Issue by lusabo** [NativeScript/docs-v7#852]
I'm doing the tutorial and in the item 3.3 is ocurring an error telling that the app cannot read property "text" of undefined. How to solve it?

**Comment by tsonevn** [comment]
Hi @lusabo,
Could you provide more detailed info about your case? Also, it would help if you could provide a sample project, which could be used for debugging or at least minimum set of code, which will allow us to investigate this scenario.

**Comment by codyfoss** [comment]
He said he was working through the tutorial. I haven't verified the error that's been reported here, but I would assume that's the project and code. If there's no error generated using the tutorial code, then I'd close this issue unless more details are added.

**Comment by tsonevn** [comment]
Hi @codyf,
We understand your point. Regarding the topic, we have a test app created while following the steps from the tutorial, which is built and work as expected on both iOS and Android. the app could be found [here](https://github.com/NativeScript/sample-Groceries/).
However, would like to verify, if we are missing something and the sample project would help for this case.
