### ISSUE TITLE
tooling/testing.md code samples are corrupt on docs.nativescript.org

### ISSUE THREAD

**Issue by madakk** [NativeScript/docs-v7#855]
While the samples are correctly formatted in the .md file and show fine in preview on github:

![snapshot 1](https://user-images.githubusercontent.com/24660923/28893556-8d601e2c-77da-11e7-9d4c-4391c8e35438.png)

On the actual website, they are corrupted, probably due to a failed conversion into a tab box:

![snapshot 2](https://user-images.githubusercontent.com/24660923/28893583-aae95ada-77da-11e7-8f91-4227745a114c.png)

**Comment by tsonevn** [comment]
Hi @madakk,
I reviewed this case, however, I was unable to find any difference in the code snippets provided in the [web site](http://docs.nativescript.org/tooling/testing) and those in the[ .md file in GitHub](https://github.com/NativeScript/docs/blob/master/docs/tooling/testing.md).

Could you provide some more info about the case and what is the problem on the site?

**Comment by madakk** [comment]
Not sure what info you're looking for? I'm just reporting what I'm seeing, the website is broken. I don't know anything about the inner workings of the website or why this happens.

**Comment by etabakov** [comment]
Looking at the article at the moment - the problem doesn't reveal itself. Feel free to reopen the issue if it arises again.
