### ISSUE TITLE
tutorial/ng-chapter-6.md says NativeScript doesn't expose placeholder-color, but it does now

### ISSUE THREAD

**Issue by madakk** [NativeScript/docs-v7#856]
This was finally resolved under https://github.com/NativeScript/NativeScript/issues/712 and now is supported, so the text should probably be changed to say that while this can be done with the provided CSS attribute, this is how you'd do it in the native way instead.

**Comment by tjvantoll** [comment]
Thanks for reporting this @madakk! Can’t believe this hasn’t come up before actually 😄 

I’m adding the “help wanted” label in case anyone from the community wants to tackle this. Otherwise I’ll change the wording up when I get from vacation at the end of next week.

**Comment by radeva** [comment]
I'm closing this issue since it is resolved with the above PR.
