### ISSUE TITLE
"Improve this article" button link in Docs is broken

### ISSUE THREAD

**Issue by surdu** [NativeScript/docs-v7#860]
When clicked anywhere in Docs it points to a GitHub 404 page

**Comment by airandfingers** [comment]
+1

For example, the link for the "Improve this article" button at the bottom of http://docs.nativescript.org/tutorial/chapter-1 points to https://github.com/NativeScript/docs/blob/master//tutorial/chapter-1.md - notice the two /s before tutorial.

I'm betting these buttons are generated somewhere, but I'm new to this repo, so I won't try to fix it myself.

**Comment by PetyaSotirova** [comment]
Thanks for reporting this one @surdu and @airandfingers. 
The was resolved with https://github.com/NativeScript/docs/commit/55deb56c5c40e6112f2a6bf0e1c8652e55aa1c05 and the buttons should be working fine in all articles now.
