### ISSUE TITLE
App_Resources/Android/values/styles.xml says "actioon-bar" instead of "action-bar" in the comment in all templates/examples

### ISSUE THREAD

**Issue by madakk** [NativeScript/docs-v7#874]
This is a minor typo, but it's a shame that every app built upon these templates will carry on this typo.

**Comment by tsonevn** [comment]
fixed with PRs [#66](https://github.com/NativeScript/template-hello-world/pull/66), [#60](https://github.com/NativeScript/template-hello-world-ng/pull/60), [#34](https://github.com/NativeScript/template-hello-world-ts/pull/34)
