### ISSUE TITLE
Broken link on NavigationTransition page

### ISSUE THREAD

**Issue by sean-perkins** [NativeScript/docs-v7#882]
https://docs.nativescript.org/api-reference/interfaces/_ui_frame_.navigationtransition.html

The  `AnimationCurve enumeration` link is broken.

**Comment by tsonevn** [comment]
Hi @sean-perkins,
Thank you for sharing this problem with us. You could keep track on this issue for further info.

**Comment by tsonevn** [comment]
fixed with PR [#4799](https://github.com/NativeScript/NativeScript/pull/4799)
