### ISSUE TITLE
Replace Groceries repo link from tjvantoll/Groceries to NativeScript/sample-Groceries

### ISSUE THREAD

**Issue by leocaseiro** [NativeScript/docs-v7#886]
Hi Guys, 

I was reading the docs and I believe there's an old link for the Groceries repo.
[ng-chapter 3](http://docs.nativescript.org/angular/tutorial/ng-chapter-3) there's a link from:

> NOTE: To show that sharing code between native and web projects is possible, and not theoretical, feel free to peruse our [web implementation of Groceries](https://github.com/tjvantoll/Groceries), which uses the exact same shared folder this guide’s native implementation does.

I wonder if should be going to the new repo https://github.com/NativeScript/sample-Groceries instead.

Perhaps, @tjvantoll would be the most indicated to confirm that.

**Comment by tjvantoll** [comment]
Ah, good catch @leocaseiro! Yep, we switched the main implementation over to https://github.com/nativescript/sample-Groceries/tree/web but never updated that link. I’ll do that now.
