### ISSUE TITLE
Broken Links from /angular/ui/components.html for ListView, HtmlView, ListPicker 

### ISSUE THREAD

**Issue by mictay** [NativeScript/docs-v7#887]
There are links to href="true" inside the components.html
[404 links to true](https://docs.nativescript.org/angular/ui//angular/ui/true)

By doing a View Source I found 3 instances of this broken link...

# ListView (line 442)
```
<p>The  <a href="true">ListView</a> shows items in a vertically scrolling list. ...
```

I think the correct href should go to this page:
[https://docs.nativescript.org/angular/ui/list-view](https://docs.nativescript.org/angular/ui/list-view)

# HtmlView (line 465)
```
<p>The  <a href="true">HtmlView</a>
```
I'm unable to find the angular href page for this component.

# ListPicker (line 603)
```
<p>With the  <a href="true">ListPicker</a> widget, you can pick a value from a list.</p>
```
I'm unable to find the angular href page for this component.

**Comment by etabakov** [comment]
Thanks for letting us know about these links @QuinnZillian. They will be fixed with the next deployment of the documentation.
