### ISSUE TITLE
checkSelfPermission is not function

### ISSUE THREAD

**Issue by ghost** [NativeScript/docs-v7#888]
nativescript-camera . module
error:
![image](https://user-images.githubusercontent.com/18701960/29758236-6c1d311e-8be4-11e7-8d5b-467aab42af72.png)
 
code:
var isAvailable = camera.isAvailable();
    console.log(isAvailable)
    if (isAvailable) {
        var imageModule = require("ui/image");
        camera.takePicture()
            .then(function(imageAsset) {
                console.log("Result is an image asset instance");
                var image = new imageModule.Image();
                image.src = imageAsset;
            }).catch(function(err) {
                console.log("Error -> " + err.message);
            });
    }

![image](https://user-images.githubusercontent.com/18701960/29758259-97ef29c8-8be4-11e7-8189-71d52bc03d0b.png)

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/nativescript-camera#54
