### ISSUE TITLE
View.eachChildView callback definition has an unexplained boolean return value

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/docs-v7#889]
_From @madakk on August 27, 2017 18:1_

There's no documentation of what the return value is supposed to represent, and no implementation of eachChildView seems to actually use it for anything.

_Copied from original issue: NativeScript/NativeScript#4759_

**Comment by madakk** [comment]
It looks like `eachChild` also has the same undocumented return value, which doesn't seem to be used for anything by any implementation.

However, `eachDescendant` which has a similar signature, defines the callback return value as following:

> If function returns false it breaks the iteration.

And indeed the implementation in ViewBase seems to adhere to that description.

**Comment by tjvantoll** [comment]
This seems like the best (only?) place to have this discussion: https://docs.nativescript.org/core-concepts/properties#iterating-over-view-children.
