### ISSUE TITLE
Long-form two-way data binding example doesn't work

### ISSUE THREAD

**Issue by airandfingers** [NativeScript/docs-v7#905]
The [Two-way Data Binding](https://github.com/NativeScript/docs/blob/master/docs//tutorial/ng-chapter-3.md#----exercise-two-way-data-binding-with-angular) section of the Angular Tutorial, Chapter 3 contains this sentence:

> In the case of this example, [(ngModel)]="email" is shorthand for [text]="email" (ngModelChange)="email=$event", which binds the email element’s text attribute to an email property and adds a change event handler that updates the email property’s value whenever the user makes a change.

I tried replacing `[(ngModel)]="email"` with `[text]="email" (ngModelChange)="email=$event"`, but  `ngModelChange` didn't seem to do anything; the field still exhibited one-way data-binding.

I'm guessing this is a docs issue, not a bug.

**Comment by vakrilov** [comment]
I think the correct way to do is `[text]="email" (textChange)="email=$event"`. Might be really a error in the docs.

**Comment by etabakov** [comment]
Indeed, this looks like a problem in the documentation. The correct syntax should be `[text]=“email” (textChange)=“email=$event.object.text”`.
