### ISSUE TITLE
Quick Start macOS setup 404

### ISSUE THREAD

**Issue by jevenson** [NativeScript/docs-v7#912]
https://github.com/NativeScript/docs/blob/master/docs/start/quick-setup.md

This command fails to execute because the url throws a 404

`ruby -e "$(curl -fsSL https://www.nativescript.org/setup/mac)"`

**Comment by grimaldodev** [comment]
Same here

**Comment by tsonevn** [comment]
Hi @jevenson , @grimaldows 
The problem with the URL is fixed and the setup script should be executed properly now.
Please let me know if you have some further problems with the setting up your environment.

**Comment by jevenson** [comment]
Looks good, thank you!
