### ISSUE TITLE
Android studio is not installed, but needed for managing virtual android devices

### ISSUE THREAD

**Issue by Softpak-JeroenE** [NativeScript/docs-v7#914]
The first step on the [Android virtual devices page](https://docs.nativescript.org/tooling/android-virtual-devices) is to open Android Studio. However, this software is not installed when you follow the instructions on the [quick setup page](https://docs.nativescript.org/start/quick-setup).

After I installed Android Studio it still did not work. I think (but not sure) that's because Android Studio installs its own adroid-sdk. I removed Android Studio and reinstalled it but deselected the SDK and pointed it towards c:\Android\android-sdk. At least now I can start the Android Virtual Devices.

**Comment by NickIliev** [comment]
@Softpak-JeroenE Android Studio is not needed to work with NativeScript so this is the reason it is not included in the setup scripts (it is also quite a large program). You can also use third-party emulators to avoid having to install Android Studio. However, the article about working with AVDs is assuming that you have Android Studio installed and configured properly and the topic there is not related to setting SDK path.
