### ISSUE TITLE
Install on Mac Failed, is the link failed?

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/docs-v7#915]
_From @xhe on September 20, 2017 15:25_

## Please, provide the details below:

Can not run the install script in Mac, the url not existed anymore

I am following the doc to install TNS in my mac

ruby -e "$(curl -fsSL https://www.nativescript.org/setup/mac)"

But this link is not available anymore, can anyone else update me with the new link? Or how to install and set env in mac?

Thanks

_Copied from original issue: NativeScript/NativeScript#4862_

**Comment by tsonevn** [comment]
Hi @xhe,
Thank you for pointing this issue.
We will do our best to fix the broken link. In the meantime, I would suggest following the [advanced setup instructions here](http://docs.nativescript.org/start/ns-setup-os-x), which would help you to setup your environment.

**Comment by xhe** [comment]
yes, thanks

**Comment by dejitaiza** [comment]
For future reference, I also encountered the same issue, and found this instead (taken from https://github.com/NativeScript/nativescript-cli/blob/master/setup/mac-startup-shell-script.sh) : 

```
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/NativeScript/nativescript-cli/production/setup/native-script.rb)"
```

**Comment by tsonevn** [comment]
Hi @xhe, @dejitaiza
The problem with the URL is fixed and the setup script should be executed properly now.
Please let me know if you have some further problems with the setting up your environment.
