### ISSUE TITLE
Advanced Mac Setup Doesn't Work with Java 9

### ISSUE THREAD

**Issue by pierretasci** [NativeScript/docs-v7#916]
I attempted the necessary steps to install the android development environment. I followed the link to install Java SE and picked JDK 9 since it was the latest. The documentation claimed anything JDK 8 or later would be fine.

Instead, I found that it did not work at all with JDK 9. The brew command to install android-sdk just would not work with JDK 9 as my latest version on mac. I had to clean everything and install the latest JDK 8 for it to work.

This should be called out explicitly.

**Comment by etabakov** [comment]
Hi @pierretasci, you are right. Currently, NativeScript requires explicitly Java 8. This should be documented and the setup scripts should be adjusted to ensure explicit version of the JDK.

**Comment by etabakov** [comment]
The documentation is updated and changes in the setup scripts are on PR. Closing the issue.

**Comment by ghost** [comment]
Thanks for this issue i did not installed version 9.
