### ISSUE TITLE
ListPicker Documentation Missing (404)

### ISSUE THREAD

**Issue by bradkeys** [NativeScript/docs-v7#925]
In the [components page documentation](https://docs.nativescript.org/ui/components#listpicker), the [link](https://docs.nativescript.org/cookbook/ui/listpicker) to view details on the ListPicker widget results in a 404.

**Comment by etabakov** [comment]
Thanks @bradkeys. This will be fixed with the next update of the documentation. Meanwhile, the resource you are looking for can be found at [https://docs.nativescript.org/cookbook/ui/list-picker](https://docs.nativescript.org/cookbook/ui/list-picker)
