### ISSUE TITLE
ns-setup-win.md Step 5

### ISSUE THREAD

**Issue by Babalooch23** [NativeScript/docs-v7#927]
The command you posted in step 5 of this document:

"%ANDROID_HOME%\tools\bin\sdkmanager" "tools" "platform-tools" "platforms;android-25" "build-tools;25.0.2" "extras;android;m2repository" "extras;google;m2repository"

didn't work on windows 10, but, I think OS is irrelevant. Rather, I think this command failed like this:

> Warning: An error occurred during installation: Failed to move away or delete existing target file: C:\Android\android-sdk\tools Move it away manually and try again..

because one needs the sdkmanager that is in \tools for your command to work. It can't be moved, and used, at the same time. Reason: I believe Google has monkeyed with things so that Android Studio is the only way to use the sdkmanager now. What I did to fix this was listen to this guy: https://stackoverflow.com/a/43856478 and copied C:\Android\android-sdk\tools to "C:\bah\tools", a temp directory, then, from command prompt C:\bah\tools\bin, I ran:

sdkmanager.bat --sdk_root=C:\Android\android-sdk "tools" "platform-tools" "platforms;android-25" "build-tools;25.0.2" "extras;android;m2repository" "extras;google;m2repository"

and it worked. Please consider this workaround in the documentation, or, at least don't ask people to run the current command, as Google has apparently broken it.

Regards,
Babalooch

**Comment by petekanev** [comment]
Dropping `platform-tools` from the arguments list should be sufficient to make the sdk installation go through, I think. Since platform-tools comprise the sdkmanager, and other executables.
