### ISSUE TITLE
General Request For Timely Updates in Official Documentation

### ISSUE THREAD

**Issue by Sibling10** [NativeScript/docs-v7#93]
It really would be nice if the official documentation is updated in a timely manner based on changes --- especially breaking changes --- implemented in every version update/release.

For example, in the Application Management section, the supposedly obsolete "local-settings" module is still referenced in the text and sample code under "Persist and Restore Application Settings".

**Comment by ErjanGavalji** [comment]
@Sibling10, thanks for the notes!

These were fixed with PR #198

**Comment by ErjanGavalji** [comment]
Closing the issue now.
