### ISSUE TITLE
Unable to find information related to inputable view

### ISSUE THREAD

**Issue by bigopon** [NativeScript/docs-v7#935]
For example: Slider class has no information about `valueChange` event, or text field has no information about `textChange` event. I believe that listening to those events works ?

Can I please have a link to source to look for those at least ? Or some suggestion how to listen to change event on this view ? I'm asking this as I feel the only way to use Nativescript is to use its magic, there's noway to do things imperatively. Please correct me if I'm wrong 😄

**Comment by NickIliev** [comment]
@bigopon The valueChange event is executed when the value of a property has changed. 

The NativeScript 3.x.x convention is that if the property is called 'text' the change event will be a concatenation of `text` and `Change` result in `textChange`. So following these thoughts for `Slider` the change event for `value` will be `valueChange`

Article about the Property system in NativeScript can be found [here](https://docs.nativescript.org/core-concepts/properties#property-system)
