### ISSUE TITLE
Please Improve Data Binding Documentation

### ISSUE THREAD

**Issue by Sibling10** [NativeScript/docs-v7#94]
Data binding is such an important feature in NativeScript and key to understanding its power.

Is it okay for the Documentation Team to find time to revisit the "App: Data Binding" doc and make it just a little bit easier to understand, especially the "Using expressions for bindings" section?

Thanks guys!

**Comment by ErjanGavalji** [comment]
@Sibling10 Thanks for the input! I'm closing this issue as binding documentation got improved with PR #98.

Your input on the quality and any suggestions on further improvements will be most appreciated.

Closing the issue now.
