### ISSUE TITLE
Html-View Docs Page Inaccessible

### ISSUE THREAD

**Issue by peterkrieg** [NativeScript/docs-v7#946]
The html-view docs page currently isn't accessible. 

From https://docs.nativescript.org/cookbook/ui, the link is https://docs.nativescript.org/cookbook/ui/html-view   (but immediately redirects to action-bar instead).

**Comment by etabakov** [comment]
Thanks for letting us know about the problem @peterkrieg! The fix is deployed on LIVE and should be fine on your side.
