### ISSUE TITLE
Broken links on docs and Google native search results

### ISSUE THREAD

**Issue by dean-huczok** [NativeScript/docs-v7#947]
On the home page docs.nativescript.org the submenu "NativeScript with Angular" link does not route to the proper page. It needs the ".html" suffix removed:
Link is: docs.nativescript.org/angular/start/introduction.html
Should be: docs.nativescript.org/angular/start/introduction

Also some native Google search results have broken links, such as for Angular Scroll View. Perhaps some 301 redirects could help? 
Link is: docs.nativescript.org/code-samples/ui/scroll-view [returns a 404 error, does not redirect]
Should be: docs.nativescript.org/angular/code-samples/ui/scroll-view

Sorry I'm not familiar with Jekyll otherwise I would go in and help fix this stuff, it shouldn't be too hard to fix stuff like this right?

**Comment by etabakov** [comment]
The problem with the links in the navigation with redundant ".html" extensions is fixed. I will need some time to investigate the problem with the custom google search. I will let you know as soon as I have more information.

**Comment by etabakov** [comment]
The problem with the search is resolved as well (might need to clear your cache). Since both issues are fixed now - I'm closing the issue. Feel free to reopen if they still persist on your side.
