### ISSUE TITLE
Bug: After running tests building project or running it will use the embedded unit test runner version

### ISSUE THREAD

**Issue by souly1** [NativeScript/docs-v7#949]
Hi,
There is an issue when working with native script test framework: 
after running tests with 'tns test android' running 'tns build/run android' will use the apk with the embedded test runner and not update to be without it.

This is an issue with CI normal flow as you would expect it to first run tests and then build apk.

Thanks

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/nativescript-cli#3188
