### ISSUE TITLE
[request] Show some comparison between options

### ISSUE THREAD

**Issue by bigopon** [NativeScript/docs-v7#952]
Currently we have N + Js, N + Ts, N + Ng as mature options to choose from. But I could not find any information on how different they are. Is Ng worth it to be introduced into my Ns apps. What the pros and cons. Im asking as I see Ns good and already does a lot of things Ng does why is Ng officially supported

**Comment by NickIliev** [comment]
@bigopon this is pure matters of personal choice.  Angular provides benefits for a lot of web developers familiar with the Angular paradigm that at the same time are not so deep with the native mobile concepts.
As stated in [this post](https://www.nativescript.org/faq)

> **Do I have to use Angular?**
> Nope. NativeScript has full support for Angular and we will continue to keep our implementation up to date with the Angular framework. However, one of the benefits of NativeScript is the freedom to choose the architecture you prefer for your applications. If you want to use Angular, great! If you want to use just JavaScript, no problem!. You can even build your app in TypeScript or Babel if you want.
> 
> We will continue to provide architectural freedom to the NativeScript community. If you want more detail on the pros and cons of each approach, read this chat between our developer relations team and a few of our NativeScript community Experts.
