### ISSUE TITLE
Documentation should be available offline

### ISSUE THREAD

**Issue by ghost** [NativeScript/docs-v7#954]

**Comment by NickIliev** [comment]
Hey, @Fabiyo-90 the NativeScript/docs repository has detailed README.md covering all the topics from contributing to local builds using Vagrant. Let me know if you need some specific information.

[https://github.com/NativeScript/docs/blob/master/README.md](https://github.com/NativeScript/docs/blob/master/README.md)

**Comment by ghost** [comment]
Why not a doc with http://devdocs.io ? It's gonna be simplier

**Comment by etabakov** [comment]
Thanks for the suggestion. From what I understand DevDocs looks like a great way to browse different documentations on a single place, but it still needs an original source to scrape the content from. While we could expose our documentation through [devdocs.io](http://devdocs.io), this could not replace our current documentation: [docs.nativescript.org](http://docs.nativescript.org).

We will evaluate the enablement of our documentation through DevDocs and will eventually include it in our roadmap. Meanwhile, if you can explain what you are trying to achieve and what are you struggling with - we might be able to help you.

**Comment by ghost** [comment]
I am in a country where the connection to use the internet is very expensive so I would like to have localhost documentation that is easy to use or install. I would have liked just having folder containing html files like the documentation of the framework fuelphp (www.fuelphp.com) for example, not very complicated to use. Just have the docs and click on the index.html file and everything is there.
Student from the Democratic Republic of Congo and I am a french man and my english is not good!

**Comment by ghost** [comment]
I love NativeScript but I can not always connect to the internet

**Comment by etabakov** [comment]
Thanks for the clarification. It looks like your requirement is to have the documentation available offline. I will rename the title of the issue to state this clearly. We will prioritise this feature and eventually include it in the roadmap. Meanwhile, you can check some tools that can make an offline copy of a website for you, like [HTTrack](https://www.httrack.com/)

**Comment by ghost** [comment]
I will try to use HttTrack then report to you, I have an old version of htttrack but it hurts the copy of the site so I try to download a new version and I will tell you more

**Comment by ghost** [comment]
HttTrack takes a lot of time from 8am and saw the bad connection we have in Congo, I feel that I will need a whole day is 24h!
It's very very very bad !

**Comment by etabakov** [comment]
The local setup instructions are updated. Now you can setup the whole documentation locally and use it as needed.
