### ISSUE TITLE
the readme doesn't list instructions for the android emulator

### ISSUE THREAD

**Issue by jaymedavis** [NativeScript/docs-v7#955]
the readme for the advanced MacOS instructions links to an article that walks you through how to do it on windows.

**Comment by jaymedavis** [comment]
it appears to be my issue that the avd manager option isn't listed in android studio.  😢

**Comment by NickIliev** [comment]
@jaymedavis on Android Studio 3 the AVD Manager might not be listed unless you install the latest Android Tools and Android Build Tools (ver.27) - try updating the tools via SDK Manager and your links to the AVD Manager should appear in Android Studio 3

**Comment by jaymedavis** [comment]
Thanks @NickIliev - that’s what it ended up being. I missed Android Studio throwing warnings in a pane that wasn’t visible. haha
