### ISSUE TITLE
AppModule.resources is undefined!

### ISSUE THREAD

**Issue by shiv19** [NativeScript/docs-v7#956]
Hi!
I’m trying to follow this part of the documentation for {N} Core
https://docs.nativescript.org/core-concepts/data-binding#example-7-adding-converters-in-the-application-module-resources1

when I do

```app = require("application")
console.log(app.resources);```
I am getting `undefined`

therefore I’m not able to add a converter to the app module resources.

Is there something that I’m missing?

(same has been asked in the forum, https://discourse.nativescript.org/t/appmodule-resources-is-undefined/3085/4)

**Comment by EddyVerbruggen** [comment]
I guess that changed to [app.getResources()](https://github.com/NativeScript/NativeScript/blob/011be368b1f66746e14c74867e0d55f60d3ea882/tns-core-modules/application/application.d.ts#L122) in [this commit 8 months ago](https://github.com/NativeScript/NativeScript/commit/e6250e718a613baea83d2eeb8dc0d426ce4fdc9e).
