### ISSUE TITLE
java.net.UnknownHostException: Unable to resolve host

### ISSUE THREAD

**Issue by charlessabenin** [NativeScript/docs-v7#964]
Hi, I am new with NativeScript and i have an error with this function from groceries NativeScript template 
```
viewModel.login = function() { 
		return fetchModule.fetch("https://LINK/api/restifydb/..." + "oauth/token", {
			method: "POST",
			body: JSON.stringify({
				username: viewModel.get("email"),
				password: viewModel.get("password"),
				grant_type: "password"
			}),
			headers: {
				"Content-Type": "application/json"
			}
		})
		.then(handleErrors)
		.then(function(response) {
			return response.json();
		})
		.then(function(data) {
			config.token = data.Result.access_token;
		});
	};
```
the error is : JS: TypeError: Network request failed: java.net.UnknownHostException: Unable to resolve host "LINK": No address associated with hostname

the LINK is from a different server with restifydb and it is not even working on mobile device.

the permissions
`<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>`
`<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>`
`<uses-permission android:name="android.permission.INTERNET"/>`

Can anybody help !?

**Comment by NickIliev** [comment]
@charlessabenin if you are trying to pass the variable `LINK` then you should pass it as a variable not as a plain text.

e.g. (TypeScript)
```
var LINK = "www.youtube.com";
fetchModule.fetch("https://" + LINK + "/api/restifydb/..." + "oauth/token",
// more code follows here
```

In your case, you are trying to fetch `https://LINK` which is not a valid host address

**Comment by NickIliev** [comment]
@charlessabenin btw if you are trying to access local alias (like `localhost`) on emulator keep in mind that emulators have different loopback address - see [this thread ](https://stackoverflow.com/a/39958955/4936697)for details

**Comment by charlessabenin** [comment]
Thanks @NickIliev
