### ISSUE TITLE
Usage of outdated API is presented in the documentation

### ISSUE THREAD

**Issue by devoto13** [NativeScript/docs-v7#973]
According to [changelog](https://github.com/NativeScript/nativescript-angular/blob/a3ee0c74df76dfa23b9cdc6532c270aeccbfd3cc/CHANGELOG.md#040-2016-08-19) `nativeScriptBootstrap` method is removed long ago, however its usages are still present in several places in the documentation. See [search results](https://github.com/NativeScript/docs/search?q=nativeScriptBootstrap&type=Code&utf8=%E2%9C%93).

- Application Architecture - update to mention importing `NativeScriptRouterModule` instead?
- Application Lifecycle - update to mention usage of `platformNativeScriptDynamic().bootstrapModule()`?
- Angular Bootstrap  - remove this and previous line from example? Looks like stale code.
- Action Bar doc - update to `platformNativeScriptDynamic({startPageActionBarHidden: true}).bootstrapModule()`?

If this sounds good, I can prepare a PR.

**Comment by etabakov** [comment]
@devoto13 your observations are correct. We will be happy to review your pull request. Thanks for bringing this to our attention.

**Comment by devoto13** [comment]
@etabakov I'm having issues with building documentation locally. Any idea how to fix it?
See more details in Slack: https://nativescriptcommunity.slack.com/archives/C0L9EJS7Q/p1511960429000205

Looks like build script tries to fetch something from `nsbuild01.telerik.com`, which is not publicly available.

**Comment by etabakov** [comment]
Unfortunately, building the documentation locally is not something that can be easily done currently. We are planning to improve on this and you can actually try building from this branch: https://github.com/NativeScript/docs/tree/kkotorov/allow-local-builds. However, if you don't plan to add new articles or other drastic changes - I encourage you to use a simple Markdown editor and submit the changes directly. This works in most of the cases.

**Comment by devoto13** [comment]
I see. I re-use one of the existing snippets and wanted to make sure it works correctly. Opened a PR.
