### ISSUE TITLE
Extending the Layouts code samples in the cookbook

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/docs-v7#976]
Extending the provided examples of the articles related to the Layouts.
* [absolute-layout](https://docs.nativescript.org/cookbook/ui/layouts/absolute-layout)
* [dock-layout](https://docs.nativescript.org/cookbook/ui/layouts/dock-layout)
* [wrap-layout](https://docs.nativescript.org/cookbook/ui/layouts/wrap-layout)

**Comment by pedromorgan** [comment]
Need to add the style+passing etc tags to the layouts also

**Comment by tjvantoll** [comment]
We could also drop a TIP on this page to point people at https://www.nslayouts.com/.
