### ISSUE TITLE
API documentation index is not jumping to page anchor in Safari

### ISSUE THREAD

**Issue by pentool** [NativeScript/docs-v7#980]
Hello,

The API documentation has an Index section for each class. For example, here is the page for the Page class: https://docs.nativescript.org/api-reference/classes/_ui_page_.page. When you click on any method or property name in the index table (using Safari), the whole page gets reloaded, but the documentation is not jumping to the method/property anchor you clicked. Instead, it just reloads the page to the top of the page itself.

**STEPS**:
1. Use Safari on the Mac
2. Go to a class documentation (eg https://docs.nativescript.org/api-reference/classes/_ui_page_.page)
3. In the Index table, click on any method/property name link.
4. Instead of going to the method/property anchor you just click on, the page simply reloads.

This seem to work correctly in Firefox (and possibly in Chrome), but not in Safari. (Although even in Firfox it still reloads the whole page for some reason as opposed to just simply jump to the anchor.)

OS X 10.11.6
Safari 11.0.1

**Comment by etabakov** [comment]
Just tested with Safari on Mac Version 11.1 (13605.1.27.2.1) and cannot reproduce the problem. Feel free to reopen the issue if it arises again.
