### ISSUE TITLE
Fix the link behind "Repeater" in ui/basics article

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/docs-v7#988]
Reported via the documentation feedback form

> There's a link on the word "Repeater" (towards the end of the page). Just search the page for the word "Repeater" to find it. I was under the impression that the link takes you to a page that describes the "Repeater" component/item. But the page the link is linking to has no "Repeater" item on it.

[https://docs.nativescript.org/ui/basics](https://docs.nativescript.org/ui/basics)

**Comment by tsonevn** [comment]
fixed with PR - https://github.com/NativeScript/docs/pull/986
