### ISSUE TITLE
tns update next is invalid command

### ISSUE THREAD

**Issue by mhmo91** [NativeScript/docs-v7#992]
Hi guys, as per the upgrade instructions here 
https://docs.nativescript.org/releases/upgrade-instructions
When i try to run the command tns update next, it throw the error in this screen.
![image](https://user-images.githubusercontent.com/3815200/33658899-00d3230e-da87-11e7-8fd6-0b19e1e682e4.png)

**Comment by etabakov** [comment]
This is a known issue and it should be fixed in @next. It will also be included in the 3.4 release, which is coming very soon. Thanks for reaching out to us!
